#ifndef GOOM_CONFIG
#define GOOM_CONFIG

#ifdef MID
#define GOOM_TEXTURE_WIDTH  512
#define GOOM_TEXTURE_HEIGHT 256
#else // MID
#define GOOM_TEXTURE_WIDTH  1280
#define GOOM_TEXTURE_HEIGHT 720
#endif // MID

#endif // GOOM_CONFIG
