#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACCENT_5 = std::vector<vivid::srgb_t>{
    {0.49804F, 0.78824F, 0.49804F},
    {0.74510F, 0.68235F, 0.83137F},
    {0.99216F, 0.75294F, 0.52549F},
    {1.00000F, 1.00000F, 0.60000F},
    {0.21961F, 0.42353F, 0.69020F},
};

} // namespace GOOM::COLOR::COLOR_DATA
