#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_19 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.23529F, 0.18039F, 0.34902F},
    {0.29412F, 0.23137F, 0.40000F},
    {0.35686F, 0.28235F, 0.45098F},
    {0.43137F, 0.32941F, 0.50196F},
    {0.50588F, 0.36863F, 0.54118F},
    {0.57255F, 0.38824F, 0.56471F},
    {0.63529F, 0.40000F, 0.57647F},
    {0.69804F, 0.40392F, 0.58431F},
    {0.76863F, 0.43137F, 0.60784F},
    {0.81961F, 0.48235F, 0.64706F},
    {0.83529F, 0.53725F, 0.68627F},
    {0.83137F, 0.58431F, 0.72157F},
    {0.82745F, 0.62745F, 0.75294F},
    {0.83137F, 0.67843F, 0.78824F},
    {0.84314F, 0.72941F, 0.82353F},
    {0.85882F, 0.78824F, 0.86275F},
    {0.87843F, 0.84314F, 0.90196F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
