#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_7 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.35686F, 0.28235F, 0.45098F},
    {0.57255F, 0.38824F, 0.56471F},
    {0.76863F, 0.43137F, 0.60784F},
    {0.83137F, 0.58431F, 0.72157F},
    {0.84314F, 0.72941F, 0.82353F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
