#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_11 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.28627F, 0.22353F, 0.39216F},
    {0.40000F, 0.31373F, 0.48235F},
    {0.52941F, 0.37647F, 0.55294F},
    {0.65098F, 0.40000F, 0.58039F},
    {0.76863F, 0.43137F, 0.60784F},
    {0.83137F, 0.52549F, 0.67843F},
    {0.83137F, 0.60784F, 0.73725F},
    {0.83529F, 0.69804F, 0.80392F},
    {0.86275F, 0.80000F, 0.87059F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
