#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_14 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.26275F, 0.20000F, 0.37255F},
    {0.34510F, 0.27059F, 0.44314F},
    {0.44314F, 0.33725F, 0.50980F},
    {0.54118F, 0.38039F, 0.55686F},
    {0.63137F, 0.39608F, 0.57647F},
    {0.72157F, 0.41176F, 0.58824F},
    {0.80392F, 0.46275F, 0.63137F},
    {0.83529F, 0.54118F, 0.69020F},
    {0.83137F, 0.60392F, 0.73725F},
    {0.83137F, 0.67059F, 0.78039F},
    {0.84706F, 0.74510F, 0.83529F},
    {0.87059F, 0.81961F, 0.88627F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
