#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_18 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.23922F, 0.18431F, 0.35294F},
    {0.30196F, 0.23922F, 0.40784F},
    {0.37255F, 0.29020F, 0.46275F},
    {0.44706F, 0.34118F, 0.51373F},
    {0.52549F, 0.37647F, 0.54902F},
    {0.59608F, 0.39216F, 0.56863F},
    {0.66275F, 0.40000F, 0.58039F},
    {0.72941F, 0.41176F, 0.59216F},
    {0.79608F, 0.45490F, 0.62745F},
    {0.83137F, 0.51373F, 0.67059F},
    {0.83137F, 0.56863F, 0.70980F},
    {0.82745F, 0.61569F, 0.74118F},
    {0.83137F, 0.66667F, 0.78039F},
    {0.83922F, 0.72157F, 0.81569F},
    {0.85490F, 0.78039F, 0.85882F},
    {0.87843F, 0.83922F, 0.89804F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
