#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_20 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.23137F, 0.17647F, 0.34510F},
    {0.29020F, 0.22745F, 0.39608F},
    {0.34902F, 0.27451F, 0.44706F},
    {0.41569F, 0.32157F, 0.49412F},
    {0.48235F, 0.35686F, 0.53333F},
    {0.55294F, 0.38431F, 0.56078F},
    {0.61569F, 0.39608F, 0.57255F},
    {0.67059F, 0.40000F, 0.58039F},
    {0.73333F, 0.41569F, 0.59608F},
    {0.79216F, 0.45098F, 0.62353F},
    {0.82745F, 0.50588F, 0.66667F},
    {0.83529F, 0.55294F, 0.69804F},
    {0.83137F, 0.59608F, 0.72941F},
    {0.82745F, 0.64314F, 0.76078F},
    {0.83529F, 0.68627F, 0.79608F},
    {0.84314F, 0.74118F, 0.83137F},
    {0.85882F, 0.79216F, 0.86667F},
    {0.88235F, 0.84706F, 0.90588F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
