#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_15 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.25490F, 0.19216F, 0.36471F},
    {0.32941F, 0.25882F, 0.43137F},
    {0.41961F, 0.32549F, 0.49804F},
    {0.51373F, 0.37255F, 0.54510F},
    {0.60000F, 0.39608F, 0.57255F},
    {0.67843F, 0.40392F, 0.58431F},
    {0.76863F, 0.43137F, 0.60784F},
    {0.82745F, 0.49804F, 0.65882F},
    {0.83529F, 0.56471F, 0.70588F},
    {0.82745F, 0.62353F, 0.74902F},
    {0.83137F, 0.68627F, 0.79216F},
    {0.85098F, 0.75686F, 0.84314F},
    {0.87451F, 0.82745F, 0.89020F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
