#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ACTON_9 = std::vector<vivid::srgb_t>{
    {0.18039F, 0.12941F, 0.30196F},
    {0.31373F, 0.24314F, 0.41569F},
    {0.46667F, 0.35294F, 0.52549F},
    {0.62353F, 0.39608F, 0.57647F},
    {0.76863F, 0.43137F, 0.60784F},
    {0.83529F, 0.54902F, 0.69412F},
    {0.83137F, 0.65098F, 0.76863F},
    {0.85490F, 0.77255F, 0.85098F},
    {0.90196F, 0.90196F, 0.94118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
