#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AGGRNYL_3 = std::vector<vivid::srgb_t>{
    {0.14118F, 0.33725F, 0.40784F},
    {0.22353F, 0.67059F, 0.49412F},
    {0.92941F, 0.93725F, 0.36471F},
};

} // namespace GOOM::COLOR::COLOR_DATA
