#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AGSUNSET_4 = std::vector<vivid::srgb_t>{
    {0.29412F, 0.16078F, 0.56863F},
    {0.75294F, 0.21176F, 0.61569F},
    {0.98039F, 0.47059F, 0.46275F},
    {0.92941F, 0.85098F, 0.63922F},
};

} // namespace GOOM::COLOR::COLOR_DATA
