#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_12 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.72941F, 0.89412F, 0.68627F},
    {0.61569F, 0.81961F, 0.56471F},
    {0.48235F, 0.74902F, 0.45098F},
    {0.33725F, 0.68627F, 0.36078F},
    {0.14902F, 0.61961F, 0.31765F},
    {0.03137F, 0.54118F, 0.30588F},
    {0.05490F, 0.45882F, 0.28235F},
    {0.09020F, 0.38039F, 0.24314F},
    {0.10196F, 0.29804F, 0.19608F},
    {0.09412F, 0.21961F, 0.14118F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
