#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_10 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.70588F, 0.87843F, 0.65882F},
    {0.55686F, 0.78824F, 0.50980F},
    {0.39216F, 0.70588F, 0.38824F},
    {0.17255F, 0.62745F, 0.32157F},
    {0.02745F, 0.52941F, 0.30196F},
    {0.07059F, 0.43137F, 0.27059F},
    {0.09804F, 0.33333F, 0.21961F},
    {0.09804F, 0.23529F, 0.15294F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
