#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_14 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.74510F, 0.90588F, 0.70196F},
    {0.65098F, 0.84314F, 0.60000F},
    {0.54510F, 0.78039F, 0.50196F},
    {0.43529F, 0.72549F, 0.41569F},
    {0.29804F, 0.67059F, 0.34510F},
    {0.13333F, 0.61176F, 0.31765F},
    {0.03529F, 0.54902F, 0.30980F},
    {0.04314F, 0.47843F, 0.28627F},
    {0.07843F, 0.40784F, 0.25882F},
    {0.09804F, 0.34118F, 0.22353F},
    {0.10196F, 0.27451F, 0.18039F},
    {0.09020F, 0.20784F, 0.13333F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
