#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_18 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.76863F, 0.92157F, 0.72941F},
    {0.69412F, 0.87059F, 0.64706F},
    {0.61961F, 0.82353F, 0.56863F},
    {0.54118F, 0.78039F, 0.49412F},
    {0.45490F, 0.73333F, 0.42745F},
    {0.35686F, 0.69412F, 0.36863F},
    {0.23922F, 0.65098F, 0.32941F},
    {0.11765F, 0.60784F, 0.31765F},
    {0.03922F, 0.55686F, 0.30980F},
    {0.03137F, 0.50196F, 0.29412F},
    {0.05882F, 0.45098F, 0.27843F},
    {0.08235F, 0.39608F, 0.25098F},
    {0.09804F, 0.34510F, 0.22353F},
    {0.10196F, 0.29412F, 0.19216F},
    {0.09804F, 0.24314F, 0.15686F},
    {0.08627F, 0.19216F, 0.11765F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
