#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_16 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.76078F, 0.91765F, 0.71765F},
    {0.67451F, 0.85882F, 0.62745F},
    {0.58824F, 0.80392F, 0.54118F},
    {0.49412F, 0.75686F, 0.45882F},
    {0.39216F, 0.70588F, 0.38824F},
    {0.26667F, 0.65882F, 0.33333F},
    {0.12549F, 0.61176F, 0.31765F},
    {0.03529F, 0.55294F, 0.30980F},
    {0.03529F, 0.49020F, 0.29412F},
    {0.07059F, 0.43137F, 0.27059F},
    {0.09020F, 0.37255F, 0.23922F},
    {0.10196F, 0.31373F, 0.20392F},
    {0.09804F, 0.25490F, 0.16863F},
    {0.09020F, 0.20000F, 0.12549F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
