#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_11 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.71373F, 0.88627F, 0.67059F},
    {0.58824F, 0.80392F, 0.54118F},
    {0.44706F, 0.73333F, 0.42353F},
    {0.26667F, 0.65882F, 0.33333F},
    {0.07059F, 0.58039F, 0.31373F},
    {0.03529F, 0.49020F, 0.29412F},
    {0.08235F, 0.40392F, 0.25490F},
    {0.10196F, 0.31373F, 0.20392F},
    {0.09412F, 0.22745F, 0.14510F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
