#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_15 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.75294F, 0.91373F, 0.71373F},
    {0.66667F, 0.85490F, 0.61569F},
    {0.56863F, 0.79216F, 0.52157F},
    {0.46667F, 0.74118F, 0.43529F},
    {0.35294F, 0.69020F, 0.36471F},
    {0.20392F, 0.63922F, 0.32549F},
    {0.07059F, 0.58039F, 0.31373F},
    {0.02745F, 0.51765F, 0.30196F},
    {0.05882F, 0.45098F, 0.27843F},
    {0.08627F, 0.38824F, 0.25098F},
    {0.09804F, 0.32941F, 0.21569F},
    {0.10196F, 0.26275F, 0.17255F},
    {0.09020F, 0.20392F, 0.12549F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
