#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ALGAE_19 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.97647F, 0.81569F},
    {0.77255F, 0.92549F, 0.73333F},
    {0.70588F, 0.87843F, 0.65882F},
    {0.63529F, 0.83529F, 0.58431F},
    {0.55686F, 0.78824F, 0.50980F},
    {0.47843F, 0.74510F, 0.44706F},
    {0.39216F, 0.70588F, 0.38824F},
    {0.29020F, 0.67059F, 0.34118F},
    {0.17255F, 0.62745F, 0.32157F},
    {0.07059F, 0.58039F, 0.31373F},
    {0.02745F, 0.52941F, 0.30196F},
    {0.04314F, 0.48235F, 0.29020F},
    {0.07059F, 0.43137F, 0.27059F},
    {0.09020F, 0.38431F, 0.24706F},
    {0.09804F, 0.33333F, 0.21961F},
    {0.10196F, 0.28627F, 0.18824F},
    {0.09804F, 0.23529F, 0.15294F},
    {0.08627F, 0.18824F, 0.11765F},
    {0.07059F, 0.14118F, 0.07843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
