#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_7 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.87451F, 0.73725F, 0.69020F},
    {0.81569F, 0.54510F, 0.45098F},
    {0.75294F, 0.34510F, 0.23137F},
    {0.65098F, 0.13333F, 0.14510F},
    {0.45490F, 0.05490F, 0.15686F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
