#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_14 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.90588F, 0.83529F, 0.81569F},
    {0.87843F, 0.74902F, 0.70980F},
    {0.85098F, 0.65882F, 0.59608F},
    {0.82353F, 0.57255F, 0.49020F},
    {0.79608F, 0.48627F, 0.38039F},
    {0.76863F, 0.39216F, 0.27843F},
    {0.73725F, 0.30196F, 0.19216F},
    {0.69020F, 0.20000F, 0.14510F},
    {0.62353F, 0.10588F, 0.14902F},
    {0.53725F, 0.05882F, 0.16078F},
    {0.43529F, 0.05490F, 0.14902F},
    {0.33725F, 0.05490F, 0.11765F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
