#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_9 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.88627F, 0.78039F, 0.74902F},
    {0.84314F, 0.63529F, 0.56863F},
    {0.80000F, 0.49412F, 0.39216F},
    {0.75294F, 0.34510F, 0.23137F},
    {0.68627F, 0.18824F, 0.14118F},
    {0.56471F, 0.06275F, 0.16078F},
    {0.39608F, 0.05882F, 0.14118F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
