#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_16 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.91373F, 0.85098F, 0.83137F},
    {0.88627F, 0.77255F, 0.73725F},
    {0.86275F, 0.69412F, 0.63922F},
    {0.83922F, 0.61961F, 0.54510F},
    {0.81569F, 0.54510F, 0.45098F},
    {0.79216F, 0.46667F, 0.35686F},
    {0.76471F, 0.38824F, 0.27451F},
    {0.73725F, 0.30588F, 0.19608F},
    {0.70196F, 0.21961F, 0.14902F},
    {0.65098F, 0.13333F, 0.14510F},
    {0.58039F, 0.07451F, 0.15686F},
    {0.49804F, 0.05490F, 0.16078F},
    {0.40784F, 0.05882F, 0.14510F},
    {0.32157F, 0.05098F, 0.10980F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
