#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_11 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.89804F, 0.80784F, 0.78431F},
    {0.86275F, 0.69412F, 0.63922F},
    {0.82745F, 0.58431F, 0.49804F},
    {0.79216F, 0.46667F, 0.35686F},
    {0.75294F, 0.34510F, 0.23137F},
    {0.70196F, 0.21961F, 0.14902F},
    {0.61961F, 0.10196F, 0.14902F},
    {0.49804F, 0.05490F, 0.16078F},
    {0.36078F, 0.05490F, 0.12941F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
