#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_12 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.90196F, 0.82353F, 0.80000F},
    {0.86667F, 0.71765F, 0.67059F},
    {0.83529F, 0.61176F, 0.53333F},
    {0.80392F, 0.50588F, 0.40784F},
    {0.77255F, 0.40392F, 0.28627F},
    {0.73333F, 0.29020F, 0.18824F},
    {0.67843F, 0.17255F, 0.14118F},
    {0.59216F, 0.07843F, 0.15686F},
    {0.47059F, 0.05490F, 0.15686F},
    {0.35294F, 0.05490F, 0.12157F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
