#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_8 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.88235F, 0.76471F, 0.72549F},
    {0.83137F, 0.59608F, 0.51765F},
    {0.78039F, 0.43529F, 0.32157F},
    {0.71765F, 0.25490F, 0.16471F},
    {0.60392F, 0.08627F, 0.15294F},
    {0.41961F, 0.05882F, 0.14510F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
