#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_20 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.91765F, 0.86667F, 0.85490F},
    {0.89412F, 0.80392F, 0.77647F},
    {0.87451F, 0.74510F, 0.70196F},
    {0.85882F, 0.68235F, 0.62353F},
    {0.83922F, 0.62353F, 0.54902F},
    {0.81961F, 0.56078F, 0.47059F},
    {0.80392F, 0.50196F, 0.40000F},
    {0.78431F, 0.44314F, 0.33333F},
    {0.76471F, 0.38039F, 0.26275F},
    {0.74118F, 0.31765F, 0.20392F},
    {0.71373F, 0.24706F, 0.16078F},
    {0.68235F, 0.17647F, 0.14118F},
    {0.63529F, 0.11765F, 0.14510F},
    {0.57647F, 0.07059F, 0.15686F},
    {0.51373F, 0.05490F, 0.16078F},
    {0.43922F, 0.05490F, 0.15294F},
    {0.37255F, 0.05490F, 0.12941F},
    {0.30196F, 0.04706F, 0.10196F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
