#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AMP_10 = std::vector<vivid::srgb_t>{
    {0.94510F, 0.92941F, 0.92549F},
    {0.89412F, 0.80000F, 0.77255F},
    {0.85098F, 0.66667F, 0.60784F},
    {0.81569F, 0.54510F, 0.45098F},
    {0.77647F, 0.41569F, 0.30196F},
    {0.72549F, 0.27451F, 0.17647F},
    {0.65098F, 0.13333F, 0.14510F},
    {0.52941F, 0.05490F, 0.16078F},
    {0.37647F, 0.05490F, 0.13333F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
