#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ANTIQUE_8 = std::vector<vivid::srgb_t>{
    {0.52157F, 0.36078F, 0.45882F},
    {0.85098F, 0.68627F, 0.41961F},
    {0.68627F, 0.39216F, 0.34510F},
    {0.45098F, 0.43529F, 0.29804F},
    {0.32157F, 0.41569F, 0.51373F},
    {0.38431F, 0.32549F, 0.46667F},
    {0.40784F, 0.52157F, 0.36078F},
    {0.61176F, 0.61176F, 0.36863F},
};

} // namespace GOOM::COLOR::COLOR_DATA
