#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto AQUATIC3_5 = std::vector<vivid::srgb_t>{
    {0.83922F, 0.63137F, 0.25882F},
    {0.76078F, 0.50196F, 0.44706F},
    {0.78431F, 0.71765F, 0.63137F},
    {0.74118F, 0.26667F, 0.17647F},
    {0.39216F, 0.32941F, 0.23529F},
};

} // namespace GOOM::COLOR::COLOR_DATA
