#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BALANCE_16 = std::vector<vivid::srgb_t>{
    {0.09412F, 0.10980F, 0.26275F},
    {0.15294F, 0.20000F, 0.47843F},
    {0.12941F, 0.29804F, 0.71373F},
    {0.08627F, 0.43922F, 0.73725F},
    {0.26275F, 0.56078F, 0.72941F},
    {0.45882F, 0.66667F, 0.74510F},
    {0.66667F, 0.76078F, 0.79608F},
    {0.85882F, 0.87059F, 0.87843F},
    {0.91373F, 0.85098F, 0.83529F},
    {0.86275F, 0.69804F, 0.64314F},
    {0.81569F, 0.54510F, 0.45098F},
    {0.76471F, 0.38824F, 0.27451F},
    {0.70196F, 0.21961F, 0.14902F},
    {0.58039F, 0.07451F, 0.15686F},
    {0.40784F, 0.05882F, 0.14510F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
