#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BALANCE_8 = std::vector<vivid::srgb_t>{
    {0.09412F, 0.10980F, 0.26275F},
    {0.10980F, 0.31373F, 0.72941F},
    {0.31765F, 0.59216F, 0.72941F},
    {0.74902F, 0.80392F, 0.82745F},
    {0.88235F, 0.76078F, 0.72157F},
    {0.78039F, 0.43529F, 0.32549F},
    {0.60000F, 0.08627F, 0.15294F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
