#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BALANCE_12 = std::vector<vivid::srgb_t>{
    {0.09412F, 0.10980F, 0.26275F},
    {0.16078F, 0.23137F, 0.56078F},
    {0.04314F, 0.40000F, 0.74118F},
    {0.28235F, 0.57255F, 0.72941F},
    {0.55686F, 0.70980F, 0.76471F},
    {0.82745F, 0.85098F, 0.86275F},
    {0.90196F, 0.82353F, 0.80392F},
    {0.83922F, 0.61569F, 0.54118F},
    {0.77255F, 0.40784F, 0.29412F},
    {0.67451F, 0.16863F, 0.14118F},
    {0.47059F, 0.05490F, 0.15686F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
