#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BALANCE_20 = std::vector<vivid::srgb_t>{
    {0.09412F, 0.10980F, 0.26275F},
    {0.14118F, 0.18039F, 0.42353F},
    {0.16078F, 0.25098F, 0.61961F},
    {0.06275F, 0.34902F, 0.74510F},
    {0.11765F, 0.46275F, 0.73333F},
    {0.25098F, 0.55294F, 0.72941F},
    {0.40784F, 0.64314F, 0.73725F},
    {0.56863F, 0.71765F, 0.76471F},
    {0.72549F, 0.79216F, 0.81569F},
    {0.88235F, 0.88235F, 0.89020F},
    {0.92157F, 0.87059F, 0.85882F},
    {0.87451F, 0.74118F, 0.69804F},
    {0.83922F, 0.62353F, 0.55294F},
    {0.80392F, 0.50980F, 0.40784F},
    {0.76471F, 0.38039F, 0.26275F},
    {0.71765F, 0.25098F, 0.16078F},
    {0.63137F, 0.11373F, 0.14510F},
    {0.51373F, 0.05490F, 0.16078F},
    {0.36863F, 0.05490F, 0.12941F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
