#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BALANCE_14 = std::vector<vivid::srgb_t>{
    {0.09412F, 0.10980F, 0.26275F},
    {0.15686F, 0.21569F, 0.51765F},
    {0.07451F, 0.34118F, 0.74510F},
    {0.16863F, 0.49804F, 0.72941F},
    {0.37255F, 0.62353F, 0.73333F},
    {0.61961F, 0.73725F, 0.78039F},
    {0.84706F, 0.86275F, 0.87059F},
    {0.90980F, 0.84314F, 0.82353F},
    {0.85098F, 0.66275F, 0.59608F},
    {0.79608F, 0.48235F, 0.37647F},
    {0.73725F, 0.30196F, 0.19608F},
    {0.62353F, 0.10588F, 0.14902F},
    {0.43922F, 0.05490F, 0.15294F},
    {0.23529F, 0.03529F, 0.07059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
