#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BAMAKO_18 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.25098F, 0.29804F},
    {0.04314F, 0.27451F, 0.27843F},
    {0.07843F, 0.29804F, 0.25490F},
    {0.11765F, 0.32157F, 0.23529F},
    {0.15686F, 0.34902F, 0.20784F},
    {0.20000F, 0.37647F, 0.18431F},
    {0.24314F, 0.40392F, 0.15686F},
    {0.29412F, 0.43529F, 0.12941F},
    {0.34902F, 0.47059F, 0.09804F},
    {0.41176F, 0.50980F, 0.06275F},
    {0.48627F, 0.54510F, 0.02353F},
    {0.56078F, 0.56471F, 0.01176F},
    {0.65098F, 0.60000F, 0.07451F},
    {0.75294F, 0.66667F, 0.17255F},
    {0.83529F, 0.73725F, 0.28627F},
    {0.89804F, 0.79608F, 0.39608F},
    {0.94902F, 0.84706F, 0.49804F},
    {1.00000F, 0.89804F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
