#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BAMAKO_12 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.25098F, 0.29804F},
    {0.06275F, 0.28627F, 0.26667F},
    {0.11765F, 0.32157F, 0.23137F},
    {0.18431F, 0.36471F, 0.19216F},
    {0.25490F, 0.41176F, 0.15294F},
    {0.33333F, 0.46275F, 0.10588F},
    {0.43137F, 0.52157F, 0.05098F},
    {0.54510F, 0.56078F, 0.01176F},
    {0.68627F, 0.61961F, 0.10588F},
    {0.83137F, 0.73333F, 0.27843F},
    {0.92157F, 0.81961F, 0.44314F},
    {1.00000F, 0.89804F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
