#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BAMAKO_17 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.25098F, 0.29804F},
    {0.04314F, 0.27451F, 0.27843F},
    {0.08235F, 0.29804F, 0.25490F},
    {0.12549F, 0.32549F, 0.22745F},
    {0.16863F, 0.35294F, 0.20392F},
    {0.21176F, 0.38431F, 0.17647F},
    {0.26275F, 0.41569F, 0.14510F},
    {0.31765F, 0.45098F, 0.11373F},
    {0.38039F, 0.49412F, 0.07843F},
    {0.45098F, 0.53333F, 0.03922F},
    {0.52941F, 0.55686F, 0.01176F},
    {0.61961F, 0.58431F, 0.04706F},
    {0.72549F, 0.64706F, 0.14510F},
    {0.81961F, 0.72549F, 0.26275F},
    {0.89020F, 0.78824F, 0.38039F},
    {0.94510F, 0.84706F, 0.49020F},
    {1.00000F, 0.89804F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
