#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BAMAKO_20 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.25098F, 0.29804F},
    {0.03529F, 0.27059F, 0.28235F},
    {0.07059F, 0.29020F, 0.26275F},
    {0.10196F, 0.31373F, 0.24314F},
    {0.14118F, 0.33725F, 0.21961F},
    {0.17647F, 0.36078F, 0.19608F},
    {0.21569F, 0.38824F, 0.17255F},
    {0.25490F, 0.41176F, 0.14902F},
    {0.29804F, 0.44314F, 0.12549F},
    {0.35294F, 0.47451F, 0.09412F},
    {0.40784F, 0.50980F, 0.06275F},
    {0.47451F, 0.54118F, 0.02745F},
    {0.54118F, 0.56078F, 0.01176F},
    {0.61176F, 0.58039F, 0.04314F},
    {0.70588F, 0.63137F, 0.12549F},
    {0.78824F, 0.69804F, 0.21961F},
    {0.85882F, 0.75686F, 0.32157F},
    {0.90588F, 0.80784F, 0.41569F},
    {0.95686F, 0.85490F, 0.51373F},
    {1.00000F, 0.89804F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
