#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BAMAKO_7 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.25098F, 0.29804F},
    {0.10980F, 0.31765F, 0.23922F},
    {0.22745F, 0.39608F, 0.16471F},
    {0.38039F, 0.49412F, 0.07843F},
    {0.58824F, 0.57255F, 0.02353F},
    {0.84706F, 0.74510F, 0.30196F},
    {1.00000F, 0.89804F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
