#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BATLOW_18 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.09804F, 0.34902F},
    {0.03529F, 0.16078F, 0.36078F},
    {0.05882F, 0.21961F, 0.37255F},
    {0.08235F, 0.28235F, 0.38039F},
    {0.12157F, 0.34510F, 0.38039F},
    {0.18824F, 0.40000F, 0.35686F},
    {0.27059F, 0.43529F, 0.31765F},
    {0.36078F, 0.46667F, 0.27059F},
    {0.45098F, 0.49412F, 0.21961F},
    {0.55294F, 0.52157F, 0.18431F},
    {0.67451F, 0.54902F, 0.18824F},
    {0.79608F, 0.57255F, 0.25098F},
    {0.90196F, 0.59608F, 0.35294F},
    {0.96863F, 0.63137F, 0.47843F},
    {0.99216F, 0.67059F, 0.60392F},
    {0.99216F, 0.71373F, 0.72549F},
    {0.98824F, 0.75686F, 0.85098F},
    {0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
