#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BATLOW_10 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.09804F, 0.34902F},
    {0.05490F, 0.21176F, 0.36863F},
    {0.11373F, 0.33333F, 0.38039F},
    {0.24314F, 0.42353F, 0.33333F},
    {0.40784F, 0.48235F, 0.24314F},
    {0.60784F, 0.53333F, 0.18039F},
    {0.83529F, 0.58039F, 0.28235F},
    {0.97647F, 0.63922F, 0.50196F},
    {0.99216F, 0.71765F, 0.74118F},
    {0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
