#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BATLOW_15 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.09804F, 0.34902F},
    {0.03922F, 0.17255F, 0.36078F},
    {0.06667F, 0.24706F, 0.37647F},
    {0.10588F, 0.32549F, 0.38039F},
    {0.18039F, 0.39216F, 0.36078F},
    {0.27843F, 0.43922F, 0.31373F},
    {0.38431F, 0.47451F, 0.25490F},
    {0.50588F, 0.50980F, 0.20000F},
    {0.63922F, 0.54118F, 0.18039F},
    {0.78824F, 0.57255F, 0.24706F},
    {0.91373F, 0.60000F, 0.36863F},
    {0.98039F, 0.64314F, 0.52157F},
    {0.99216F, 0.69412F, 0.67843F},
    {0.99216F, 0.74510F, 0.82745F},
    {0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
