#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BATLOW_5 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.09804F, 0.34902F},
    {0.13725F, 0.36078F, 0.37647F},
    {0.50588F, 0.50980F, 0.20000F},
    {0.95686F, 0.61961F, 0.44314F},
    {0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
