#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BATLOW_14 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.09804F, 0.34902F},
    {0.04314F, 0.18039F, 0.36471F},
    {0.07059F, 0.25882F, 0.37647F},
    {0.11765F, 0.34118F, 0.38039F},
    {0.20392F, 0.40784F, 0.35294F},
    {0.31765F, 0.45490F, 0.29412F},
    {0.43922F, 0.49020F, 0.22745F},
    {0.56863F, 0.52549F, 0.18039F},
    {0.73333F, 0.56078F, 0.21176F},
    {0.88235F, 0.59216F, 0.33333F},
    {0.97255F, 0.63529F, 0.48627F},
    {0.99216F, 0.68627F, 0.65098F},
    {0.99216F, 0.74118F, 0.80784F},
    {0.98039F, 0.80000F, 0.98039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
