#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BERLIN_20 = std::vector<vivid::srgb_t>{
    {0.61961F, 0.69020F, 1.00000F},
    {0.50196F, 0.67451F, 0.94510F},
    {0.36471F, 0.64706F, 0.86667F},
    {0.25490F, 0.58039F, 0.75686F},
    {0.18824F, 0.47843F, 0.61961F},
    {0.14902F, 0.38431F, 0.49804F},
    {0.10980F, 0.28627F, 0.37255F},
    {0.08235F, 0.20000F, 0.25882F},
    {0.06667F, 0.12549F, 0.15686F},
    {0.07451F, 0.06667F, 0.07059F},
    {0.12549F, 0.04314F, 0.01569F},
    {0.18824F, 0.05882F, 0.00000F},
    {0.25882F, 0.07451F, 0.00392F},
    {0.34118F, 0.10588F, 0.02353F},
    {0.45882F, 0.17647F, 0.09020F},
    {0.56471F, 0.26667F, 0.18824F},
    {0.67451F, 0.36863F, 0.30980F},
    {0.77647F, 0.46667F, 0.42353F},
    {0.89020F, 0.57647F, 0.55686F},
    {1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
