#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BERLIN_4 = std::vector<vivid::srgb_t>{
    {0.61961F, 0.69020F, 1.00000F},
    {0.10196F, 0.25882F, 0.33725F},
    {0.31373F, 0.09412F, 0.01176F},
    {1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
