#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BERLIN_17 = std::vector<vivid::srgb_t>{
    {0.61961F, 0.69020F, 1.00000F},
    {0.47451F, 0.67059F, 0.92941F},
    {0.31765F, 0.62353F, 0.82745F},
    {0.21176F, 0.52157F, 0.67843F},
    {0.15686F, 0.40784F, 0.52549F},
    {0.11373F, 0.29412F, 0.38039F},
    {0.07843F, 0.18824F, 0.24314F},
    {0.06667F, 0.10196F, 0.12549F},
    {0.09804F, 0.04706F, 0.03529F},
    {0.16471F, 0.05490F, 0.00392F},
    {0.24706F, 0.07059F, 0.00392F},
    {0.34902F, 0.10980F, 0.02745F},
    {0.48235F, 0.19608F, 0.10980F},
    {0.61176F, 0.30980F, 0.23922F},
    {0.73725F, 0.42745F, 0.38039F},
    {0.86667F, 0.55294F, 0.52549F},
    {1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
