#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BERLIN_15 = std::vector<vivid::srgb_t>{
    {0.61961F, 0.69020F, 1.00000F},
    {0.45490F, 0.66667F, 0.92157F},
    {0.28235F, 0.60392F, 0.79216F},
    {0.18431F, 0.47059F, 0.61176F},
    {0.13333F, 0.34118F, 0.44314F},
    {0.08627F, 0.21961F, 0.28627F},
    {0.06275F, 0.11373F, 0.14510F},
    {0.09804F, 0.04706F, 0.03529F},
    {0.17647F, 0.05490F, 0.00000F},
    {0.27843F, 0.07843F, 0.00392F},
    {0.40784F, 0.14118F, 0.05882F},
    {0.55686F, 0.25882F, 0.18039F},
    {0.70588F, 0.40000F, 0.34510F},
    {0.85098F, 0.53725F, 0.50980F},
    {1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
