#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BERLIN_14 = std::vector<vivid::srgb_t>{
    {0.61961F, 0.69020F, 1.00000F},
    {0.43529F, 0.66275F, 0.90980F},
    {0.26275F, 0.58431F, 0.76471F},
    {0.17255F, 0.44314F, 0.57255F},
    {0.11765F, 0.30588F, 0.39608F},
    {0.07451F, 0.17647F, 0.22745F},
    {0.06667F, 0.07451F, 0.09020F},
    {0.13725F, 0.04706F, 0.00784F},
    {0.23529F, 0.06667F, 0.00392F},
    {0.36471F, 0.11765F, 0.03529F},
    {0.52549F, 0.23137F, 0.14902F},
    {0.68235F, 0.37647F, 0.31765F},
    {0.83529F, 0.52157F, 0.49020F},
    {1.00000F, 0.67843F, 0.67843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
