#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BILBAO_19 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.92941F, 0.92941F, 0.92549F},
    {0.86275F, 0.85882F, 0.85098F},
    {0.80784F, 0.80000F, 0.76863F},
    {0.77255F, 0.75294F, 0.68627F},
    {0.74902F, 0.72157F, 0.61569F},
    {0.72549F, 0.68627F, 0.54510F},
    {0.70196F, 0.63529F, 0.47451F},
    {0.68235F, 0.58039F, 0.42745F},
    {0.66667F, 0.52549F, 0.39608F},
    {0.65098F, 0.47843F, 0.37647F},
    {0.63922F, 0.43137F, 0.35686F},
    {0.61961F, 0.38039F, 0.33333F},
    {0.59608F, 0.32549F, 0.30196F},
    {0.55294F, 0.26275F, 0.25490F},
    {0.49804F, 0.20000F, 0.19608F},
    {0.43137F, 0.13333F, 0.13333F},
    {0.36471F, 0.07059F, 0.07843F},
    {0.30196F, 0.00000F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
