#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BILBAO_20 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.93333F, 0.93333F, 0.93333F},
    {0.86667F, 0.86275F, 0.85490F},
    {0.81569F, 0.80784F, 0.78039F},
    {0.77647F, 0.76078F, 0.70196F},
    {0.75294F, 0.72941F, 0.63529F},
    {0.73333F, 0.69412F, 0.56471F},
    {0.70980F, 0.65490F, 0.49804F},
    {0.69020F, 0.60392F, 0.44314F},
    {0.67451F, 0.55294F, 0.40784F},
    {0.65882F, 0.50588F, 0.38824F},
    {0.64706F, 0.45882F, 0.36863F},
    {0.63137F, 0.41176F, 0.34902F},
    {0.61569F, 0.36471F, 0.32549F},
    {0.58824F, 0.30980F, 0.29020F},
    {0.54510F, 0.25098F, 0.24314F},
    {0.48627F, 0.18824F, 0.18431F},
    {0.42745F, 0.12941F, 0.12941F},
    {0.36078F, 0.06667F, 0.07451F},
    {0.30196F, 0.00000F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
