#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEDARKRED18_17 = std::vector<vivid::srgb_t>{
    {0.14118F, 0.00000F, 0.84706F},
    {0.09412F, 0.10980F, 0.96863F},
    {0.15686F, 0.34118F, 1.00000F},
    {0.23922F, 0.52941F, 1.00000F},
    {0.33725F, 0.69020F, 1.00000F},
    {0.45882F, 0.82745F, 1.00000F},
    {0.60000F, 0.91765F, 1.00000F},
    {0.73725F, 0.97647F, 1.00000F},
    {0.91765F, 1.00000F, 1.00000F},
    {1.00000F, 0.94510F, 0.73725F},
    {1.00000F, 0.83922F, 0.60000F},
    {1.00000F, 0.67451F, 0.45882F},
    {1.00000F, 0.47059F, 0.33725F},
    {1.00000F, 0.23922F, 0.23922F},
    {0.96863F, 0.15294F, 0.20784F},
    {0.84706F, 0.08235F, 0.18431F},
    {0.64706F, 0.00000F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
