#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEDARKORANGE12_10 = std::vector<vivid::srgb_t>{
    {0.11765F, 0.55686F, 0.60000F},
    {0.31765F, 0.76471F, 0.80000F},
    {0.60000F, 0.97647F, 1.00000F},
    {0.80000F, 0.99608F, 1.00000F},
    {0.89804F, 1.00000F, 1.00000F},
    {1.00000F, 0.89804F, 0.80000F},
    {1.00000F, 0.79216F, 0.60000F},
    {1.00000F, 0.55686F, 0.19608F},
    {0.80000F, 0.34510F, 0.00000F},
    {0.60000F, 0.24706F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
