#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUES_3 = std::vector<vivid::srgb_t>{
    {0.87059F, 0.92157F, 0.96863F},
    {0.61961F, 0.79216F, 0.88235F},
    {0.19216F, 0.50980F, 0.74118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
