#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUES10_9 = std::vector<vivid::srgb_t>{
    {0.89804F, 1.00000F, 1.00000F},
    {0.80000F, 0.98039F, 1.00000F},
    {0.69804F, 0.94902F, 1.00000F},
    {0.60000F, 0.89804F, 1.00000F},
    {0.49804F, 0.83137F, 1.00000F},
    {0.29804F, 0.64706F, 1.00000F},
    {0.19608F, 0.53333F, 1.00000F},
    {0.09804F, 0.39608F, 1.00000F},
    {0.00000F, 0.24706F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
