#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEDARKORANGE18_7 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.40000F, 0.40000F},
    {0.00000F, 1.00000F, 1.00000F},
    {0.60000F, 1.00000F, 1.00000F},
    {0.79608F, 1.00000F, 1.00000F},
    {1.00000F, 0.79216F, 0.60000F},
    {1.00000F, 0.43137F, 0.00000F},
    {0.40000F, 0.15294F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
