#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEORANGE10_4 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.32941F, 1.00000F},
    {0.60000F, 0.92941F, 1.00000F},
    {1.00000F, 0.93333F, 0.60000F},
    {1.00000F, 0.33333F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
