#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEDARKRED12_12 = std::vector<vivid::srgb_t>{
    {0.16078F, 0.03922F, 0.84706F},
    {0.14902F, 0.30196F, 1.00000F},
    {0.24706F, 0.62745F, 1.00000F},
    {0.44706F, 0.85098F, 1.00000F},
    {0.66667F, 0.96863F, 1.00000F},
    {0.87843F, 1.00000F, 1.00000F},
    {1.00000F, 1.00000F, 0.74902F},
    {1.00000F, 0.87843F, 0.60000F},
    {1.00000F, 0.67843F, 0.44706F},
    {0.96863F, 0.42745F, 0.36863F},
    {0.84706F, 0.14902F, 0.19608F},
    {0.64706F, 0.00000F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
