#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEGRAY_6 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.60000F, 0.80000F},
    {0.40000F, 0.89804F, 1.00000F},
    {0.80000F, 1.00000F, 1.00000F},
    {0.89804F, 0.89804F, 0.89804F},
    {0.40000F, 0.40000F, 0.40000F},
    {0.20000F, 0.20000F, 0.20000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
