#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUES7_7 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.80000F, 0.99216F, 1.00000F},
    {0.60000F, 0.97255F, 1.00000F},
    {0.40000F, 0.93725F, 1.00000F},
    {0.20000F, 0.89020F, 1.00000F},
    {0.00000F, 0.66667F, 0.80000F},
    {0.00000F, 0.47843F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
