#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUEORANGERED_11 = std::vector<vivid::srgb_t>{
    {0.02745F, 0.35294F, 1.00000F},
    {0.19608F, 0.46275F, 1.00000F},
    {0.54902F, 0.69804F, 1.00000F},
    {0.74902F, 0.83137F, 1.00000F},
    {0.89804F, 0.93333F, 1.00000F},
    {0.96863F, 0.97647F, 1.00000F},
    {1.00000F, 1.00000F, 0.60000F},
    {1.00000F, 1.00000F, 0.00000F},
    {1.00000F, 0.80000F, 0.00000F},
    {1.00000F, 0.40000F, 0.00000F},
    {1.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
