#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUERED_12 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.41176F, 0.69020F},
    {0.70980F, 0.78431F, 0.88627F},
    {0.94118F, 0.15294F, 0.12549F},
    {1.00000F, 0.71373F, 0.69020F},
    {0.67451F, 0.38039F, 0.23529F},
    {0.91373F, 0.76471F, 0.60784F},
    {0.41961F, 0.63922F, 0.83922F},
    {0.70980F, 0.87451F, 0.99216F},
    {0.67451F, 0.52941F, 0.38824F},
    {0.86667F, 0.78824F, 0.70588F},
    {0.74118F, 0.03922F, 0.21176F},
    {0.95686F, 0.45098F, 0.47843F},
};

} // namespace GOOM::COLOR::COLOR_DATA
