#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUERED_6 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.41176F, 0.69020F},
    {0.94118F, 0.15294F, 0.12549F},
    {0.67451F, 0.38039F, 0.23529F},
    {0.41961F, 0.63922F, 0.83922F},
    {0.91765F, 0.41961F, 0.45098F},
    {0.91373F, 0.76471F, 0.60784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
