#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUES_7 = std::vector<vivid::srgb_t>{
    {0.93725F, 0.95294F, 1.00000F},
    {0.77647F, 0.85882F, 0.93725F},
    {0.61961F, 0.79216F, 0.88235F},
    {0.41961F, 0.68235F, 0.83922F},
    {0.25882F, 0.57255F, 0.77647F},
    {0.12941F, 0.44314F, 0.70980F},
    {0.03137F, 0.27059F, 0.58039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
