#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUGRN_6 = std::vector<vivid::srgb_t>{
    {0.76863F, 0.90196F, 0.76471F},
    {0.58824F, 0.82353F, 0.64314F},
    {0.42745F, 0.73725F, 0.56471F},
    {0.21176F, 0.52941F, 0.47843F},
    {0.14902F, 0.41961F, 0.43137F},
    {0.11373F, 0.30980F, 0.37647F},
};

} // namespace GOOM::COLOR::COLOR_DATA
