#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BLUYL_2 = std::vector<vivid::srgb_t>{
    {0.96863F, 0.99608F, 0.68235F},
    {0.01569F, 0.32157F, 0.45882F},
};

} // namespace GOOM::COLOR::COLOR_DATA
