#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BOLD_10 = std::vector<vivid::srgb_t>{
    {0.49804F, 0.23529F, 0.55294F},
    {0.06667F, 0.64706F, 0.47451F},
    {0.22353F, 0.41176F, 0.67451F},
    {0.94902F, 0.71765F, 0.00392F},
    {0.90588F, 0.24706F, 0.45490F},
    {0.50196F, 0.72941F, 0.35294F},
    {0.90196F, 0.51373F, 0.06275F},
    {0.00000F, 0.52549F, 0.58431F},
    {0.81176F, 0.10980F, 0.56471F},
    {0.97647F, 0.48235F, 0.44706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
