#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BRBG_7 = std::vector<vivid::srgb_t>{
    {0.54902F, 0.31765F, 0.03922F},
    {0.84706F, 0.70196F, 0.39608F},
    {0.96471F, 0.90980F, 0.76471F},
    {0.96078F, 0.96078F, 0.96078F},
    {0.78039F, 0.91765F, 0.89804F},
    {0.35294F, 0.70588F, 0.67451F},
    {0.00392F, 0.40000F, 0.36863F},
};

} // namespace GOOM::COLOR::COLOR_DATA
