#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BRBG_10 = std::vector<vivid::srgb_t>{
    {0.32941F, 0.18824F, 0.01961F},
    {0.54902F, 0.31765F, 0.03922F},
    {0.74902F, 0.50588F, 0.17647F},
    {0.87451F, 0.76078F, 0.49020F},
    {0.96471F, 0.90980F, 0.76471F},
    {0.78039F, 0.91765F, 0.89804F},
    {0.50196F, 0.80392F, 0.75686F},
    {0.20784F, 0.59216F, 0.56078F},
    {0.00392F, 0.40000F, 0.36863F},
    {0.00000F, 0.23529F, 0.18824F},
};

} // namespace GOOM::COLOR::COLOR_DATA
