#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROC_18 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.18824F, 0.38824F},
    {0.15686F, 0.27843F, 0.47843F},
    {0.20392F, 0.38039F, 0.56863F},
    {0.32157F, 0.48235F, 0.64314F},
    {0.45490F, 0.58431F, 0.71373F},
    {0.59216F, 0.69020F, 0.78431F},
    {0.72941F, 0.79608F, 0.85882F},
    {0.87059F, 0.89804F, 0.92549F},
    {0.92941F, 0.93333F, 0.88235F},
    {0.87451F, 0.87451F, 0.74902F},
    {0.80000F, 0.80000F, 0.60784F},
    {0.69804F, 0.69804F, 0.46667F},
    {0.57647F, 0.57647F, 0.35686F},
    {0.45882F, 0.45882F, 0.25882F},
    {0.34902F, 0.34902F, 0.16471F},
    {0.24314F, 0.24314F, 0.08235F},
    {0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
