#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROC_17 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.19216F, 0.39216F},
    {0.16078F, 0.29412F, 0.49020F},
    {0.22353F, 0.40000F, 0.58431F},
    {0.35686F, 0.50980F, 0.66275F},
    {0.49804F, 0.61961F, 0.73725F},
    {0.64706F, 0.73333F, 0.81569F},
    {0.79608F, 0.84706F, 0.89412F},
    {0.92157F, 0.93333F, 0.92549F},
    {0.90588F, 0.90588F, 0.81176F},
    {0.83137F, 0.83137F, 0.66667F},
    {0.73725F, 0.73725F, 0.51373F},
    {0.60784F, 0.60784F, 0.38431F},
    {0.48235F, 0.48235F, 0.27843F},
    {0.36471F, 0.36471F, 0.17647F},
    {0.25098F, 0.25098F, 0.08627F},
    {0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
