#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROC_19 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.18039F, 0.38039F},
    {0.15686F, 0.26667F, 0.46667F},
    {0.18824F, 0.36078F, 0.54902F},
    {0.29412F, 0.46275F, 0.62745F},
    {0.41961F, 0.55686F, 0.69412F},
    {0.54510F, 0.65490F, 0.76078F},
    {0.67451F, 0.75294F, 0.82745F},
    {0.80784F, 0.85098F, 0.89804F},
    {0.92157F, 0.93333F, 0.92549F},
    {0.90980F, 0.90980F, 0.82353F},
    {0.84706F, 0.84706F, 0.69412F},
    {0.77255F, 0.77255F, 0.56078F},
    {0.66667F, 0.66667F, 0.43529F},
    {0.55294F, 0.55294F, 0.33725F},
    {0.44706F, 0.44706F, 0.24706F},
    {0.33333F, 0.33333F, 0.15294F},
    {0.23529F, 0.23922F, 0.07843F},
    {0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
