#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROC_5 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.35686F, 0.50980F, 0.66275F},
    {0.92157F, 0.93333F, 0.92549F},
    {0.60784F, 0.60784F, 0.38431F},
    {0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
