#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROC_14 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16078F, 0.21961F, 0.41569F},
    {0.17647F, 0.34118F, 0.53333F},
    {0.31373F, 0.47451F, 0.63922F},
    {0.48235F, 0.60784F, 0.72941F},
    {0.66667F, 0.74510F, 0.82353F},
    {0.85098F, 0.88627F, 0.91765F},
    {0.92549F, 0.92941F, 0.86667F},
    {0.84314F, 0.84314F, 0.68235F},
    {0.72157F, 0.72157F, 0.49412F},
    {0.56863F, 0.56863F, 0.34902F},
    {0.41569F, 0.41569F, 0.21961F},
    {0.27843F, 0.27843F, 0.10980F},
    {0.14902F, 0.14902F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
