#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROWNBLUE10_6 = std::vector<vivid::srgb_t>{
    {0.40000F, 0.18431F, 0.00000F},
    {0.80000F, 0.60784F, 0.47843F},
    {0.94902F, 0.85490F, 0.80392F},
    {0.80000F, 0.99216F, 1.00000F},
    {0.39608F, 0.93725F, 1.00000F},
    {0.00000F, 0.66275F, 0.80000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
