#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROWNBLUE12_8 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.09804F, 0.00000F},
    {0.20784F, 0.37647F, 0.20784F},
    {0.01569F, 0.60784F, 0.47843F},
    {0.16471F, 0.85490F, 0.80392F},
    {0.01569F, 0.99216F, 1.00000F},
    {0.00392F, 0.93725F, 1.00000F},
    {0.19608F, 0.89020F, 1.00000F},
    {0.00000F, 0.47843F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
