#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROWNBLUE12_6 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.09804F, 0.00000F},
    {0.20784F, 0.37647F, 0.20784F},
    {0.06275F, 0.68627F, 0.59216F},
    {0.20784F, 0.97255F, 1.00000F},
    {0.19608F, 0.89020F, 1.00000F},
    {0.00000F, 0.47843F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
