#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BROWNBLUE10_8 = std::vector<vivid::srgb_t>{
    {0.40000F, 0.18431F, 0.00000F},
    {0.60000F, 0.37647F, 0.20784F},
    {0.84706F, 0.68627F, 0.59216F},
    {0.94902F, 0.85490F, 0.80392F},
    {0.80000F, 0.99216F, 1.00000F},
    {0.60000F, 0.97255F, 1.00000F},
    {0.19608F, 0.89020F, 1.00000F},
    {0.00000F, 0.66275F, 0.80000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
