#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUDA_19 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.00392F, 0.70196F},
    {0.70196F, 0.10196F, 0.65490F},
    {0.70196F, 0.16863F, 0.61961F},
    {0.70980F, 0.22353F, 0.59608F},
    {0.72549F, 0.28235F, 0.57255F},
    {0.74510F, 0.33333F, 0.55686F},
    {0.76078F, 0.38039F, 0.54118F},
    {0.77647F, 0.42745F, 0.52549F},
    {0.79216F, 0.47451F, 0.50980F},
    {0.80392F, 0.52157F, 0.49412F},
    {0.81961F, 0.56863F, 0.48235F},
    {0.83137F, 0.61961F, 0.47059F},
    {0.84314F, 0.66667F, 0.45882F},
    {0.85490F, 0.71373F, 0.44706F},
    {0.86667F, 0.76471F, 0.43529F},
    {0.87843F, 0.81569F, 0.41961F},
    {0.89804F, 0.87451F, 0.40784F},
    {0.93725F, 0.93333F, 0.40000F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
