#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUDA_14 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.00392F, 0.70196F},
    {0.70196F, 0.12941F, 0.63922F},
    {0.70588F, 0.21176F, 0.60000F},
    {0.72941F, 0.29020F, 0.57255F},
    {0.75294F, 0.35686F, 0.54902F},
    {0.77647F, 0.42353F, 0.52549F},
    {0.79608F, 0.49020F, 0.50588F},
    {0.81176F, 0.55294F, 0.48627F},
    {0.83137F, 0.61961F, 0.47059F},
    {0.84706F, 0.69020F, 0.45098F},
    {0.86667F, 0.75686F, 0.43529F},
    {0.88235F, 0.83137F, 0.41961F},
    {0.91765F, 0.90588F, 0.40392F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
