#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUDA_18 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.00392F, 0.70196F},
    {0.70196F, 0.10588F, 0.65098F},
    {0.70196F, 0.17647F, 0.61569F},
    {0.71373F, 0.23529F, 0.58824F},
    {0.72941F, 0.29412F, 0.56863F},
    {0.74902F, 0.34510F, 0.55294F},
    {0.76471F, 0.39608F, 0.53333F},
    {0.78039F, 0.44706F, 0.51765F},
    {0.79608F, 0.49412F, 0.50196F},
    {0.81176F, 0.54510F, 0.49020F},
    {0.82353F, 0.59608F, 0.47451F},
    {0.83922F, 0.64706F, 0.46275F},
    {0.85098F, 0.70196F, 0.45098F},
    {0.86275F, 0.75294F, 0.43529F},
    {0.87843F, 0.80784F, 0.42353F},
    {0.89412F, 0.86667F, 0.41176F},
    {0.93333F, 0.92941F, 0.40392F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
