#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUDA_20 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.00392F, 0.70196F},
    {0.70196F, 0.09412F, 0.65882F},
    {0.70196F, 0.16078F, 0.62353F},
    {0.70980F, 0.21569F, 0.59608F},
    {0.72157F, 0.27059F, 0.57647F},
    {0.73725F, 0.31765F, 0.56078F},
    {0.75686F, 0.36471F, 0.54510F},
    {0.76863F, 0.41176F, 0.52941F},
    {0.78431F, 0.45098F, 0.51765F},
    {0.80000F, 0.49804F, 0.50196F},
    {0.81176F, 0.54118F, 0.49020F},
    {0.82353F, 0.59216F, 0.47843F},
    {0.83529F, 0.63529F, 0.46667F},
    {0.84706F, 0.67843F, 0.45490F},
    {0.85882F, 0.72941F, 0.44314F},
    {0.87059F, 0.77647F, 0.43137F},
    {0.88235F, 0.82745F, 0.41961F},
    {0.89804F, 0.87843F, 0.40784F},
    {0.94118F, 0.93725F, 0.40000F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
