#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUDA_10 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.00392F, 0.70196F},
    {0.70196F, 0.16863F, 0.61961F},
    {0.72549F, 0.28235F, 0.57255F},
    {0.76078F, 0.38039F, 0.54118F},
    {0.79216F, 0.47451F, 0.50980F},
    {0.81961F, 0.56863F, 0.48235F},
    {0.84314F, 0.66667F, 0.45882F},
    {0.86667F, 0.76471F, 0.43529F},
    {0.89804F, 0.87451F, 0.40784F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
