#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUGN_5 = std::vector<vivid::srgb_t>{
    {0.92941F, 0.97255F, 0.98431F},
    {0.69804F, 0.88627F, 0.88627F},
    {0.40000F, 0.76078F, 0.64314F},
    {0.17255F, 0.63529F, 0.37255F},
    {0.00000F, 0.42745F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
