#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BUGN_7 = std::vector<vivid::srgb_t>{
    {0.92941F, 0.97255F, 0.98431F},
    {0.80000F, 0.92549F, 0.90196F},
    {0.60000F, 0.84706F, 0.78824F},
    {0.40000F, 0.76078F, 0.64314F},
    {0.25490F, 0.68235F, 0.46275F},
    {0.13725F, 0.54510F, 0.27059F},
    {0.00000F, 0.34510F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
