#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BURGYL_7 = std::vector<vivid::srgb_t>{
    {0.98431F, 0.90196F, 0.77255F},
    {0.96078F, 0.72941F, 0.59608F},
    {0.93333F, 0.54118F, 0.50980F},
    {0.86275F, 0.44314F, 0.46275F},
    {0.78431F, 0.34510F, 0.42353F},
    {0.61176F, 0.24706F, 0.36471F},
    {0.43922F, 0.15686F, 0.29020F},
};

} // namespace GOOM::COLOR::COLOR_DATA
