#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto BURG_3 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.77647F, 0.76863F},
    {0.80000F, 0.37647F, 0.49020F},
    {0.40392F, 0.12549F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
