#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CAVALCANTI_5 = std::vector<vivid::srgb_t>{
    {0.81961F, 0.66667F, 0.00000F},
    {0.03137F, 0.19608F, 0.07451F},
    {0.57255F, 0.58039F, 0.37647F},
    {0.43529F, 0.59608F, 0.47451F},
    {0.51765F, 0.12941F, 0.06667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
