#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CORK_16 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.19608F, 0.39608F},
    {0.16863F, 0.29804F, 0.49412F},
    {0.23922F, 0.40784F, 0.58824F},
    {0.37255F, 0.52157F, 0.67059F},
    {0.51765F, 0.63137F, 0.74510F},
    {0.66667F, 0.74902F, 0.82745F},
    {0.81176F, 0.86275F, 0.89412F},
    {0.83922F, 0.90196F, 0.85882F},
    {0.71765F, 0.83529F, 0.72941F},
    {0.58431F, 0.75686F, 0.60000F},
    {0.45098F, 0.67843F, 0.47059F},
    {0.32549F, 0.58824F, 0.33333F},
    {0.25490F, 0.47843F, 0.19216F},
    {0.25490F, 0.38039F, 0.09412F},
    {0.25882F, 0.30196F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
