#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CORK_15 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.20392F, 0.40000F},
    {0.17255F, 0.30980F, 0.50588F},
    {0.27059F, 0.43529F, 0.60784F},
    {0.41569F, 0.55294F, 0.69020F},
    {0.56863F, 0.67451F, 0.77255F},
    {0.72941F, 0.79608F, 0.85882F},
    {0.85882F, 0.90196F, 0.89804F},
    {0.77255F, 0.86667F, 0.78431F},
    {0.63137F, 0.78431F, 0.64314F},
    {0.49020F, 0.70196F, 0.50588F},
    {0.35294F, 0.61176F, 0.36471F},
    {0.25882F, 0.49020F, 0.20784F},
    {0.25490F, 0.38824F, 0.09804F},
    {0.25882F, 0.30196F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
