#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CORK_18 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16863F, 0.18431F, 0.38431F},
    {0.16471F, 0.27451F, 0.47059F},
    {0.20392F, 0.36863F, 0.55686F},
    {0.30588F, 0.46667F, 0.63137F},
    {0.43137F, 0.56863F, 0.70196F},
    {0.56078F, 0.66667F, 0.76863F},
    {0.69412F, 0.76863F, 0.83922F},
    {0.81961F, 0.86667F, 0.89804F},
    {0.84706F, 0.90588F, 0.86275F},
    {0.74118F, 0.84706F, 0.75294F},
    {0.62353F, 0.78039F, 0.63529F},
    {0.50588F, 0.70980F, 0.52157F},
    {0.38824F, 0.63922F, 0.40784F},
    {0.29020F, 0.54902F, 0.28235F},
    {0.25490F, 0.45098F, 0.16863F},
    {0.25490F, 0.37255F, 0.08627F},
    {0.25882F, 0.30196F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
