#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CORK_19 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16863F, 0.18039F, 0.37647F},
    {0.16471F, 0.26275F, 0.45882F},
    {0.19216F, 0.34902F, 0.54118F},
    {0.28235F, 0.44706F, 0.61961F},
    {0.39608F, 0.54118F, 0.68235F},
    {0.51765F, 0.63137F, 0.74510F},
    {0.63922F, 0.72549F, 0.81176F},
    {0.76471F, 0.82353F, 0.87451F},
    {0.85882F, 0.90196F, 0.89804F},
    {0.80392F, 0.88235F, 0.81176F},
    {0.69412F, 0.81961F, 0.70588F},
    {0.58431F, 0.75686F, 0.60000F},
    {0.47451F, 0.69020F, 0.49020F},
    {0.36863F, 0.62353F, 0.38431F},
    {0.28235F, 0.53725F, 0.26275F},
    {0.25098F, 0.43922F, 0.15294F},
    {0.25490F, 0.36471F, 0.07843F},
    {0.25882F, 0.30196F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
