#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CORK_11 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.24706F, 0.44706F},
    {0.23922F, 0.40784F, 0.58824F},
    {0.43922F, 0.57255F, 0.70588F},
    {0.66667F, 0.74902F, 0.82745F},
    {0.85882F, 0.90196F, 0.89804F},
    {0.71765F, 0.83529F, 0.72941F},
    {0.52157F, 0.71765F, 0.53725F},
    {0.32549F, 0.58824F, 0.33333F},
    {0.25098F, 0.42353F, 0.13725F},
    {0.25882F, 0.30196F, 0.01176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
