#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEHELIX3_16 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.00000F, 0.15294F, 0.04706F},
    {0.00000F, 0.26667F, 0.23529F},
    {0.00000F, 0.31373F, 0.51373F},
    {0.01176F, 0.29412F, 0.79216F},
    {0.28235F, 0.23529F, 0.98824F},
    {0.61176F, 0.16863F, 1.00000F},
    {0.92157F, 0.14118F, 0.95686F},
    {1.00000F, 0.17647F, 0.76078F},
    {1.00000F, 0.28627F, 0.52549F},
    {1.00000F, 0.45098F, 0.33725F},
    {1.00000F, 0.64314F, 0.26275F},
    {0.92157F, 0.81961F, 0.33333F},
    {0.82745F, 0.94510F, 0.52941F},
    {0.84314F, 1.00000F, 0.78431F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
