#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEYF_9 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.00784F, 0.56471F},
    {0.51373F, 0.21569F, 0.84706F},
    {0.41569F, 0.41569F, 0.99608F},
    {0.31765F, 0.59216F, 0.87843F},
    {0.22353F, 0.72941F, 0.69412F},
    {0.29412F, 0.82353F, 0.47843F},
    {0.37647F, 0.89804F, 0.27843F},
    {0.63922F, 0.92549F, 0.33333F},
    {0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
