#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEYF_20 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.00784F, 0.56471F},
    {0.52157F, 0.05098F, 0.69412F},
    {0.52157F, 0.17647F, 0.80784F},
    {0.49804F, 0.27059F, 0.90196F},
    {0.44314F, 0.35686F, 0.98431F},
    {0.40784F, 0.43137F, 1.00000F},
    {0.36863F, 0.51765F, 0.94902F},
    {0.32157F, 0.58039F, 0.89020F},
    {0.27843F, 0.64314F, 0.82745F},
    {0.22745F, 0.70588F, 0.74118F},
    {0.23529F, 0.74902F, 0.65882F},
    {0.27059F, 0.79216F, 0.55294F},
    {0.29804F, 0.82745F, 0.46275F},
    {0.32941F, 0.85882F, 0.37255F},
    {0.36078F, 0.89020F, 0.28627F},
    {0.44314F, 0.90980F, 0.29804F},
    {0.56863F, 0.92157F, 0.32157F},
    {0.67059F, 0.92549F, 0.33725F},
    {0.74902F, 0.92549F, 0.34902F},
    {0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
