#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBE1_16 = std::vector<vivid::srgb_t>{
    {0.47059F, 0.00000F, 0.52157F},
    {0.51373F, 0.05098F, 0.70980F},
    {0.49412F, 0.25098F, 0.87843F},
    {0.43137F, 0.38431F, 0.99216F},
    {0.36863F, 0.51765F, 0.94902F},
    {0.29804F, 0.61961F, 0.85098F},
    {0.21961F, 0.71373F, 0.72157F},
    {0.26275F, 0.78431F, 0.57647F},
    {0.30980F, 0.83922F, 0.42353F},
    {0.36078F, 0.89020F, 0.28627F},
    {0.52157F, 0.92157F, 0.31373F},
    {0.67843F, 0.92549F, 0.33725F},
    {0.80000F, 0.92549F, 0.35294F},
    {0.87059F, 0.85490F, 0.36078F},
    {0.95294F, 0.74510F, 0.36863F},
    {0.97647F, 0.58824F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
