#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEHELIX1_16 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.10588F, 0.05882F, 0.00000F},
    {0.25490F, 0.09020F, 0.01569F},
    {0.40784F, 0.10588F, 0.12549F},
    {0.52157F, 0.12941F, 0.29412F},
    {0.57647F, 0.17647F, 0.49412F},
    {0.56471F, 0.25882F, 0.68627F},
    {0.50588F, 0.37647F, 0.82353F},
    {0.43529F, 0.51373F, 0.89020F},
    {0.38824F, 0.65098F, 0.88627F},
    {0.39608F, 0.77255F, 0.82745F},
    {0.47059F, 0.85882F, 0.76078F},
    {0.60000F, 0.91373F, 0.72549F},
    {0.75686F, 0.94118F, 0.74902F},
    {0.90196F, 0.96078F, 0.84706F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
