#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBE1_18 = std::vector<vivid::srgb_t>{
    {0.47059F, 0.00000F, 0.52157F},
    {0.51373F, 0.04314F, 0.69020F},
    {0.50196F, 0.20392F, 0.84314F},
    {0.45490F, 0.34118F, 0.96863F},
    {0.40000F, 0.45882F, 0.97647F},
    {0.34118F, 0.56078F, 0.91765F},
    {0.27059F, 0.64706F, 0.81569F},
    {0.22353F, 0.72549F, 0.69804F},
    {0.26667F, 0.78824F, 0.56863F},
    {0.30588F, 0.83529F, 0.43529F},
    {0.34902F, 0.88235F, 0.29412F},
    {0.47059F, 0.91765F, 0.30588F},
    {0.61569F, 0.92549F, 0.32941F},
    {0.74118F, 0.92549F, 0.34510F},
    {0.82745F, 0.91373F, 0.35686F},
    {0.89020F, 0.83529F, 0.36471F},
    {0.95686F, 0.72941F, 0.36863F},
    {0.97647F, 0.58824F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
