#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEYF_14 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.00784F, 0.56471F},
    {0.52549F, 0.11373F, 0.75294F},
    {0.49804F, 0.26667F, 0.89412F},
    {0.43137F, 0.38431F, 0.99216F},
    {0.38039F, 0.50196F, 0.96078F},
    {0.30980F, 0.60000F, 0.87059F},
    {0.23529F, 0.69412F, 0.75686F},
    {0.24314F, 0.75686F, 0.63922F},
    {0.28627F, 0.81569F, 0.49412F},
    {0.34118F, 0.86667F, 0.34510F},
    {0.40784F, 0.90588F, 0.28627F},
    {0.57647F, 0.92549F, 0.32549F},
    {0.70588F, 0.92549F, 0.34118F},
    {0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
