#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEYF_11 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.00784F, 0.56471F},
    {0.52157F, 0.16863F, 0.80000F},
    {0.45098F, 0.34118F, 0.97255F},
    {0.38431F, 0.48627F, 0.97255F},
    {0.29804F, 0.61961F, 0.85098F},
    {0.22353F, 0.72941F, 0.69412F},
    {0.27843F, 0.80392F, 0.52157F},
    {0.34510F, 0.87059F, 0.34118F},
    {0.46275F, 0.91373F, 0.30196F},
    {0.67843F, 0.92549F, 0.33725F},
    {0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
