#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBE1_4 = std::vector<vivid::srgb_t>{
    {0.47059F, 0.00000F, 0.52157F},
    {0.29804F, 0.61961F, 0.85098F},
    {0.52157F, 0.92157F, 0.31373F},
    {0.97647F, 0.58824F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
