#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEYF_18 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.00784F, 0.56471F},
    {0.52549F, 0.06667F, 0.70980F},
    {0.51765F, 0.20000F, 0.83137F},
    {0.47451F, 0.30588F, 0.94118F},
    {0.42745F, 0.39216F, 0.99216F},
    {0.38824F, 0.47843F, 0.97647F},
    {0.33725F, 0.56078F, 0.90980F},
    {0.28627F, 0.63137F, 0.83922F},
    {0.23137F, 0.70196F, 0.74510F},
    {0.23922F, 0.75294F, 0.65098F},
    {0.27451F, 0.79608F, 0.54118F},
    {0.30588F, 0.83529F, 0.43529F},
    {0.34902F, 0.87451F, 0.32941F},
    {0.40392F, 0.90196F, 0.28627F},
    {0.52549F, 0.92157F, 0.31373F},
    {0.64706F, 0.92549F, 0.33333F},
    {0.73333F, 0.92549F, 0.34510F},
    {0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
