#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CUBEYF_16 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.00784F, 0.56471F},
    {0.52549F, 0.08235F, 0.72941F},
    {0.50980F, 0.22745F, 0.85882F},
    {0.45098F, 0.34118F, 0.97255F},
    {0.40784F, 0.43922F, 0.99608F},
    {0.35294F, 0.53725F, 0.93333F},
    {0.29804F, 0.61961F, 0.85098F},
    {0.23529F, 0.69804F, 0.74902F},
    {0.23922F, 0.75294F, 0.64314F},
    {0.27843F, 0.80392F, 0.52157F},
    {0.31765F, 0.84706F, 0.40000F},
    {0.36078F, 0.89020F, 0.29020F},
    {0.46275F, 0.91373F, 0.30196F},
    {0.62353F, 0.92549F, 0.33333F},
    {0.72157F, 0.92549F, 0.34510F},
    {0.81961F, 0.92157F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
