#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_19 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.10588F, 0.21961F, 0.32549F},
    {0.10980F, 0.32549F, 0.39216F},
    {0.08235F, 0.42745F, 0.45098F},
    {0.09020F, 0.53333F, 0.49020F},
    {0.27843F, 0.62353F, 0.50980F},
    {0.49020F, 0.70196F, 0.56471F},
    {0.68235F, 0.78039F, 0.66667F},
    {0.84706F, 0.86667F, 0.80000F},
    {0.99608F, 0.96471F, 0.96078F},
    {0.93725F, 0.82745F, 0.77647F},
    {0.89804F, 0.69412F, 0.60392F},
    {0.85882F, 0.54902F, 0.46667F},
    {0.80392F, 0.41569F, 0.39608F},
    {0.72549F, 0.29412F, 0.37647F},
    {0.61569F, 0.18824F, 0.37647F},
    {0.49020F, 0.10980F, 0.37255F},
    {0.34510F, 0.07451F, 0.31765F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
