#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_12 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.10980F, 0.28627F, 0.36863F},
    {0.07059F, 0.45882F, 0.46275F},
    {0.25490F, 0.61569F, 0.50980F},
    {0.60000F, 0.74510F, 0.61569F},
    {0.87451F, 0.88235F, 0.82745F},
    {0.94510F, 0.85490F, 0.80784F},
    {0.87843F, 0.63137F, 0.53725F},
    {0.80000F, 0.40392F, 0.39216F},
    {0.64706F, 0.21569F, 0.37647F},
    {0.43922F, 0.09412F, 0.36078F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
