#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_5 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.17255F, 0.58039F, 0.49804F},
    {0.99608F, 0.96471F, 0.96078F},
    {0.76863F, 0.35294F, 0.38039F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
