#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_11 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.10980F, 0.30196F, 0.38039F},
    {0.06667F, 0.49020F, 0.47451F},
    {0.36471F, 0.65490F, 0.52549F},
    {0.71373F, 0.79608F, 0.68627F},
    {0.99608F, 0.96471F, 0.96078F},
    {0.90196F, 0.71765F, 0.63529F},
    {0.83137F, 0.46667F, 0.41569F},
    {0.68235F, 0.25098F, 0.37647F},
    {0.46275F, 0.09804F, 0.36471F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
