#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_15 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.10980F, 0.25098F, 0.34510F},
    {0.09804F, 0.38431F, 0.42745F},
    {0.07843F, 0.51765F, 0.48627F},
    {0.31373F, 0.63529F, 0.51765F},
    {0.57255F, 0.73333F, 0.60000F},
    {0.80000F, 0.83922F, 0.75686F},
    {0.99608F, 0.96471F, 0.96078F},
    {0.92549F, 0.79216F, 0.72549F},
    {0.87843F, 0.61569F, 0.52157F},
    {0.81569F, 0.43529F, 0.40000F},
    {0.70588F, 0.27451F, 0.37647F},
    {0.56471F, 0.15294F, 0.37647F},
    {0.39216F, 0.08235F, 0.34118F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
