#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_17 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.10588F, 0.23529F, 0.33725F},
    {0.10588F, 0.34902F, 0.40784F},
    {0.06667F, 0.46667F, 0.46667F},
    {0.17255F, 0.58039F, 0.49804F},
    {0.41961F, 0.67451F, 0.54118F},
    {0.63922F, 0.76078F, 0.63529F},
    {0.82745F, 0.85490F, 0.78431F},
    {0.99608F, 0.96471F, 0.96078F},
    {0.93333F, 0.81569F, 0.75686F},
    {0.88627F, 0.65882F, 0.56863F},
    {0.84314F, 0.50196F, 0.43137F},
    {0.76863F, 0.35294F, 0.38039F},
    {0.65882F, 0.22745F, 0.37647F},
    {0.52549F, 0.12549F, 0.37647F},
    {0.36471F, 0.07843F, 0.32941F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
