#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto CURL_16 = std::vector<vivid::srgb_t>{
    {0.08235F, 0.11373F, 0.26667F},
    {0.10588F, 0.24314F, 0.34118F},
    {0.10196F, 0.36471F, 0.41569F},
    {0.06667F, 0.49020F, 0.47451F},
    {0.23137F, 0.60784F, 0.50588F},
    {0.49020F, 0.70196F, 0.56471F},
    {0.71373F, 0.79608F, 0.68627F},
    {0.90588F, 0.90196F, 0.85882F},
    {0.95686F, 0.88235F, 0.84706F},
    {0.90196F, 0.71765F, 0.63529F},
    {0.85882F, 0.54902F, 0.46667F},
    {0.79216F, 0.38824F, 0.38824F},
    {0.68235F, 0.25098F, 0.37647F},
    {0.54118F, 0.13725F, 0.37647F},
    {0.37647F, 0.07843F, 0.33333F},
    {0.20392F, 0.05098F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
