#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DARKMINT_3 = std::vector<vivid::srgb_t>{
    {0.82353F, 0.98431F, 0.83137F},
    {0.33333F, 0.61176F, 0.61961F},
    {0.07059F, 0.24706F, 0.35294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
