#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DARK2_6 = std::vector<vivid::srgb_t>{
    {0.10588F, 0.61961F, 0.46667F},
    {0.85098F, 0.37255F, 0.00784F},
    {0.45882F, 0.43922F, 0.70196F},
    {0.90588F, 0.16078F, 0.54118F},
    {0.40000F, 0.65098F, 0.11765F},
    {0.90196F, 0.67059F, 0.00784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
