#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DAVOS_17 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.01961F, 0.29020F},
    {0.03137F, 0.10980F, 0.38039F},
    {0.07843F, 0.19608F, 0.46667F},
    {0.12941F, 0.27843F, 0.53725F},
    {0.18431F, 0.35294F, 0.58824F},
    {0.24314F, 0.41961F, 0.61176F},
    {0.30588F, 0.47451F, 0.61569F},
    {0.36471F, 0.51765F, 0.60000F},
    {0.42353F, 0.55686F, 0.57647F},
    {0.47843F, 0.59216F, 0.55294F},
    {0.54510F, 0.63922F, 0.53333F},
    {0.62745F, 0.69804F, 0.53725F},
    {0.73333F, 0.78039F, 0.58039F},
    {0.85098F, 0.87451F, 0.67843F},
    {0.93725F, 0.94118F, 0.79608F},
    {0.98039F, 0.97647F, 0.90196F},
    {0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
