#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DAVOS_18 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.01961F, 0.29020F},
    {0.02745F, 0.10588F, 0.37647F},
    {0.07451F, 0.18431F, 0.45490F},
    {0.11765F, 0.26275F, 0.52549F},
    {0.16863F, 0.33725F, 0.57647F},
    {0.22745F, 0.40000F, 0.60784F},
    {0.28235F, 0.45490F, 0.61569F},
    {0.33725F, 0.49804F, 0.60784F},
    {0.39608F, 0.53725F, 0.58824F},
    {0.45098F, 0.57255F, 0.56471F},
    {0.50588F, 0.61176F, 0.54118F},
    {0.57255F, 0.65882F, 0.52941F},
    {0.65882F, 0.72157F, 0.54510F},
    {0.76471F, 0.80392F, 0.60000F},
    {0.87059F, 0.89020F, 0.70196F},
    {0.94510F, 0.94902F, 0.81176F},
    {0.98039F, 0.98039F, 0.90980F},
    {0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
