#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DAVOS_15 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.01961F, 0.29020F},
    {0.03922F, 0.12157F, 0.39216F},
    {0.09020F, 0.21569F, 0.48627F},
    {0.15294F, 0.30980F, 0.56471F},
    {0.21961F, 0.39216F, 0.60392F},
    {0.28627F, 0.45882F, 0.61569F},
    {0.35294F, 0.50980F, 0.60392F},
    {0.42353F, 0.55686F, 0.57647F},
    {0.49020F, 0.60000F, 0.54902F},
    {0.56863F, 0.65490F, 0.52941F},
    {0.67059F, 0.73333F, 0.54902F},
    {0.80392F, 0.83529F, 0.63137F},
    {0.92157F, 0.92941F, 0.76863F},
    {0.97647F, 0.97647F, 0.89020F},
    {0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
