#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DAVOS_16 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.01961F, 0.29020F},
    {0.03529F, 0.11765F, 0.38431F},
    {0.08627F, 0.20392F, 0.47451F},
    {0.13725F, 0.29020F, 0.54902F},
    {0.20000F, 0.37255F, 0.59608F},
    {0.26275F, 0.43922F, 0.61569F},
    {0.32941F, 0.49020F, 0.61176F},
    {0.39216F, 0.53333F, 0.58824F},
    {0.45490F, 0.57647F, 0.56078F},
    {0.51765F, 0.61961F, 0.53725F},
    {0.60000F, 0.67843F, 0.53333F},
    {0.70588F, 0.75686F, 0.56471F},
    {0.83137F, 0.85882F, 0.65882F},
    {0.92941F, 0.93725F, 0.78039F},
    {0.97647F, 0.97647F, 0.89804F},
    {0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
