#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DAVOS_10 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.01961F, 0.29020F},
    {0.06667F, 0.17255F, 0.44314F},
    {0.16078F, 0.32157F, 0.56863F},
    {0.26275F, 0.43922F, 0.61569F},
    {0.36863F, 0.52157F, 0.59608F},
    {0.47451F, 0.58824F, 0.55294F},
    {0.60000F, 0.67843F, 0.53333F},
    {0.78824F, 0.82353F, 0.61961F},
    {0.95294F, 0.95294F, 0.82353F},
    {0.99608F, 0.99608F, 0.99608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
