#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEEP_11 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.99608F, 0.80000F},
    {0.78431F, 0.91765F, 0.69412F},
    {0.57255F, 0.84706F, 0.64314F},
    {0.40000F, 0.76078F, 0.64314F},
    {0.32157F, 0.65882F, 0.63922F},
    {0.28235F, 0.55686F, 0.61961F},
    {0.25098F, 0.45882F, 0.59608F},
    {0.24314F, 0.35686F, 0.57647F},
    {0.25490F, 0.25098F, 0.48235F},
    {0.21961F, 0.17647F, 0.31765F},
    {0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
