#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEEP_20 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.99608F, 0.80000F},
    {0.89020F, 0.95686F, 0.74118F},
    {0.77647F, 0.91765F, 0.69020F},
    {0.66667F, 0.87843F, 0.65882F},
    {0.54510F, 0.83922F, 0.63922F},
    {0.45098F, 0.79608F, 0.63922F},
    {0.38039F, 0.74510F, 0.64314F},
    {0.33725F, 0.69020F, 0.64314F},
    {0.31373F, 0.63922F, 0.63529F},
    {0.29020F, 0.58431F, 0.62353F},
    {0.27451F, 0.53333F, 0.61176F},
    {0.25882F, 0.47843F, 0.60000F},
    {0.24706F, 0.42745F, 0.59216F},
    {0.24314F, 0.37647F, 0.58039F},
    {0.24706F, 0.31373F, 0.55686F},
    {0.25882F, 0.26275F, 0.50196F},
    {0.24706F, 0.21961F, 0.41176F},
    {0.22353F, 0.18039F, 0.32941F},
    {0.18824F, 0.14118F, 0.24314F},
    {0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
