#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEEP_14 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.99608F, 0.80000F},
    {0.83137F, 0.93725F, 0.71373F},
    {0.67451F, 0.88235F, 0.65882F},
    {0.50588F, 0.82353F, 0.63922F},
    {0.39216F, 0.75686F, 0.64314F},
    {0.32941F, 0.67451F, 0.63922F},
    {0.29412F, 0.59608F, 0.62745F},
    {0.27059F, 0.52157F, 0.61176F},
    {0.25098F, 0.44314F, 0.59216F},
    {0.24314F, 0.36078F, 0.57647F},
    {0.25490F, 0.28235F, 0.52941F},
    {0.24314F, 0.21569F, 0.40392F},
    {0.20784F, 0.16078F, 0.28627F},
    {0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
