#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEEP_16 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.99608F, 0.80000F},
    {0.85882F, 0.94510F, 0.72549F},
    {0.71765F, 0.89804F, 0.67059F},
    {0.57255F, 0.84706F, 0.64314F},
    {0.44314F, 0.79216F, 0.63922F},
    {0.36471F, 0.72941F, 0.64314F},
    {0.32157F, 0.65882F, 0.63922F},
    {0.29412F, 0.59216F, 0.62745F},
    {0.27059F, 0.52549F, 0.61176F},
    {0.25098F, 0.45882F, 0.59608F},
    {0.24314F, 0.39216F, 0.58431F},
    {0.24706F, 0.32157F, 0.56078F},
    {0.25490F, 0.25098F, 0.48235F},
    {0.23529F, 0.20000F, 0.37255F},
    {0.20000F, 0.15294F, 0.26667F},
    {0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
