#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEEP_19 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.99608F, 0.80000F},
    {0.88235F, 0.95294F, 0.73725F},
    {0.76863F, 0.91373F, 0.68627F},
    {0.64706F, 0.87451F, 0.65490F},
    {0.52157F, 0.82745F, 0.63922F},
    {0.42745F, 0.78039F, 0.63922F},
    {0.36471F, 0.72941F, 0.64314F},
    {0.32549F, 0.67059F, 0.63922F},
    {0.30196F, 0.61569F, 0.63137F},
    {0.28235F, 0.55686F, 0.61961F},
    {0.26667F, 0.50196F, 0.60784F},
    {0.25098F, 0.44706F, 0.59608F},
    {0.24314F, 0.39216F, 0.58431F},
    {0.24706F, 0.33333F, 0.56471F},
    {0.25490F, 0.27451F, 0.51765F},
    {0.25098F, 0.22745F, 0.43137F},
    {0.22353F, 0.18431F, 0.33333F},
    {0.19216F, 0.14510F, 0.25098F},
    {0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
