#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEEP_17 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.99608F, 0.80000F},
    {0.86667F, 0.94902F, 0.72941F},
    {0.73333F, 0.90196F, 0.67451F},
    {0.59608F, 0.85490F, 0.64314F},
    {0.47059F, 0.80784F, 0.63922F},
    {0.38431F, 0.74902F, 0.64314F},
    {0.33333F, 0.68235F, 0.63922F},
    {0.30588F, 0.61961F, 0.63137F},
    {0.28235F, 0.55686F, 0.61961F},
    {0.26275F, 0.49804F, 0.60392F},
    {0.24706F, 0.43529F, 0.59216F},
    {0.24314F, 0.37255F, 0.57647F},
    {0.25098F, 0.30196F, 0.54902F},
    {0.25490F, 0.24314F, 0.46275F},
    {0.23137F, 0.19608F, 0.36078F},
    {0.19608F, 0.14902F, 0.26275F},
    {0.15686F, 0.10196F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
