#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_14 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.14902F, 0.22353F, 0.51765F},
    {0.10588F, 0.38039F, 0.62353F},
    {0.17255F, 0.52941F, 0.65490F},
    {0.32941F, 0.67059F, 0.69020F},
    {0.62745F, 0.78824F, 0.75686F},
    {0.87451F, 0.91373F, 0.86275F},
    {0.94902F, 0.90196F, 0.64706F},
    {0.81961F, 0.74902F, 0.31765F},
    {0.58431F, 0.64314F, 0.05882F},
    {0.30980F, 0.54902F, 0.07451F},
    {0.06667F, 0.42745F, 0.16471F},
    {0.08235F, 0.28235F, 0.16078F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
