#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_7 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.10980F, 0.40392F, 0.62745F},
    {0.42353F, 0.70980F, 0.70196F},
    {1.00000F, 0.99216F, 0.80392F},
    {0.66667F, 0.67451F, 0.12549F},
    {0.09412F, 0.45098F, 0.15686F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
