#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_9 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.10980F, 0.32157F, 0.61569F},
    {0.20000F, 0.56863F, 0.66275F},
    {0.59216F, 0.77255F, 0.74510F},
    {1.00000F, 0.99216F, 0.80392F},
    {0.79608F, 0.73333F, 0.27451F},
    {0.38039F, 0.57255F, 0.04314F},
    {0.04314F, 0.37647F, 0.17647F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
