#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_19 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.13333F, 0.19608F, 0.43529F},
    {0.12157F, 0.29020F, 0.60784F},
    {0.10980F, 0.40392F, 0.62745F},
    {0.16471F, 0.51373F, 0.65098F},
    {0.25098F, 0.61961F, 0.67843F},
    {0.42353F, 0.70980F, 0.70196F},
    {0.63922F, 0.79216F, 0.76078F},
    {0.81961F, 0.88235F, 0.83922F},
    {1.00000F, 0.99216F, 0.80392F},
    {0.92549F, 0.86275F, 0.56863F},
    {0.82745F, 0.75686F, 0.33333F},
    {0.66667F, 0.67451F, 0.12549F},
    {0.47843F, 0.60784F, 0.02353F},
    {0.28235F, 0.53725F, 0.08627F},
    {0.09412F, 0.45098F, 0.15686F},
    {0.05098F, 0.34902F, 0.17647F},
    {0.09412F, 0.24314F, 0.14510F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
