#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_20 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.12941F, 0.19216F, 0.42745F},
    {0.12941F, 0.27451F, 0.60392F},
    {0.10588F, 0.38824F, 0.62353F},
    {0.14902F, 0.49412F, 0.64706F},
    {0.21961F, 0.58824F, 0.67059F},
    {0.35686F, 0.68235F, 0.69412F},
    {0.56078F, 0.76078F, 0.73333F},
    {0.74510F, 0.84314F, 0.80392F},
    {0.91373F, 0.93333F, 0.87843F},
    {0.96471F, 0.92941F, 0.69412F},
    {0.89020F, 0.81176F, 0.46667F},
    {0.77255F, 0.72157F, 0.24706F},
    {0.60784F, 0.65098F, 0.07843F},
    {0.42353F, 0.58824F, 0.02745F},
    {0.23922F, 0.52157F, 0.10588F},
    {0.07451F, 0.43529F, 0.16078F},
    {0.05882F, 0.33725F, 0.17255F},
    {0.09804F, 0.23922F, 0.14118F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
