#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_8 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.10588F, 0.35686F, 0.61961F},
    {0.26667F, 0.63137F, 0.68235F},
    {0.77255F, 0.85490F, 0.81569F},
    {0.90196F, 0.83137F, 0.50196F},
    {0.50588F, 0.61569F, 0.02353F},
    {0.05098F, 0.40784F, 0.16863F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
