#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DELTA_11 = std::vector<vivid::srgb_t>{
    {0.06667F, 0.12549F, 0.25098F},
    {0.13725F, 0.26275F, 0.59216F},
    {0.13725F, 0.47059F, 0.63922F},
    {0.30588F, 0.65882F, 0.68627F},
    {0.67451F, 0.80784F, 0.77647F},
    {1.00000F, 0.99216F, 0.80392F},
    {0.84706F, 0.77255F, 0.37255F},
    {0.55686F, 0.63529F, 0.04314F},
    {0.19608F, 0.50196F, 0.12157F},
    {0.06275F, 0.32941F, 0.17255F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
