#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_14 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.76863F, 0.87843F, 0.90196F},
    {0.65098F, 0.81569F, 0.89020F},
    {0.54902F, 0.74510F, 0.88627F},
    {0.47843F, 0.67059F, 0.89412F},
    {0.45098F, 0.58431F, 0.89412F},
    {0.46275F, 0.49020F, 0.86275F},
    {0.47451F, 0.40000F, 0.80392F},
    {0.47451F, 0.31373F, 0.71373F},
    {0.45490F, 0.23137F, 0.60784F},
    {0.42353F, 0.16471F, 0.49412F},
    {0.37255F, 0.10588F, 0.36471F},
    {0.30588F, 0.07451F, 0.24314F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
