#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_11 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.72941F, 0.85882F, 0.89804F},
    {0.58824F, 0.77255F, 0.88627F},
    {0.48235F, 0.67843F, 0.89412F},
    {0.45098F, 0.56471F, 0.89020F},
    {0.47059F, 0.44314F, 0.83529F},
    {0.47451F, 0.32941F, 0.73333F},
    {0.45490F, 0.23137F, 0.60000F},
    {0.40784F, 0.14118F, 0.44314F},
    {0.32549F, 0.08235F, 0.27451F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
