#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_13 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.76078F, 0.87451F, 0.90196F},
    {0.63529F, 0.80784F, 0.88627F},
    {0.52549F, 0.72549F, 0.89020F},
    {0.46275F, 0.64314F, 0.89804F},
    {0.45490F, 0.54510F, 0.88627F},
    {0.47059F, 0.44314F, 0.83529F},
    {0.47451F, 0.34902F, 0.75294F},
    {0.46275F, 0.25882F, 0.64706F},
    {0.43529F, 0.18039F, 0.52157F},
    {0.38431F, 0.11765F, 0.38824F},
    {0.30980F, 0.07843F, 0.25098F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
