#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_12 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.74902F, 0.87059F, 0.90196F},
    {0.61176F, 0.79216F, 0.88627F},
    {0.50196F, 0.70196F, 0.89020F},
    {0.45490F, 0.60784F, 0.89412F},
    {0.45882F, 0.49804F, 0.86667F},
    {0.47451F, 0.39216F, 0.79608F},
    {0.47059F, 0.29412F, 0.68627F},
    {0.44706F, 0.20392F, 0.56078F},
    {0.39608F, 0.12549F, 0.40784F},
    {0.31765F, 0.07843F, 0.26275F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
