#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_19 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.80784F, 0.89804F, 0.91373F},
    {0.71765F, 0.85490F, 0.89412F},
    {0.63529F, 0.80784F, 0.88627F},
    {0.55686F, 0.75294F, 0.88627F},
    {0.49804F, 0.69804F, 0.89020F},
    {0.46275F, 0.64314F, 0.89804F},
    {0.45098F, 0.58039F, 0.89412F},
    {0.45882F, 0.51373F, 0.87451F},
    {0.47059F, 0.44314F, 0.83529F},
    {0.47451F, 0.38039F, 0.78431F},
    {0.47451F, 0.31765F, 0.71765F},
    {0.46275F, 0.25882F, 0.64706F},
    {0.44706F, 0.20784F, 0.56471F},
    {0.41961F, 0.15686F, 0.47843F},
    {0.38431F, 0.11765F, 0.38824F},
    {0.33725F, 0.08627F, 0.29412F},
    {0.27843F, 0.07059F, 0.21176F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
