#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_5 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.52549F, 0.72549F, 0.89020F},
    {0.47059F, 0.44314F, 0.83529F},
    {0.43529F, 0.18039F, 0.52157F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
