#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DENSE_16 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.94510F, 0.94510F},
    {0.78824F, 0.89020F, 0.90980F},
    {0.68235F, 0.83137F, 0.89020F},
    {0.58824F, 0.77255F, 0.88627F},
    {0.50980F, 0.70980F, 0.89020F},
    {0.46275F, 0.64314F, 0.89804F},
    {0.45098F, 0.56471F, 0.89020F},
    {0.46275F, 0.48627F, 0.86275F},
    {0.47451F, 0.40784F, 0.80784F},
    {0.47451F, 0.32941F, 0.73333F},
    {0.46275F, 0.25882F, 0.64706F},
    {0.44314F, 0.19608F, 0.54902F},
    {0.40784F, 0.14118F, 0.44314F},
    {0.35686F, 0.09804F, 0.32941F},
    {0.29020F, 0.07451F, 0.22745F},
    {0.21176F, 0.05490F, 0.14118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
