#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEVON_18 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.15686F, 0.35294F},
    {0.16078F, 0.21176F, 0.41176F},
    {0.15294F, 0.26667F, 0.47059F},
    {0.15686F, 0.32941F, 0.54118F},
    {0.18039F, 0.38431F, 0.62353F},
    {0.23137F, 0.42745F, 0.70588F},
    {0.31765F, 0.47843F, 0.78431F},
    {0.43529F, 0.53333F, 0.84314F},
    {0.54902F, 0.58431F, 0.88627F},
    {0.64314F, 0.63529F, 0.92157F},
    {0.70980F, 0.68627F, 0.94118F},
    {0.76078F, 0.73725F, 0.94902F},
    {0.80784F, 0.78824F, 0.96078F},
    {0.85490F, 0.83922F, 0.96863F},
    {0.90196F, 0.89412F, 0.98039F},
    {0.94902F, 0.94510F, 0.98824F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
