#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEVON_17 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.16078F, 0.35686F},
    {0.16078F, 0.21961F, 0.41569F},
    {0.15294F, 0.27843F, 0.48235F},
    {0.16078F, 0.34510F, 0.56078F},
    {0.19608F, 0.39608F, 0.65098F},
    {0.25882F, 0.44706F, 0.73725F},
    {0.37255F, 0.50196F, 0.81176F},
    {0.49412F, 0.56078F, 0.86667F},
    {0.60392F, 0.60784F, 0.90588F},
    {0.68627F, 0.66667F, 0.93333F},
    {0.74510F, 0.72157F, 0.94902F},
    {0.79216F, 0.77647F, 0.95686F},
    {0.84314F, 0.83137F, 0.96863F},
    {0.89412F, 0.88627F, 0.98039F},
    {0.94902F, 0.94118F, 0.98824F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
