#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto DEVON_15 = std::vector<vivid::srgb_t>{
    {0.17255F, 0.10196F, 0.29804F},
    {0.16471F, 0.16471F, 0.36471F},
    {0.15686F, 0.23137F, 0.43137F},
    {0.15294F, 0.30980F, 0.51373F},
    {0.17647F, 0.37647F, 0.61176F},
    {0.23529F, 0.42745F, 0.70980F},
    {0.34902F, 0.49020F, 0.80000F},
    {0.49412F, 0.56078F, 0.86667F},
    {0.61961F, 0.61961F, 0.91373F},
    {0.70588F, 0.68235F, 0.93725F},
    {0.76471F, 0.74510F, 0.95294F},
    {0.82353F, 0.80392F, 0.96471F},
    {0.88235F, 0.87059F, 0.97647F},
    {0.94118F, 0.93333F, 0.98824F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
