#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto EARTH_7 = std::vector<vivid::srgb_t>{
    {0.63137F, 0.41176F, 0.15686F},
    {0.74118F, 0.57255F, 0.35294F},
    {0.83922F, 0.74118F, 0.55294F},
    {0.92941F, 0.91765F, 0.76078F},
    {0.70980F, 0.78431F, 0.72157F},
    {0.47451F, 0.65490F, 0.67451F},
    {0.15686F, 0.52941F, 0.63137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
