#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto EARTH_2 = std::vector<vivid::srgb_t>{
    {0.63137F, 0.41176F, 0.15686F},
    {0.15686F, 0.52941F, 0.63137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
