#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GEYSER_7 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.50196F, 0.50196F},
    {0.43922F, 0.64314F, 0.58039F},
    {0.70588F, 0.78431F, 0.65882F},
    {0.96471F, 0.92941F, 0.74118F},
    {0.92941F, 0.73333F, 0.54118F},
    {0.87059F, 0.54118F, 0.35294F},
    {0.79216F, 0.33725F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
