#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GNBU_3 = std::vector<vivid::srgb_t>{
    {0.87843F, 0.95294F, 0.85882F},
    {0.65882F, 0.86667F, 0.70980F},
    {0.26275F, 0.63529F, 0.79216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
