#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GNBU_6 = std::vector<vivid::srgb_t>{
    {0.94118F, 0.97647F, 0.90980F},
    {0.80000F, 0.92157F, 0.77255F},
    {0.65882F, 0.86667F, 0.70980F},
    {0.48235F, 0.80000F, 0.76863F},
    {0.26275F, 0.63529F, 0.79216F},
    {0.03137F, 0.40784F, 0.67451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
