#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRANDBUDAPEST3_6 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.86275F, 0.71373F},
    {0.14510F, 0.21961F, 0.27059F},
    {0.90588F, 0.67843F, 0.61569F},
    {0.40000F, 0.45882F, 0.43137F},
    {0.54510F, 0.24706F, 0.19216F},
    {0.58824F, 0.42745F, 0.20784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
