#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAY_16 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.03922F, 0.03922F, 0.03922F},
    {0.10980F, 0.10588F, 0.10588F},
    {0.16863F, 0.16863F, 0.16863F},
    {0.23137F, 0.22745F, 0.22745F},
    {0.29020F, 0.29020F, 0.28627F},
    {0.35294F, 0.34902F, 0.34902F},
    {0.41176F, 0.41176F, 0.40784F},
    {0.47451F, 0.47451F, 0.47059F},
    {0.54118F, 0.53725F, 0.53725F},
    {0.60784F, 0.60392F, 0.60392F},
    {0.67843F, 0.67451F, 0.67451F},
    {0.75294F, 0.74902F, 0.74510F},
    {0.82745F, 0.82745F, 0.82353F},
    {0.90980F, 0.90980F, 0.90588F},
    {1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
