#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAYC_12 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.89804F, 0.89804F, 0.89804F},
    {0.80000F, 0.80000F, 0.80000F},
    {0.69804F, 0.69804F, 0.69804F},
    {0.60392F, 0.60392F, 0.60392F},
    {0.50980F, 0.50980F, 0.50980F},
    {0.42353F, 0.42353F, 0.42353F},
    {0.33725F, 0.33725F, 0.33725F},
    {0.25490F, 0.25490F, 0.25490F},
    {0.17255F, 0.17255F, 0.17255F},
    {0.10196F, 0.10196F, 0.10196F},
    {0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
