#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAY_11 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.07843F, 0.07451F, 0.07451F},
    {0.16863F, 0.16863F, 0.16863F},
    {0.25882F, 0.25882F, 0.25490F},
    {0.35294F, 0.34902F, 0.34902F},
    {0.44706F, 0.44314F, 0.44314F},
    {0.54118F, 0.53725F, 0.53725F},
    {0.63922F, 0.63922F, 0.63529F},
    {0.75294F, 0.74902F, 0.74510F},
    {0.87059F, 0.87059F, 0.86667F},
    {1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
