#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAY_14 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.05098F, 0.05098F, 0.05098F},
    {0.12549F, 0.12549F, 0.12549F},
    {0.20000F, 0.19608F, 0.19608F},
    {0.26667F, 0.26275F, 0.26275F},
    {0.33725F, 0.33333F, 0.33333F},
    {0.40784F, 0.40784F, 0.40392F},
    {0.47843F, 0.47843F, 0.47451F},
    {0.55686F, 0.55294F, 0.55294F},
    {0.63529F, 0.63529F, 0.63137F},
    {0.71765F, 0.71373F, 0.70980F},
    {0.80392F, 0.80392F, 0.80000F},
    {0.89804F, 0.89412F, 0.89020F},
    {1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
