#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAY_20 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.02353F, 0.02353F, 0.02353F},
    {0.08235F, 0.07843F, 0.07843F},
    {0.12941F, 0.12941F, 0.12941F},
    {0.18039F, 0.18039F, 0.18039F},
    {0.22745F, 0.22353F, 0.22353F},
    {0.27843F, 0.27451F, 0.27451F},
    {0.32157F, 0.32157F, 0.31765F},
    {0.36863F, 0.36863F, 0.36471F},
    {0.41961F, 0.41961F, 0.41569F},
    {0.46667F, 0.46667F, 0.46275F},
    {0.52157F, 0.51765F, 0.51765F},
    {0.57255F, 0.56863F, 0.56863F},
    {0.62353F, 0.62353F, 0.61961F},
    {0.68235F, 0.67843F, 0.67843F},
    {0.73725F, 0.73725F, 0.73333F},
    {0.80000F, 0.80000F, 0.79608F},
    {0.86275F, 0.86275F, 0.85882F},
    {0.93333F, 0.92941F, 0.92549F},
    {1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
