#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAYC_14 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.90980F, 0.90980F, 0.90980F},
    {0.82745F, 0.82745F, 0.82745F},
    {0.74510F, 0.74510F, 0.74510F},
    {0.66275F, 0.66275F, 0.66275F},
    {0.58431F, 0.58431F, 0.58431F},
    {0.50196F, 0.50196F, 0.50196F},
    {0.43137F, 0.43137F, 0.43137F},
    {0.35294F, 0.35294F, 0.35294F},
    {0.28235F, 0.28235F, 0.28235F},
    {0.21569F, 0.21569F, 0.21569F},
    {0.14902F, 0.14902F, 0.14902F},
    {0.09020F, 0.09020F, 0.09020F},
    {0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
