#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAYC_7 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.81569F, 0.81569F, 0.81569F},
    {0.63529F, 0.63529F, 0.63529F},
    {0.46275F, 0.46275F, 0.46275F},
    {0.30588F, 0.30588F, 0.30588F},
    {0.16471F, 0.16471F, 0.16471F},
    {0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
