#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAY_17 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.03529F, 0.03529F, 0.03529F},
    {0.10196F, 0.09804F, 0.09804F},
    {0.16078F, 0.15686F, 0.15686F},
    {0.21569F, 0.21569F, 0.21569F},
    {0.27451F, 0.27059F, 0.27059F},
    {0.32941F, 0.32941F, 0.32549F},
    {0.38824F, 0.38431F, 0.38431F},
    {0.44706F, 0.44314F, 0.44314F},
    {0.50196F, 0.49804F, 0.49804F},
    {0.56471F, 0.56078F, 0.56078F},
    {0.62745F, 0.62745F, 0.62353F},
    {0.69412F, 0.69412F, 0.69020F},
    {0.76471F, 0.76471F, 0.76078F},
    {0.83922F, 0.83922F, 0.83137F},
    {0.91765F, 0.91765F, 0.90980F},
    {1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
