#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAYC_20 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.94118F, 0.94118F, 0.94118F},
    {0.88235F, 0.88235F, 0.88235F},
    {0.82353F, 0.82353F, 0.82353F},
    {0.76471F, 0.76471F, 0.76471F},
    {0.70980F, 0.70980F, 0.70980F},
    {0.65098F, 0.65098F, 0.65098F},
    {0.60000F, 0.60000F, 0.60000F},
    {0.54510F, 0.54510F, 0.54510F},
    {0.49020F, 0.49020F, 0.49020F},
    {0.44314F, 0.44314F, 0.44314F},
    {0.38824F, 0.38824F, 0.38824F},
    {0.34118F, 0.34118F, 0.34118F},
    {0.29412F, 0.29412F, 0.29412F},
    {0.24314F, 0.24314F, 0.24314F},
    {0.20000F, 0.20000F, 0.20000F},
    {0.15294F, 0.15294F, 0.15294F},
    {0.11373F, 0.11373F, 0.11373F},
    {0.06667F, 0.06667F, 0.06667F},
    {0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
