#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAYC_16 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 1.00000F},
    {0.92549F, 0.92549F, 0.92549F},
    {0.85098F, 0.85098F, 0.85098F},
    {0.77647F, 0.77647F, 0.77647F},
    {0.70588F, 0.70588F, 0.70588F},
    {0.63529F, 0.63529F, 0.63529F},
    {0.56863F, 0.56863F, 0.56863F},
    {0.49804F, 0.49804F, 0.49804F},
    {0.43529F, 0.43529F, 0.43529F},
    {0.36863F, 0.36863F, 0.36863F},
    {0.30588F, 0.30588F, 0.30588F},
    {0.24706F, 0.24706F, 0.24706F},
    {0.18824F, 0.18824F, 0.18824F},
    {0.13333F, 0.13333F, 0.13333F},
    {0.08235F, 0.08235F, 0.08235F},
    {0.00000F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
