#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GRAY_4 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.29020F, 0.29020F, 0.28627F},
    {0.60784F, 0.60392F, 0.60392F},
    {1.00000F, 1.00000F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
