#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GREENS_5 = std::vector<vivid::srgb_t>{
    {0.92941F, 0.97255F, 0.91373F},
    {0.72941F, 0.89412F, 0.70196F},
    {0.45490F, 0.76863F, 0.46275F},
    {0.19216F, 0.63922F, 0.32941F},
    {0.00000F, 0.42745F, 0.17255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
