#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GREENORANGE_12 = std::vector<vivid::srgb_t>{
    {0.19608F, 0.63529F, 0.31765F},
    {0.67451F, 0.85098F, 0.55294F},
    {1.00000F, 0.49804F, 0.05882F},
    {1.00000F, 0.72549F, 0.46667F},
    {0.23529F, 0.71765F, 0.80000F},
    {0.59608F, 0.85098F, 0.89412F},
    {0.72157F, 0.35294F, 0.05098F},
    {1.00000F, 0.85098F, 0.29020F},
    {0.22353F, 0.45098F, 0.48627F},
    {0.52549F, 0.70588F, 0.66275F},
    {0.50980F, 0.52157F, 0.23137F},
    {0.80000F, 0.78824F, 0.30196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
