#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GREENS_3 = std::vector<vivid::srgb_t>{
    {0.89804F, 0.96078F, 0.87843F},
    {0.63137F, 0.85098F, 0.60784F},
    {0.19216F, 0.63922F, 0.32941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
