#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GREENS_9 = std::vector<vivid::srgb_t>{
    {0.96863F, 0.98824F, 0.96078F},
    {0.89804F, 0.96078F, 0.87843F},
    {0.78039F, 0.91373F, 0.75294F},
    {0.63137F, 0.85098F, 0.60784F},
    {0.45490F, 0.76863F, 0.46275F},
    {0.25490F, 0.67059F, 0.36471F},
    {0.13725F, 0.54510F, 0.27059F},
    {0.00000F, 0.42745F, 0.17255F},
    {0.00000F, 0.26667F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
