#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GREYS_3 = std::vector<vivid::srgb_t>{
    {0.94118F, 0.94118F, 0.94118F},
    {0.74118F, 0.74118F, 0.74118F},
    {0.38824F, 0.38824F, 0.38824F},
};

} // namespace GOOM::COLOR::COLOR_DATA
