#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto GREYS_5 = std::vector<vivid::srgb_t>{
    {0.96863F, 0.96863F, 0.96863F},
    {0.80000F, 0.80000F, 0.80000F},
    {0.58824F, 0.58824F, 0.58824F},
    {0.38824F, 0.38824F, 0.38824F},
    {0.14510F, 0.14510F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
