#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HALINE_17 = std::vector<vivid::srgb_t>{
    {0.16471F, 0.09412F, 0.42353F},
    {0.18039F, 0.11373F, 0.57647F},
    {0.12549F, 0.20392F, 0.63529F},
    {0.05882F, 0.29020F, 0.59608F},
    {0.05882F, 0.35686F, 0.56471F},
    {0.10980F, 0.41569F, 0.54902F},
    {0.16078F, 0.46667F, 0.53725F},
    {0.20000F, 0.52157F, 0.53333F},
    {0.23529F, 0.57647F, 0.52941F},
    {0.26667F, 0.63137F, 0.51765F},
    {0.30980F, 0.68627F, 0.49412F},
    {0.37255F, 0.74510F, 0.45882F},
    {0.47059F, 0.79608F, 0.40784F},
    {0.60784F, 0.83529F, 0.36078F},
    {0.75686F, 0.86667F, 0.39216F},
    {0.88235F, 0.89804F, 0.48627F},
    {0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
