#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HALINE_16 = std::vector<vivid::srgb_t>{
    {0.16471F, 0.09412F, 0.42353F},
    {0.18039F, 0.11765F, 0.58431F},
    {0.11373F, 0.21569F, 0.63137F},
    {0.05098F, 0.30588F, 0.58824F},
    {0.07059F, 0.37255F, 0.56078F},
    {0.12549F, 0.43137F, 0.54510F},
    {0.17647F, 0.48627F, 0.53725F},
    {0.21569F, 0.54510F, 0.53333F},
    {0.25098F, 0.60392F, 0.52549F},
    {0.29020F, 0.66667F, 0.50588F},
    {0.35294F, 0.72549F, 0.47059F},
    {0.44314F, 0.78431F, 0.41961F},
    {0.58039F, 0.82745F, 0.36471F},
    {0.74118F, 0.86275F, 0.38431F},
    {0.87843F, 0.89804F, 0.47843F},
    {0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
