#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HALINE_15 = std::vector<vivid::srgb_t>{
    {0.16471F, 0.09412F, 0.42353F},
    {0.18039F, 0.11765F, 0.59608F},
    {0.10588F, 0.22745F, 0.62745F},
    {0.04706F, 0.32157F, 0.58039F},
    {0.08627F, 0.38824F, 0.55294F},
    {0.14510F, 0.45098F, 0.54118F},
    {0.19216F, 0.50980F, 0.53333F},
    {0.23529F, 0.57647F, 0.52941F},
    {0.27451F, 0.64314F, 0.51373F},
    {0.32549F, 0.70588F, 0.48627F},
    {0.41176F, 0.76863F, 0.43529F},
    {0.54510F, 0.81961F, 0.37647F},
    {0.72157F, 0.85882F, 0.37647F},
    {0.87059F, 0.89412F, 0.47451F},
    {0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
