#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HALINE_6 = std::vector<vivid::srgb_t>{
    {0.16471F, 0.09412F, 0.42353F},
    {0.05098F, 0.30588F, 0.58824F},
    {0.17647F, 0.48627F, 0.53725F},
    {0.29020F, 0.66667F, 0.50588F},
    {0.58039F, 0.82745F, 0.36471F},
    {0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
