#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HALINE_13 = std::vector<vivid::srgb_t>{
    {0.16471F, 0.09412F, 0.42353F},
    {0.17647F, 0.12941F, 0.61569F},
    {0.07843F, 0.26275F, 0.61176F},
    {0.05882F, 0.35686F, 0.56471F},
    {0.12549F, 0.43137F, 0.54510F},
    {0.18431F, 0.50196F, 0.53725F},
    {0.23529F, 0.57647F, 0.52941F},
    {0.28235F, 0.65098F, 0.50980F},
    {0.35294F, 0.72549F, 0.47059F},
    {0.47059F, 0.79608F, 0.40784F},
    {0.65882F, 0.84706F, 0.36078F},
    {0.84706F, 0.88627F, 0.45098F},
    {0.99216F, 0.93725F, 0.60392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
