#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HAWAII_6 = std::vector<vivid::srgb_t>{
    {0.54902F, 0.00784F, 0.45098F},
    {0.58431F, 0.25490F, 0.27843F},
    {0.61176F, 0.45882F, 0.14118F},
    {0.56078F, 0.71373F, 0.23529F},
    {0.38431F, 0.86275F, 0.66275F},
    {0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
