#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HAWAII_20 = std::vector<vivid::srgb_t>{
    {0.54902F, 0.00784F, 0.45098F},
    {0.56078F, 0.09804F, 0.40000F},
    {0.57255F, 0.16078F, 0.35294F},
    {0.57647F, 0.21176F, 0.30980F},
    {0.58431F, 0.26667F, 0.27059F},
    {0.59216F, 0.31765F, 0.23529F},
    {0.60000F, 0.37255F, 0.19608F},
    {0.60784F, 0.42353F, 0.16471F},
    {0.61176F, 0.48235F, 0.12941F},
    {0.61569F, 0.55294F, 0.10980F},
    {0.60392F, 0.62353F, 0.12549F},
    {0.57647F, 0.69020F, 0.20000F},
    {0.53333F, 0.74510F, 0.29804F},
    {0.48627F, 0.78431F, 0.40392F},
    {0.43529F, 0.82353F, 0.52549F},
    {0.39216F, 0.85490F, 0.63529F},
    {0.37255F, 0.89412F, 0.76078F},
    {0.42745F, 0.92157F, 0.86275F},
    {0.56078F, 0.94118F, 0.94510F},
    {0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
