#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HAWAII_19 = std::vector<vivid::srgb_t>{
    {0.54902F, 0.00784F, 0.45098F},
    {0.56078F, 0.10196F, 0.39608F},
    {0.57255F, 0.16471F, 0.34902F},
    {0.58039F, 0.21961F, 0.30196F},
    {0.58824F, 0.27843F, 0.25882F},
    {0.59216F, 0.32941F, 0.22353F},
    {0.60000F, 0.38824F, 0.18824F},
    {0.60784F, 0.44706F, 0.14902F},
    {0.61569F, 0.51373F, 0.11765F},
    {0.61176F, 0.58824F, 0.10980F},
    {0.59216F, 0.66275F, 0.16471F},
    {0.54902F, 0.72549F, 0.25882F},
    {0.50196F, 0.77255F, 0.37255F},
    {0.44706F, 0.81176F, 0.49020F},
    {0.40000F, 0.84706F, 0.61176F},
    {0.37255F, 0.88627F, 0.73333F},
    {0.42353F, 0.92157F, 0.85882F},
    {0.55294F, 0.94118F, 0.94118F},
    {0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
