#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HAWAII_12 = std::vector<vivid::srgb_t>{
    {0.54902F, 0.00784F, 0.45098F},
    {0.56863F, 0.14510F, 0.36471F},
    {0.58039F, 0.23529F, 0.29020F},
    {0.59216F, 0.32549F, 0.22745F},
    {0.60392F, 0.41961F, 0.16471F},
    {0.61569F, 0.52941F, 0.11373F},
    {0.59608F, 0.64706F, 0.14902F},
    {0.52941F, 0.74510F, 0.30588F},
    {0.44314F, 0.81569F, 0.49804F},
    {0.37647F, 0.87843F, 0.70588F},
    {0.46275F, 0.92941F, 0.89020F},
    {0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
