#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto HAWAII_14 = std::vector<vivid::srgb_t>{
    {0.54902F, 0.00784F, 0.45098F},
    {0.56471F, 0.12941F, 0.37647F},
    {0.57647F, 0.20784F, 0.31373F},
    {0.58824F, 0.28627F, 0.25490F},
    {0.59608F, 0.36078F, 0.20392F},
    {0.60784F, 0.44314F, 0.15294F},
    {0.61569F, 0.53725F, 0.10980F},
    {0.60000F, 0.63922F, 0.13725F},
    {0.54902F, 0.72941F, 0.26667F},
    {0.47451F, 0.79216F, 0.43137F},
    {0.40784F, 0.84314F, 0.59216F},
    {0.37647F, 0.89412F, 0.76863F},
    {0.49020F, 0.93333F, 0.90980F},
    {0.70196F, 0.94902F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
