#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_6 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.18824F, 0.18431F, 0.37255F},
    {0.24314F, 0.36863F, 0.66275F},
    {0.32157F, 0.58824F, 0.75686F},
    {0.54902F, 0.79608F, 0.83922F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
