#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_18 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.07059F, 0.07451F, 0.15686F},
    {0.12157F, 0.12157F, 0.24314F},
    {0.17255F, 0.16471F, 0.33333F},
    {0.21176F, 0.20784F, 0.43137F},
    {0.23922F, 0.25882F, 0.52941F},
    {0.24706F, 0.31765F, 0.61569F},
    {0.24314F, 0.38039F, 0.67059F},
    {0.25098F, 0.44706F, 0.70588F},
    {0.27451F, 0.50980F, 0.72941F},
    {0.31373F, 0.57255F, 0.75294F},
    {0.36471F, 0.63529F, 0.77255F},
    {0.42353F, 0.69804F, 0.79608F},
    {0.49804F, 0.76078F, 0.82353F},
    {0.59216F, 0.81961F, 0.85098F},
    {0.70196F, 0.87451F, 0.89020F},
    {0.81176F, 0.92941F, 0.93725F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
