#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_5 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.21961F, 0.22353F, 0.45882F},
    {0.25882F, 0.48235F, 0.71765F},
    {0.47451F, 0.74510F, 0.81569F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
