#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_14 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.09020F, 0.09020F, 0.18431F},
    {0.15294F, 0.14510F, 0.29804F},
    {0.20784F, 0.20784F, 0.42353F},
    {0.24314F, 0.27059F, 0.54902F},
    {0.24706F, 0.34902F, 0.64706F},
    {0.24706F, 0.43922F, 0.70196F},
    {0.27843F, 0.52157F, 0.73333F},
    {0.33333F, 0.60392F, 0.76078F},
    {0.41176F, 0.68627F, 0.79216F},
    {0.50196F, 0.76471F, 0.82353F},
    {0.63529F, 0.83922F, 0.86275F},
    {0.77647F, 0.90980F, 0.92157F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
