#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_13 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.09020F, 0.09412F, 0.19216F},
    {0.16078F, 0.15686F, 0.31765F},
    {0.21961F, 0.22353F, 0.45882F},
    {0.24706F, 0.29412F, 0.58824F},
    {0.24314F, 0.38431F, 0.67451F},
    {0.25882F, 0.48235F, 0.71765F},
    {0.30980F, 0.56863F, 0.74902F},
    {0.38039F, 0.65882F, 0.78039F},
    {0.47451F, 0.74510F, 0.81569F},
    {0.60392F, 0.82745F, 0.85490F},
    {0.76863F, 0.90588F, 0.91765F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
