#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_10 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.11765F, 0.11373F, 0.23137F},
    {0.20392F, 0.20000F, 0.41176F},
    {0.24706F, 0.29412F, 0.58824F},
    {0.24314F, 0.41569F, 0.69020F},
    {0.29020F, 0.54118F, 0.74118F},
    {0.38039F, 0.65882F, 0.78039F},
    {0.51373F, 0.77255F, 0.82745F},
    {0.71765F, 0.88235F, 0.89412F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
