#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ICE_15 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.02353F, 0.07451F},
    {0.08235F, 0.08235F, 0.17255F},
    {0.14510F, 0.13725F, 0.27843F},
    {0.20000F, 0.19608F, 0.40000F},
    {0.23529F, 0.25098F, 0.51765F},
    {0.24706F, 0.32157F, 0.61961F},
    {0.24314F, 0.40000F, 0.68235F},
    {0.25882F, 0.48235F, 0.71765F},
    {0.30196F, 0.55686F, 0.74510F},
    {0.36078F, 0.63137F, 0.77255F},
    {0.43137F, 0.70588F, 0.80000F},
    {0.52549F, 0.78039F, 0.83137F},
    {0.65882F, 0.85098F, 0.87059F},
    {0.78824F, 0.91765F, 0.92941F},
    {0.91765F, 0.99216F, 0.99216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
