#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto IMOLA_9 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.20000F, 0.70196F},
    {0.14510F, 0.28627F, 0.65882F},
    {0.18824F, 0.36863F, 0.61569F},
    {0.24706F, 0.44314F, 0.55686F},
    {0.32941F, 0.52549F, 0.49804F},
    {0.43922F, 0.63922F, 0.46667F},
    {0.56863F, 0.76471F, 0.43529F},
    {0.74118F, 0.90196F, 0.40392F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
