#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto IMOLA_18 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.20000F, 0.70196F},
    {0.12549F, 0.24314F, 0.67843F},
    {0.14510F, 0.28235F, 0.65882F},
    {0.16471F, 0.32157F, 0.63922F},
    {0.18431F, 0.35686F, 0.61961F},
    {0.20392F, 0.39608F, 0.59608F},
    {0.23529F, 0.43137F, 0.56863F},
    {0.26667F, 0.46275F, 0.53725F},
    {0.30588F, 0.50196F, 0.50980F},
    {0.35294F, 0.54902F, 0.49020F},
    {0.40392F, 0.60392F, 0.47451F},
    {0.46275F, 0.66275F, 0.45882F},
    {0.52157F, 0.72157F, 0.44706F},
    {0.58431F, 0.78431F, 0.43137F},
    {0.65490F, 0.84706F, 0.41569F},
    {0.75294F, 0.90980F, 0.40392F},
    {0.87451F, 0.95686F, 0.40000F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
