#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto IMOLA_8 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.20000F, 0.70196F},
    {0.15294F, 0.29804F, 0.65098F},
    {0.20392F, 0.39216F, 0.60000F},
    {0.27451F, 0.47451F, 0.52941F},
    {0.39216F, 0.58824F, 0.47843F},
    {0.52941F, 0.72941F, 0.44314F},
    {0.70980F, 0.88627F, 0.40784F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
