#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto IMOLA_11 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.20000F, 0.70196F},
    {0.13725F, 0.27059F, 0.66667F},
    {0.17255F, 0.33333F, 0.63137F},
    {0.20784F, 0.39608F, 0.59608F},
    {0.25882F, 0.45490F, 0.54510F},
    {0.32941F, 0.52549F, 0.49804F},
    {0.41569F, 0.61569F, 0.47059F},
    {0.51373F, 0.71373F, 0.44706F},
    {0.62353F, 0.82353F, 0.41961F},
    {0.79216F, 0.92549F, 0.40392F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
