#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto IMOLA_10 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.20000F, 0.70196F},
    {0.14118F, 0.27451F, 0.66275F},
    {0.18039F, 0.34902F, 0.62353F},
    {0.22353F, 0.41961F, 0.58039F},
    {0.28627F, 0.48235F, 0.52157F},
    {0.37647F, 0.57255F, 0.48235F},
    {0.48235F, 0.68235F, 0.45490F},
    {0.59608F, 0.79608F, 0.42745F},
    {0.76863F, 0.91765F, 0.40392F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
