#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto IMOLA_13 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.20000F, 0.70196F},
    {0.13333F, 0.25882F, 0.67059F},
    {0.16078F, 0.31373F, 0.64314F},
    {0.18824F, 0.36863F, 0.61569F},
    {0.22353F, 0.41961F, 0.58039F},
    {0.27059F, 0.46667F, 0.53725F},
    {0.32941F, 0.52549F, 0.49804F},
    {0.40392F, 0.60000F, 0.47451F},
    {0.48235F, 0.68235F, 0.45490F},
    {0.56863F, 0.76471F, 0.43529F},
    {0.66667F, 0.85490F, 0.41176F},
    {0.82745F, 0.94118F, 0.40000F},
    {1.00000F, 1.00000F, 0.40000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
