#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto INFERNO_20 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.03137F, 0.01961F, 0.11373F},
    {0.09804F, 0.04706F, 0.24314F},
    {0.18431F, 0.03922F, 0.35686F},
    {0.27843F, 0.04314F, 0.41569F},
    {0.36078F, 0.07059F, 0.43137F},
    {0.44706F, 0.10196F, 0.43137F},
    {0.52941F, 0.12941F, 0.41961F},
    {0.60784F, 0.16078F, 0.39216F},
    {0.69412F, 0.19608F, 0.35294F},
    {0.76863F, 0.23529F, 0.30588F},
    {0.84314F, 0.29412F, 0.24706F},
    {0.89804F, 0.36078F, 0.18824F},
    {0.94118F, 0.43529F, 0.12549F},
    {0.97255F, 0.52941F, 0.05490F},
    {0.98824F, 0.62353F, 0.02745F},
    {0.98431F, 0.72941F, 0.12157F},
    {0.96863F, 0.82745F, 0.25098F},
    {0.94510F, 0.92941F, 0.44314F},
    {0.98824F, 1.00000F, 0.64314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
