#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto INFERNO_9 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.12941F, 0.04706F, 0.29020F},
    {0.34118F, 0.06275F, 0.43137F},
    {0.54118F, 0.13333F, 0.41569F},
    {0.73725F, 0.21569F, 0.32941F},
    {0.89020F, 0.34902F, 0.20000F},
    {0.97647F, 0.54902F, 0.03922F},
    {0.97647F, 0.78824F, 0.19608F},
    {0.98824F, 1.00000F, 0.64314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
