#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto INFERNO_11 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.09412F, 0.04706F, 0.23529F},
    {0.25882F, 0.03922F, 0.40784F},
    {0.41569F, 0.09020F, 0.43137F},
    {0.57647F, 0.14902F, 0.40392F},
    {0.73725F, 0.21569F, 0.32941F},
    {0.86667F, 0.31765F, 0.22745F},
    {0.95294F, 0.46275F, 0.10588F},
    {0.98824F, 0.64706F, 0.03922F},
    {0.96471F, 0.84314F, 0.27451F},
    {0.98824F, 1.00000F, 0.64314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
