#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto INFERNO_14 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.06275F, 0.03529F, 0.17647F},
    {0.17647F, 0.04314F, 0.34902F},
    {0.30980F, 0.05098F, 0.42353F},
    {0.42745F, 0.09412F, 0.43137F},
    {0.55294F, 0.13725F, 0.41176F},
    {0.67843F, 0.18824F, 0.36471F},
    {0.78431F, 0.24706F, 0.29412F},
    {0.88235F, 0.33725F, 0.20784F},
    {0.94902F, 0.45490F, 0.10980F},
    {0.98431F, 0.58824F, 0.02353F},
    {0.98431F, 0.73725F, 0.12941F},
    {0.95686F, 0.88235F, 0.33725F},
    {0.98824F, 1.00000F, 0.64314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
