#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAJOLLA_15 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.99216F, 0.95294F, 0.67451F},
    {0.98039F, 0.89804F, 0.54510F},
    {0.96078F, 0.81176F, 0.41569F},
    {0.93725F, 0.71765F, 0.34902F},
    {0.91765F, 0.63137F, 0.32549F},
    {0.90196F, 0.54902F, 0.31765F},
    {0.87059F, 0.45490F, 0.30980F},
    {0.80392F, 0.36471F, 0.29804F},
    {0.68627F, 0.29412F, 0.27059F},
    {0.56078F, 0.25098F, 0.23137F},
    {0.43529F, 0.21569F, 0.17647F},
    {0.30980F, 0.17255F, 0.11765F},
    {0.20000F, 0.13725F, 0.06667F},
    {0.10196F, 0.10196F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
