#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAJOLLA_20 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.99608F, 0.96863F, 0.70980F},
    {0.98824F, 0.92941F, 0.61176F},
    {0.97647F, 0.88235F, 0.51765F},
    {0.96078F, 0.81569F, 0.42353F},
    {0.94510F, 0.74902F, 0.36471F},
    {0.92941F, 0.67843F, 0.33725F},
    {0.91765F, 0.61569F, 0.32549F},
    {0.90196F, 0.55686F, 0.32157F},
    {0.88235F, 0.49020F, 0.31373F},
    {0.85490F, 0.42353F, 0.30588F},
    {0.79216F, 0.35686F, 0.29412F},
    {0.70980F, 0.30196F, 0.27451F},
    {0.61569F, 0.26667F, 0.25098F},
    {0.51765F, 0.23922F, 0.21569F},
    {0.43137F, 0.21176F, 0.17647F},
    {0.33725F, 0.18431F, 0.12941F},
    {0.25490F, 0.15686F, 0.09020F},
    {0.16863F, 0.12941F, 0.05098F},
    {0.10196F, 0.10196F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
