#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAJOLLA_10 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.98431F, 0.92549F, 0.60392F},
    {0.95686F, 0.80000F, 0.40784F},
    {0.92549F, 0.65882F, 0.33333F},
    {0.89412F, 0.52941F, 0.31765F},
    {0.82353F, 0.38431F, 0.30196F},
    {0.64706F, 0.27843F, 0.25882F},
    {0.45098F, 0.21961F, 0.18431F},
    {0.25882F, 0.15686F, 0.09412F},
    {0.10196F, 0.10196F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
