#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAJOLLA_7 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.97255F, 0.87451F, 0.50196F},
    {0.92549F, 0.65882F, 0.33333F},
    {0.87059F, 0.45490F, 0.30980F},
    {0.64706F, 0.27843F, 0.25882F},
    {0.35686F, 0.18824F, 0.14118F},
    {0.10196F, 0.10196F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
