#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAJOLLA_18 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.99216F, 0.96078F, 0.69412F},
    {0.98431F, 0.91765F, 0.58824F},
    {0.97255F, 0.86275F, 0.48235F},
    {0.95294F, 0.78431F, 0.39216F},
    {0.93333F, 0.70588F, 0.34510F},
    {0.92157F, 0.63529F, 0.32941F},
    {0.90588F, 0.56471F, 0.32157F},
    {0.88627F, 0.49412F, 0.31373F},
    {0.85098F, 0.41961F, 0.30588F},
    {0.78039F, 0.34510F, 0.29412F},
    {0.68235F, 0.29020F, 0.27059F},
    {0.57647F, 0.25490F, 0.23529F},
    {0.47059F, 0.22353F, 0.19216F},
    {0.36863F, 0.19216F, 0.14510F},
    {0.27059F, 0.16078F, 0.10196F},
    {0.18039F, 0.13333F, 0.05882F},
    {0.10196F, 0.10196F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
