#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAPAZ_5 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.04706F, 0.39216F},
    {0.17647F, 0.32549F, 0.57647F},
    {0.36078F, 0.54902F, 0.63922F},
    {0.70196F, 0.67451F, 0.58824F},
    {0.99608F, 0.94902F, 0.95294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
