#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAPAZ_20 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.04706F, 0.39216F},
    {0.12157F, 0.11373F, 0.43529F},
    {0.13333F, 0.17255F, 0.47843F},
    {0.14902F, 0.22745F, 0.51765F},
    {0.16078F, 0.28627F, 0.55294F},
    {0.18039F, 0.33725F, 0.58431F},
    {0.20392F, 0.38824F, 0.60784F},
    {0.23529F, 0.43922F, 0.62745F},
    {0.27451F, 0.48235F, 0.63922F},
    {0.32941F, 0.52941F, 0.64314F},
    {0.38824F, 0.56471F, 0.63529F},
    {0.46275F, 0.60000F, 0.62353F},
    {0.52941F, 0.62353F, 0.60784F},
    {0.60000F, 0.64314F, 0.59216F},
    {0.68235F, 0.66667F, 0.58431F},
    {0.77255F, 0.70588F, 0.60784F},
    {0.87059F, 0.76471F, 0.67059F},
    {0.94118F, 0.83137F, 0.76078F},
    {0.98039F, 0.89804F, 0.86275F},
    {0.99608F, 0.94902F, 0.95294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
