#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAPAZ_12 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.04706F, 0.39216F},
    {0.12941F, 0.15686F, 0.46667F},
    {0.15294F, 0.25098F, 0.53333F},
    {0.18431F, 0.34902F, 0.58824F},
    {0.23137F, 0.43529F, 0.62353F},
    {0.30980F, 0.51373F, 0.64314F},
    {0.41569F, 0.58039F, 0.63137F},
    {0.53725F, 0.62353F, 0.60392F},
    {0.66667F, 0.66275F, 0.58431F},
    {0.82745F, 0.73725F, 0.63922F},
    {0.95686F, 0.85098F, 0.78824F},
    {0.99608F, 0.94902F, 0.95294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
