#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LAPAZ_17 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.04706F, 0.39216F},
    {0.12549F, 0.12549F, 0.44314F},
    {0.14118F, 0.19608F, 0.49412F},
    {0.15686F, 0.25882F, 0.53725F},
    {0.17647F, 0.32549F, 0.57647F},
    {0.20000F, 0.38431F, 0.60784F},
    {0.23922F, 0.44314F, 0.62745F},
    {0.29412F, 0.50196F, 0.63922F},
    {0.36078F, 0.54902F, 0.63922F},
    {0.43529F, 0.58824F, 0.63137F},
    {0.52157F, 0.61961F, 0.61176F},
    {0.60784F, 0.64314F, 0.58824F},
    {0.70196F, 0.67451F, 0.58824F},
    {0.81569F, 0.72941F, 0.62745F},
    {0.91765F, 0.80784F, 0.72549F},
    {0.97647F, 0.88235F, 0.83922F},
    {0.99608F, 0.94902F, 0.95294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
