#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LINEARL_9 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.01569F, 0.01569F},
    {0.17647F, 0.09020F, 0.27843F},
    {0.10588F, 0.22353F, 0.49804F},
    {0.00000F, 0.39216F, 0.42745F},
    {0.00000F, 0.55686F, 0.24706F},
    {0.20392F, 0.69412F, 0.00000F},
    {0.67451F, 0.77647F, 0.00000F},
    {0.96078F, 0.83922F, 0.71765F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
