#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LINEARL_11 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.01569F, 0.01569F},
    {0.18039F, 0.07843F, 0.17647F},
    {0.15686F, 0.14902F, 0.47059F},
    {0.09804F, 0.27843F, 0.53333F},
    {0.00000F, 0.42353F, 0.39608F},
    {0.00000F, 0.55686F, 0.24706F},
    {0.07843F, 0.67059F, 0.00000F},
    {0.44706F, 0.75686F, 0.00000F},
    {0.81961F, 0.79608F, 0.34118F},
    {0.97255F, 0.87451F, 0.80000F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
