#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LINEARL_14 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.01569F, 0.01569F},
    {0.15686F, 0.06667F, 0.13725F},
    {0.17647F, 0.10588F, 0.36078F},
    {0.11765F, 0.20000F, 0.48235F},
    {0.08235F, 0.29020F, 0.52157F},
    {0.00000F, 0.40392F, 0.41961F},
    {0.00000F, 0.50588F, 0.30980F},
    {0.00000F, 0.60392F, 0.20392F},
    {0.17647F, 0.68627F, 0.00000F},
    {0.41569F, 0.75686F, 0.00000F},
    {0.74510F, 0.78824F, 0.00000F},
    {0.90980F, 0.82353F, 0.60784F},
    {0.96863F, 0.90196F, 0.84706F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
