#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LINEARL_15 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.01569F, 0.01569F},
    {0.14902F, 0.05882F, 0.12941F},
    {0.17647F, 0.09804F, 0.32941F},
    {0.12941F, 0.18039F, 0.47059F},
    {0.10588F, 0.25882F, 0.53333F},
    {0.01569F, 0.36863F, 0.44706F},
    {0.00000F, 0.46275F, 0.36078F},
    {0.00000F, 0.55686F, 0.24706F},
    {0.00000F, 0.64706F, 0.15294F},
    {0.25882F, 0.71373F, 0.00000F},
    {0.52941F, 0.76471F, 0.00000F},
    {0.78824F, 0.78824F, 0.09412F},
    {0.93333F, 0.83137F, 0.65882F},
    {0.96863F, 0.90980F, 0.86275F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
