#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LINEARL_18 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.01569F, 0.01569F},
    {0.13725F, 0.05490F, 0.12157F},
    {0.17647F, 0.08627F, 0.25098F},
    {0.17255F, 0.12157F, 0.42745F},
    {0.11373F, 0.20392F, 0.48235F},
    {0.10588F, 0.27059F, 0.54118F},
    {0.01569F, 0.36078F, 0.45098F},
    {0.00000F, 0.43922F, 0.38431F},
    {0.00000F, 0.51765F, 0.29412F},
    {0.00000F, 0.59216F, 0.21569F},
    {0.00000F, 0.66667F, 0.09020F},
    {0.26667F, 0.71765F, 0.00000F},
    {0.49020F, 0.76078F, 0.00000F},
    {0.72941F, 0.78431F, 0.00000F},
    {0.86667F, 0.81176F, 0.49804F},
    {0.97255F, 0.84706F, 0.74118F},
    {0.96863F, 0.92549F, 0.89804F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
