#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LISBON_4 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.89804F, 1.00000F},
    {0.11765F, 0.26275F, 0.40784F},
    {0.34118F, 0.31765F, 0.20392F},
    {1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
