#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LISBON_14 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.89804F, 1.00000F},
    {0.69020F, 0.74510F, 0.87451F},
    {0.49412F, 0.60392F, 0.75686F},
    {0.29804F, 0.45098F, 0.62745F},
    {0.15294F, 0.30980F, 0.47059F},
    {0.08235F, 0.18824F, 0.29412F},
    {0.07059F, 0.10196F, 0.14118F},
    {0.12549F, 0.12157F, 0.09412F},
    {0.24706F, 0.23529F, 0.14902F},
    {0.39216F, 0.36863F, 0.23529F},
    {0.53725F, 0.50588F, 0.32549F},
    {0.70196F, 0.67059F, 0.46667F},
    {0.85098F, 0.83137F, 0.64314F},
    {1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
