#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LISBON_20 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.89804F, 1.00000F},
    {0.76471F, 0.80000F, 0.91765F},
    {0.61961F, 0.69412F, 0.83137F},
    {0.48627F, 0.59608F, 0.75294F},
    {0.34902F, 0.49020F, 0.66275F},
    {0.22745F, 0.39216F, 0.56863F},
    {0.13333F, 0.29020F, 0.44314F},
    {0.09020F, 0.21176F, 0.32549F},
    {0.07059F, 0.14118F, 0.21569F},
    {0.07451F, 0.09804F, 0.12549F},
    {0.10980F, 0.10980F, 0.09020F},
    {0.18824F, 0.17647F, 0.11765F},
    {0.27451F, 0.25882F, 0.16471F},
    {0.36863F, 0.34510F, 0.21961F},
    {0.47451F, 0.44706F, 0.28627F},
    {0.58039F, 0.54510F, 0.35686F},
    {0.69412F, 0.66275F, 0.45882F},
    {0.79608F, 0.77255F, 0.57647F},
    {0.90196F, 0.89020F, 0.71373F},
    {1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
