#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LISBON_9 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.89804F, 1.00000F},
    {0.56471F, 0.65490F, 0.80000F},
    {0.25490F, 0.41569F, 0.59216F},
    {0.08627F, 0.20000F, 0.30980F},
    {0.09020F, 0.09804F, 0.09804F},
    {0.26275F, 0.24706F, 0.15686F},
    {0.49804F, 0.47059F, 0.29804F},
    {0.75686F, 0.72941F, 0.52941F},
    {1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
