#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LISBON_8 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.89804F, 1.00000F},
    {0.52549F, 0.62745F, 0.77647F},
    {0.18431F, 0.34902F, 0.51765F},
    {0.06667F, 0.13333F, 0.20000F},
    {0.17647F, 0.16863F, 0.10980F},
    {0.42745F, 0.40392F, 0.25490F},
    {0.72549F, 0.69412F, 0.49020F},
    {1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
