#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto LISBON_18 = std::vector<vivid::srgb_t>{
    {0.90196F, 0.89804F, 1.00000F},
    {0.74118F, 0.78431F, 0.90588F},
    {0.58824F, 0.67059F, 0.81176F},
    {0.43529F, 0.55686F, 0.72157F},
    {0.29020F, 0.44706F, 0.61961F},
    {0.16863F, 0.33333F, 0.49804F},
    {0.09804F, 0.23529F, 0.36471F},
    {0.07059F, 0.15294F, 0.23529F},
    {0.07059F, 0.09804F, 0.12941F},
    {0.11765F, 0.11373F, 0.09020F},
    {0.20000F, 0.18824F, 0.12549F},
    {0.30196F, 0.28627F, 0.18039F},
    {0.41176F, 0.38824F, 0.24706F},
    {0.52941F, 0.49804F, 0.32157F},
    {0.65098F, 0.61961F, 0.41569F},
    {0.77255F, 0.74510F, 0.54510F},
    {0.88627F, 0.87059F, 0.69412F},
    {1.00000F, 1.00000F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
