#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MAGENTA_3 = std::vector<vivid::srgb_t>{
    {0.95294F, 0.79608F, 0.82745F},
    {0.79216F, 0.41176F, 0.61569F},
    {0.42353F, 0.12941F, 0.40392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
