#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MAGMA_14 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.05490F, 0.04314F, 0.16863F},
    {0.15294F, 0.07059F, 0.34510F},
    {0.28627F, 0.06275F, 0.47059F},
    {0.40392F, 0.10588F, 0.50196F},
    {0.52549F, 0.15294F, 0.50588F},
    {0.65098F, 0.19216F, 0.49020F},
    {0.77255F, 0.23529F, 0.45490F},
    {0.89020F, 0.30588F, 0.39608F},
    {0.96471F, 0.42353F, 0.36078F},
    {0.98824F, 0.56471F, 0.39608F},
    {0.99608F, 0.71373F, 0.48627F},
    {0.99608F, 0.84706F, 0.60392F},
    {0.98824F, 0.99216F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
