#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MAGMA_10 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.09412F, 0.05882F, 0.23922F},
    {0.27059F, 0.06275F, 0.46667F},
    {0.44706F, 0.12157F, 0.50588F},
    {0.61961F, 0.18431F, 0.49804F},
    {0.80392F, 0.25098F, 0.44314F},
    {0.94510F, 0.37647F, 0.36471F},
    {0.99216F, 0.58039F, 0.40392F},
    {0.99608F, 0.79216F, 0.55294F},
    {0.98824F, 0.99216F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
