#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MAGMA_8 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.13333F, 0.06667F, 0.31373F},
    {0.37255F, 0.09412F, 0.49804F},
    {0.59608F, 0.17647F, 0.50196F},
    {0.82745F, 0.26275F, 0.43137F},
    {0.97255F, 0.46275F, 0.36078F},
    {0.99608F, 0.73333F, 0.50588F},
    {0.98824F, 0.99216F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
