#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MAGMA_20 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.01569F},
    {0.02745F, 0.02353F, 0.10980F},
    {0.08627F, 0.05882F, 0.23137F},
    {0.16078F, 0.06667F, 0.35294F},
    {0.25098F, 0.05882F, 0.45490F},
    {0.33725F, 0.07843F, 0.49020F},
    {0.41961F, 0.11373F, 0.50588F},
    {0.50196F, 0.14510F, 0.50980F},
    {0.58039F, 0.17255F, 0.50196F},
    {0.67059F, 0.20000F, 0.48627F},
    {0.75294F, 0.22745F, 0.46275F},
    {0.83922F, 0.27059F, 0.42353F},
    {0.90980F, 0.32549F, 0.38431F},
    {0.95686F, 0.40392F, 0.36078F},
    {0.98039F, 0.50588F, 0.37255F},
    {0.99216F, 0.60392F, 0.41569F},
    {0.99608F, 0.70588F, 0.48235F},
    {0.99608F, 0.80000F, 0.56078F},
    {0.99216F, 0.89804F, 0.65490F},
    {0.98824F, 0.99216F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
