#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MARGOT3_4 = std::vector<vivid::srgb_t>{
    {0.52941F, 0.63529F, 0.64314F},
    {0.79216F, 0.62745F, 0.39608F},
    {0.83922F, 0.79216F, 0.74902F},
    {0.83922F, 0.62745F, 0.62745F},
};

} // namespace GOOM::COLOR::COLOR_DATA
