#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MARGOT2_4 = std::vector<vivid::srgb_t>{
    {0.46275F, 0.54510F, 0.57647F},
    {0.73725F, 0.14118F, 0.05882F},
    {0.97647F, 0.92549F, 0.77255F},
    {0.83137F, 0.45098F, 0.16078F},
};

} // namespace GOOM::COLOR::COLOR_DATA
