#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MATTER_19 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92941F, 0.69020F},
    {0.98824F, 0.85490F, 0.61569F},
    {0.98039F, 0.77647F, 0.54902F},
    {0.96863F, 0.70196F, 0.48627F},
    {0.95686F, 0.62353F, 0.42745F},
    {0.94118F, 0.54510F, 0.38039F},
    {0.92157F, 0.47059F, 0.34510F},
    {0.89412F, 0.40000F, 0.32549F},
    {0.85882F, 0.32941F, 0.32549F},
    {0.80784F, 0.26275F, 0.33725F},
    {0.75294F, 0.21176F, 0.35686F},
    {0.69020F, 0.17255F, 0.37255F},
    {0.62353F, 0.14118F, 0.38431F},
    {0.55294F, 0.11765F, 0.38824F},
    {0.47843F, 0.10588F, 0.38431F},
    {0.40392F, 0.09804F, 0.36471F},
    {0.32549F, 0.08627F, 0.32941F},
    {0.25490F, 0.07451F, 0.29020F},
    {0.18431F, 0.05882F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
