#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MATTER_3 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92941F, 0.69020F},
    {0.80784F, 0.26275F, 0.33725F},
    {0.18431F, 0.05882F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
