#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MATTER_15 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92941F, 0.69020F},
    {0.98431F, 0.83137F, 0.59608F},
    {0.97255F, 0.73333F, 0.51373F},
    {0.95686F, 0.63137F, 0.43529F},
    {0.93725F, 0.53725F, 0.37647F},
    {0.90980F, 0.43922F, 0.33725F},
    {0.87059F, 0.34902F, 0.32549F},
    {0.80784F, 0.26275F, 0.33725F},
    {0.73333F, 0.20000F, 0.36078F},
    {0.65098F, 0.15294F, 0.38039F},
    {0.56471F, 0.12157F, 0.38824F},
    {0.47059F, 0.10196F, 0.38039F},
    {0.36863F, 0.09412F, 0.34902F},
    {0.27451F, 0.07843F, 0.30196F},
    {0.18431F, 0.05882F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
