#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MATTER_18 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92941F, 0.69020F},
    {0.98824F, 0.84706F, 0.61176F},
    {0.97647F, 0.76471F, 0.54118F},
    {0.96863F, 0.68627F, 0.47451F},
    {0.95294F, 0.60392F, 0.41569F},
    {0.93333F, 0.52549F, 0.36863F},
    {0.91373F, 0.44706F, 0.33725F},
    {0.87843F, 0.36863F, 0.32549F},
    {0.83529F, 0.29804F, 0.32941F},
    {0.78039F, 0.23922F, 0.34902F},
    {0.71765F, 0.18824F, 0.36863F},
    {0.64706F, 0.14902F, 0.38431F},
    {0.57255F, 0.12157F, 0.38824F},
    {0.49412F, 0.10588F, 0.38431F},
    {0.41569F, 0.09804F, 0.36863F},
    {0.33725F, 0.09020F, 0.33333F},
    {0.25882F, 0.07843F, 0.29412F},
    {0.18431F, 0.05882F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
