#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MATTER_7 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92941F, 0.69020F},
    {0.96863F, 0.70196F, 0.48627F},
    {0.92157F, 0.47059F, 0.34510F},
    {0.80784F, 0.26275F, 0.33725F},
    {0.62353F, 0.14118F, 0.38431F},
    {0.40392F, 0.09804F, 0.36471F},
    {0.18431F, 0.05882F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
