#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MINT_3 = std::vector<vivid::srgb_t>{
    {0.89412F, 0.94510F, 0.88235F},
    {0.38824F, 0.65098F, 0.62745F},
    {0.05098F, 0.34510F, 0.37255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
