#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MOONRISE7_5 = std::vector<vivid::srgb_t>{
    {0.13725F, 0.13725F, 0.33333F},
    {0.38039F, 0.40784F, 0.37647F},
    {0.65490F, 0.35686F, 0.26667F},
    {0.56863F, 0.16863F, 0.16078F},
    {1.00000F, 0.89020F, 0.56078F},
};

} // namespace GOOM::COLOR::COLOR_DATA
