#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto MOONRISE5_6 = std::vector<vivid::srgb_t>{
    {0.87451F, 0.54902F, 0.56471F},
    {0.84706F, 0.82353F, 0.55686F},
    {0.96078F, 0.74510F, 0.14510F},
    {0.23922F, 0.29020F, 0.10980F},
    {0.81961F, 0.18824F, 0.37647F},
    {0.65882F, 0.41961F, 0.29804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
