#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_12 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.14118F, 0.37647F, 0.52157F},
    {0.23922F, 0.41961F, 0.50980F},
    {0.35686F, 0.48235F, 0.52941F},
    {0.47451F, 0.55294F, 0.56471F},
    {0.58431F, 0.61961F, 0.59216F},
    {0.66275F, 0.67451F, 0.59216F},
    {0.71373F, 0.71373F, 0.56471F},
    {0.75294F, 0.75294F, 0.52941F},
    {0.80784F, 0.80784F, 0.51373F},
    {0.90196F, 0.90196F, 0.57647F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
