#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_14 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.12941F, 0.37255F, 0.52549F},
    {0.20784F, 0.40392F, 0.50980F},
    {0.30196F, 0.45098F, 0.51765F},
    {0.40000F, 0.50588F, 0.54118F},
    {0.50196F, 0.56863F, 0.57255F},
    {0.59216F, 0.62353F, 0.59216F},
    {0.65882F, 0.67059F, 0.59216F},
    {0.70588F, 0.70588F, 0.57255F},
    {0.74118F, 0.73725F, 0.54118F},
    {0.77255F, 0.77255F, 0.51765F},
    {0.83137F, 0.83137F, 0.52549F},
    {0.91373F, 0.91373F, 0.59216F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
