#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_17 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.10980F, 0.36863F, 0.52941F},
    {0.17647F, 0.39216F, 0.51373F},
    {0.24706F, 0.42353F, 0.50980F},
    {0.32549F, 0.46667F, 0.52157F},
    {0.40784F, 0.51373F, 0.54510F},
    {0.49020F, 0.56078F, 0.56863F},
    {0.56863F, 0.60784F, 0.58824F},
    {0.63137F, 0.65098F, 0.59608F},
    {0.67451F, 0.68235F, 0.58824F},
    {0.70980F, 0.70980F, 0.56863F},
    {0.73725F, 0.73333F, 0.54510F},
    {0.76471F, 0.76078F, 0.52157F},
    {0.80392F, 0.80000F, 0.51373F},
    {0.86275F, 0.85882F, 0.54118F},
    {0.93333F, 0.93333F, 0.61176F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
