#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_7 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.21961F, 0.41176F, 0.50980F},
    {0.43529F, 0.52941F, 0.55294F},
    {0.63137F, 0.65098F, 0.59608F},
    {0.72941F, 0.72549F, 0.55294F},
    {0.81961F, 0.81569F, 0.51765F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
