#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_16 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.11765F, 0.36863F, 0.52549F},
    {0.18431F, 0.39608F, 0.51373F},
    {0.26275F, 0.43137F, 0.50980F},
    {0.34510F, 0.47843F, 0.52549F},
    {0.43529F, 0.52941F, 0.55294F},
    {0.52157F, 0.58039F, 0.57647F},
    {0.59608F, 0.62745F, 0.59216F},
    {0.65490F, 0.66667F, 0.59216F},
    {0.69804F, 0.69804F, 0.57647F},
    {0.72941F, 0.72549F, 0.55294F},
    {0.75686F, 0.75686F, 0.52941F},
    {0.79216F, 0.79216F, 0.51373F},
    {0.85098F, 0.85098F, 0.53333F},
    {0.92941F, 0.92941F, 0.60392F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
