#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_18 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.10588F, 0.36863F, 0.52941F},
    {0.16863F, 0.38824F, 0.51373F},
    {0.23529F, 0.41569F, 0.50980F},
    {0.30588F, 0.45490F, 0.51765F},
    {0.38431F, 0.49804F, 0.53725F},
    {0.46275F, 0.54510F, 0.56078F},
    {0.53725F, 0.58824F, 0.58039F},
    {0.60000F, 0.62745F, 0.59216F},
    {0.65098F, 0.66667F, 0.59216F},
    {0.69020F, 0.69412F, 0.58039F},
    {0.71765F, 0.71765F, 0.56078F},
    {0.74510F, 0.74118F, 0.53725F},
    {0.77255F, 0.76863F, 0.51765F},
    {0.81176F, 0.81176F, 0.51765F},
    {0.87059F, 0.87059F, 0.54902F},
    {0.93725F, 0.93725F, 0.61569F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
