#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_19 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.10196F, 0.36471F, 0.52941F},
    {0.16078F, 0.38431F, 0.51765F},
    {0.21961F, 0.41176F, 0.50980F},
    {0.29020F, 0.44706F, 0.51373F},
    {0.36078F, 0.48627F, 0.52941F},
    {0.43529F, 0.52941F, 0.55294F},
    {0.50588F, 0.56863F, 0.57255F},
    {0.57255F, 0.61176F, 0.58824F},
    {0.63137F, 0.65098F, 0.59608F},
    {0.67059F, 0.67843F, 0.58824F},
    {0.70196F, 0.70588F, 0.57255F},
    {0.72941F, 0.72549F, 0.55294F},
    {0.75294F, 0.74902F, 0.53333F},
    {0.78039F, 0.77647F, 0.51765F},
    {0.81961F, 0.81569F, 0.51765F},
    {0.87843F, 0.87843F, 0.55686F},
    {0.94118F, 0.94118F, 0.61961F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
