#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto NUUK_8 = std::vector<vivid::srgb_t>{
    {0.01961F, 0.34902F, 0.54902F},
    {0.19608F, 0.40000F, 0.50980F},
    {0.37255F, 0.49020F, 0.53333F},
    {0.55294F, 0.60000F, 0.58824F},
    {0.68235F, 0.68627F, 0.58431F},
    {0.74902F, 0.74510F, 0.53333F},
    {0.84314F, 0.84314F, 0.52941F},
    {0.99608F, 0.99608F, 0.69804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
