#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OLERON_18 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.14902F, 0.34902F},
    {0.19216F, 0.23922F, 0.43922F},
    {0.28627F, 0.33333F, 0.53333F},
    {0.38431F, 0.43529F, 0.63529F},
    {0.48627F, 0.53725F, 0.73725F},
    {0.59608F, 0.64314F, 0.84314F},
    {0.69804F, 0.74902F, 0.93333F},
    {0.78431F, 0.83529F, 0.97255F},
    {0.86275F, 0.91373F, 0.99216F},
    {0.17255F, 0.31765F, 0.00000F},
    {0.30196F, 0.36078F, 0.00392F},
    {0.43137F, 0.41569F, 0.07843F},
    {0.56471F, 0.49804F, 0.20784F},
    {0.69412F, 0.58431F, 0.34118F},
    {0.82745F, 0.68627F, 0.47843F},
    {0.93333F, 0.79608F, 0.62353F},
    {0.97255F, 0.89412F, 0.76471F},
    {0.99216F, 0.99216F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
