#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OLERON_19 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.14902F, 0.34902F},
    {0.18431F, 0.23137F, 0.43529F},
    {0.27059F, 0.32157F, 0.52157F},
    {0.36471F, 0.41176F, 0.61176F},
    {0.46667F, 0.51765F, 0.71765F},
    {0.56471F, 0.61569F, 0.81569F},
    {0.66667F, 0.71765F, 0.90980F},
    {0.75294F, 0.80392F, 0.96078F},
    {0.82745F, 0.87843F, 0.98039F},
    {0.10196F, 0.29804F, 0.00000F},
    {0.23529F, 0.33725F, 0.00000F},
    {0.35294F, 0.37647F, 0.01961F},
    {0.47843F, 0.44314F, 0.12157F},
    {0.60000F, 0.51765F, 0.24314F},
    {0.71765F, 0.60392F, 0.36863F},
    {0.84314F, 0.70196F, 0.49804F},
    {0.94510F, 0.80784F, 0.64314F},
    {0.97255F, 0.90196F, 0.77255F},
    {0.99216F, 0.99216F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
