#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OLERON_14 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.14902F, 0.34902F},
    {0.22353F, 0.27059F, 0.47059F},
    {0.34510F, 0.39216F, 0.59216F},
    {0.47843F, 0.52941F, 0.72941F},
    {0.61569F, 0.66667F, 0.86275F},
    {0.74902F, 0.79608F, 0.95686F},
    {0.85490F, 0.90196F, 0.98824F},
    {0.19216F, 0.32549F, 0.00000F},
    {0.36078F, 0.38039F, 0.02353F},
    {0.54118F, 0.48235F, 0.18039F},
    {0.70196F, 0.59216F, 0.34902F},
    {0.87843F, 0.72941F, 0.53725F},
    {0.96471F, 0.86275F, 0.71765F},
    {0.99216F, 0.99216F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
