#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OLERON_7 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.14902F, 0.34902F},
    {0.36471F, 0.41176F, 0.61176F},
    {0.66667F, 0.71765F, 0.90980F},
    {0.10196F, 0.29804F, 0.00000F},
    {0.47843F, 0.44314F, 0.12157F},
    {0.84314F, 0.70196F, 0.49804F},
    {0.99216F, 0.99216F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
