#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ORANGES_8 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96078F, 0.92157F},
    {0.99608F, 0.90196F, 0.80784F},
    {0.99216F, 0.81569F, 0.63529F},
    {0.99216F, 0.68235F, 0.41961F},
    {0.99216F, 0.55294F, 0.23529F},
    {0.94510F, 0.41176F, 0.07451F},
    {0.85098F, 0.28235F, 0.00392F},
    {0.54902F, 0.17647F, 0.01569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
