#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ORANGES_4 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92941F, 0.87059F},
    {0.99216F, 0.74510F, 0.52157F},
    {0.99216F, 0.55294F, 0.23529F},
    {0.85098F, 0.27843F, 0.00392F},
};

} // namespace GOOM::COLOR::COLOR_DATA
