#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ORANGES_3 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.90196F, 0.80784F},
    {0.99216F, 0.68235F, 0.41961F},
    {0.90196F, 0.33333F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
