#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ORRD_3 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.90980F, 0.78431F},
    {0.99216F, 0.73333F, 0.51765F},
    {0.89020F, 0.29020F, 0.20000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
