#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ORRD_5 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.94118F, 0.85098F},
    {0.99216F, 0.80000F, 0.54118F},
    {0.98824F, 0.55294F, 0.34902F},
    {0.89020F, 0.29020F, 0.20000F},
    {0.70196F, 0.00000F, 0.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
