#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ORYEL_4 = std::vector<vivid::srgb_t>{
    {0.92549F, 0.85490F, 0.60392F},
    {0.95294F, 0.67843F, 0.41569F},
    {0.97647F, 0.48235F, 0.34118F},
    {0.93333F, 0.30196F, 0.35294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
