#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OSLO_10 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.00392F, 0.00392F},
    {0.05098F, 0.10588F, 0.16078F},
    {0.07451F, 0.19608F, 0.31765F},
    {0.12157F, 0.29804F, 0.48235F},
    {0.21961F, 0.41176F, 0.65882F},
    {0.39608F, 0.54118F, 0.78039F},
    {0.53725F, 0.62745F, 0.79216F},
    {0.66667F, 0.71373F, 0.79216F},
    {0.83137F, 0.83922F, 0.85882F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
