#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OSLO_18 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.00392F, 0.00392F},
    {0.03529F, 0.06667F, 0.09804F},
    {0.05490F, 0.10980F, 0.17255F},
    {0.06275F, 0.15686F, 0.25098F},
    {0.07843F, 0.20784F, 0.33333F},
    {0.10196F, 0.26275F, 0.42353F},
    {0.13333F, 0.31765F, 0.51373F},
    {0.18431F, 0.37647F, 0.60784F},
    {0.26275F, 0.44314F, 0.69804F},
    {0.35686F, 0.51373F, 0.76471F},
    {0.43922F, 0.56863F, 0.78824F},
    {0.51373F, 0.61569F, 0.79216F},
    {0.58039F, 0.65882F, 0.78824F},
    {0.65490F, 0.70588F, 0.79216F},
    {0.72941F, 0.76078F, 0.80784F},
    {0.81961F, 0.82745F, 0.85098F},
    {0.90980F, 0.91373F, 0.91765F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
