#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OSLO_11 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.00392F, 0.00392F},
    {0.05098F, 0.09804F, 0.15294F},
    {0.07059F, 0.17647F, 0.28235F},
    {0.10196F, 0.26667F, 0.42745F},
    {0.17255F, 0.36471F, 0.58824F},
    {0.31373F, 0.48235F, 0.73725F},
    {0.45490F, 0.58039F, 0.78824F},
    {0.57255F, 0.65098F, 0.78824F},
    {0.69804F, 0.73725F, 0.80000F},
    {0.84706F, 0.85490F, 0.87059F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
