#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OSLO_8 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.00392F, 0.00392F},
    {0.05882F, 0.12941F, 0.20000F},
    {0.09804F, 0.25490F, 0.41176F},
    {0.20000F, 0.39216F, 0.63137F},
    {0.41961F, 0.55686F, 0.78431F},
    {0.59216F, 0.66275F, 0.78824F},
    {0.78039F, 0.80000F, 0.82745F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
