#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OSLO_20 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.00392F, 0.00392F},
    {0.03137F, 0.05882F, 0.09020F},
    {0.05098F, 0.10196F, 0.15686F},
    {0.05882F, 0.14118F, 0.22353F},
    {0.07059F, 0.18824F, 0.29804F},
    {0.09020F, 0.23137F, 0.37647F},
    {0.11373F, 0.28235F, 0.45882F},
    {0.14510F, 0.33333F, 0.53725F},
    {0.19216F, 0.38431F, 0.61961F},
    {0.26667F, 0.44706F, 0.70196F},
    {0.34902F, 0.50980F, 0.76078F},
    {0.43137F, 0.56471F, 0.78431F},
    {0.49412F, 0.60392F, 0.79216F},
    {0.55294F, 0.63922F, 0.78824F},
    {0.61961F, 0.68235F, 0.78824F},
    {0.68235F, 0.72549F, 0.79608F},
    {0.76078F, 0.78039F, 0.81961F},
    {0.83529F, 0.84706F, 0.86275F},
    {0.92157F, 0.92549F, 0.92941F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
