#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OSLO_7 = std::vector<vivid::srgb_t>{
    {0.00392F, 0.00392F, 0.00392F},
    {0.06275F, 0.14902F, 0.23529F},
    {0.12157F, 0.29804F, 0.48235F},
    {0.31373F, 0.48235F, 0.73725F},
    {0.53725F, 0.62745F, 0.79216F},
    {0.74118F, 0.76863F, 0.81176F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
