#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OXY_19 = std::vector<vivid::srgb_t>{
    {0.25098F, 0.01961F, 0.01961F},
    {0.34118F, 0.02745F, 0.04314F},
    {0.43529F, 0.02353F, 0.05882F},
    {0.52157F, 0.03922F, 0.04314F},
    {0.33333F, 0.32941F, 0.32941F},
    {0.38431F, 0.38431F, 0.38039F},
    {0.43529F, 0.43529F, 0.43137F},
    {0.49020F, 0.49020F, 0.48627F},
    {0.54510F, 0.54510F, 0.54118F},
    {0.60784F, 0.60392F, 0.60392F},
    {0.66667F, 0.66667F, 0.66275F},
    {0.72941F, 0.72549F, 0.72157F},
    {0.79608F, 0.79216F, 0.78824F},
    {0.85882F, 0.85882F, 0.85490F},
    {0.93333F, 0.93333F, 0.92549F},
    {0.92549F, 0.96078F, 0.30588F},
    {0.90980F, 0.86275F, 0.18824F},
    {0.89020F, 0.76863F, 0.13725F},
    {0.86667F, 0.68627F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
