#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OXY_9 = std::vector<vivid::srgb_t>{
    {0.25098F, 0.01961F, 0.01961F},
    {0.46275F, 0.01961F, 0.05882F},
    {0.36078F, 0.35686F, 0.35686F},
    {0.47843F, 0.47843F, 0.47451F},
    {0.60784F, 0.60392F, 0.60392F},
    {0.74118F, 0.74118F, 0.73725F},
    {0.89412F, 0.89412F, 0.89020F},
    {0.91373F, 0.89020F, 0.20392F},
    {0.86667F, 0.68627F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
