#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto OXY_8 = std::vector<vivid::srgb_t>{
    {0.25098F, 0.01961F, 0.01961F},
    {0.49020F, 0.01961F, 0.05490F},
    {0.39216F, 0.38824F, 0.38824F},
    {0.52941F, 0.52941F, 0.52549F},
    {0.68627F, 0.68235F, 0.68235F},
    {0.85098F, 0.85098F, 0.84706F},
    {0.91765F, 0.91765F, 0.23137F},
    {0.86667F, 0.68627F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
