#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PAIRED_9 = std::vector<vivid::srgb_t>{
    {0.65098F, 0.80784F, 0.89020F},
    {0.12157F, 0.47059F, 0.70588F},
    {0.69804F, 0.87451F, 0.54118F},
    {0.20000F, 0.62745F, 0.17255F},
    {0.98431F, 0.60392F, 0.60000F},
    {0.89020F, 0.10196F, 0.10980F},
    {0.99216F, 0.74902F, 0.43529F},
    {1.00000F, 0.49804F, 0.00000F},
    {0.79216F, 0.69804F, 0.83922F},
};

} // namespace GOOM::COLOR::COLOR_DATA
