#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PASTEL_4 = std::vector<vivid::srgb_t>{
    {0.40000F, 0.77255F, 0.80000F},
    {0.96471F, 0.81176F, 0.44314F},
    {0.97255F, 0.61176F, 0.45490F},
    {0.86275F, 0.69020F, 0.94902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
