#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PASTEL2_6 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.88627F, 0.80392F},
    {0.99216F, 0.80392F, 0.67451F},
    {0.79608F, 0.83529F, 0.90980F},
    {0.95686F, 0.79216F, 0.89412F},
    {0.90196F, 0.96078F, 0.78824F},
    {1.00000F, 0.94902F, 0.68235F},
};

} // namespace GOOM::COLOR::COLOR_DATA
