#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PEACH_4 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.87843F, 0.77255F},
    {0.97255F, 0.70980F, 0.54510F},
    {0.94902F, 0.52157F, 0.36471F},
    {0.92157F, 0.29020F, 0.25098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
