#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PERCEPTUAL_RAINBOW_16 = std::vector<vivid::srgb_t>{
    {0.52941F, 0.23137F, 0.38039F},
    {0.56078F, 0.25098F, 0.49804F},
    {0.56078F, 0.28235F, 0.61569F},
    {0.52941F, 0.33333F, 0.72549F},
    {0.47451F, 0.40000F, 0.81176F},
    {0.40392F, 0.48235F, 0.86275F},
    {0.32941F, 0.57255F, 0.87451F},
    {0.27059F, 0.66667F, 0.84314F},
    {0.23137F, 0.75294F, 0.77255F},
    {0.23529F, 0.82353F, 0.67451F},
    {0.27843F, 0.87451F, 0.56863F},
    {0.36471F, 0.89804F, 0.47059F},
    {0.48627F, 0.90588F, 0.40392F},
    {0.63137F, 0.89020F, 0.37255F},
    {0.77647F, 0.86275F, 0.39216F},
    {0.91373F, 0.83529F, 0.45882F},
};

} // namespace GOOM::COLOR::COLOR_DATA
