#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PHASE_13 = std::vector<vivid::srgb_t>{
    {0.65882F, 0.47059F, 0.05098F},
    {0.76863F, 0.38431F, 0.18824F},
    {0.84314F, 0.28627F, 0.34118F},
    {0.87451F, 0.16471F, 0.57647F},
    {0.81569F, 0.18431F, 0.81569F},
    {0.68235F, 0.32157F, 0.94118F},
    {0.49020F, 0.45098F, 0.94118F},
    {0.27059F, 0.53725F, 0.82745F},
    {0.11765F, 0.57647F, 0.65882F},
    {0.04706F, 0.59608F, 0.49412F},
    {0.19216F, 0.60000F, 0.27451F},
    {0.49020F, 0.54510F, 0.06275F},
    {0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
