#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PHASE_16 = std::vector<vivid::srgb_t>{
    {0.65882F, 0.47059F, 0.05098F},
    {0.74902F, 0.40392F, 0.16471F},
    {0.81569F, 0.32549F, 0.27843F},
    {0.86275F, 0.23529F, 0.42745F},
    {0.87059F, 0.15294F, 0.62745F},
    {0.81569F, 0.18431F, 0.81569F},
    {0.71373F, 0.29412F, 0.92941F},
    {0.57647F, 0.40000F, 0.95686F},
    {0.40784F, 0.48627F, 0.90980F},
    {0.23137F, 0.54902F, 0.79608F},
    {0.11765F, 0.57647F, 0.65882F},
    {0.05882F, 0.59216F, 0.52549F},
    {0.09804F, 0.60392F, 0.36863F},
    {0.32549F, 0.58824F, 0.16078F},
    {0.52549F, 0.53333F, 0.05490F},
    {0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
