#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PHASE_9 = std::vector<vivid::srgb_t>{
    {0.65882F, 0.47059F, 0.05098F},
    {0.81176F, 0.33725F, 0.26275F},
    {0.87451F, 0.16471F, 0.57647F},
    {0.75294F, 0.25490F, 0.89804F},
    {0.49020F, 0.45098F, 0.94118F},
    {0.18039F, 0.56078F, 0.74510F},
    {0.04706F, 0.59608F, 0.49412F},
    {0.35294F, 0.58039F, 0.13725F},
    {0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
