#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PHASE_20 = std::vector<vivid::srgb_t>{
    {0.65882F, 0.47059F, 0.05098F},
    {0.72941F, 0.41961F, 0.13725F},
    {0.79216F, 0.36078F, 0.22745F},
    {0.83529F, 0.29412F, 0.32549F},
    {0.86667F, 0.21961F, 0.46275F},
    {0.87059F, 0.15686F, 0.61569F},
    {0.83137F, 0.16471F, 0.78039F},
    {0.76471F, 0.24314F, 0.88627F},
    {0.67451F, 0.32941F, 0.94510F},
    {0.56078F, 0.41176F, 0.95686F},
    {0.43137F, 0.47843F, 0.92157F},
    {0.27843F, 0.53333F, 0.83529F},
    {0.16471F, 0.56471F, 0.72941F},
    {0.10196F, 0.58039F, 0.62745F},
    {0.05490F, 0.59608F, 0.51765F},
    {0.07451F, 0.60392F, 0.40000F},
    {0.23529F, 0.60000F, 0.23529F},
    {0.41961F, 0.56471F, 0.09020F},
    {0.56078F, 0.51765F, 0.05098F},
    {0.65882F, 0.47059F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
