#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PINKYL_3 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.96471F, 0.70980F},
    {1.00000F, 0.65098F, 0.47451F},
    {0.88235F, 0.32549F, 0.51373F},
};

} // namespace GOOM::COLOR::COLOR_DATA
