#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PIYG_10 = std::vector<vivid::srgb_t>{
    {0.55686F, 0.00392F, 0.32157F},
    {0.77255F, 0.10588F, 0.49020F},
    {0.87059F, 0.46667F, 0.68235F},
    {0.94510F, 0.71373F, 0.85490F},
    {0.99216F, 0.87843F, 0.93725F},
    {0.90196F, 0.96078F, 0.81569F},
    {0.72157F, 0.88235F, 0.52549F},
    {0.49804F, 0.73725F, 0.25490F},
    {0.30196F, 0.57255F, 0.12941F},
    {0.15294F, 0.39216F, 0.09804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
