#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PIYG_7 = std::vector<vivid::srgb_t>{
    {0.77255F, 0.10588F, 0.49020F},
    {0.91373F, 0.63922F, 0.78824F},
    {0.99216F, 0.87843F, 0.93725F},
    {0.96863F, 0.96863F, 0.96863F},
    {0.90196F, 0.96078F, 0.81569F},
    {0.63137F, 0.84314F, 0.41569F},
    {0.30196F, 0.57255F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
