#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PLASMA_14 = std::vector<vivid::srgb_t>{
    {0.05098F, 0.03137F, 0.52941F},
    {0.21961F, 0.01569F, 0.60392F},
    {0.34510F, 0.00392F, 0.64314F},
    {0.46667F, 0.00392F, 0.65882F},
    {0.57255F, 0.05882F, 0.63922F},
    {0.67451F, 0.14902F, 0.58039F},
    {0.76078F, 0.23529F, 0.50588F},
    {0.83137F, 0.32157F, 0.43922F},
    {0.89412F, 0.41176F, 0.36863F},
    {0.94510F, 0.50588F, 0.30196F},
    {0.98039F, 0.60784F, 0.23922F},
    {0.99608F, 0.72157F, 0.17255F},
    {0.98431F, 0.84314F, 0.14118F},
    {0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
