#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PLASMA_10 = std::vector<vivid::srgb_t>{
    {0.05098F, 0.03137F, 0.52941F},
    {0.27451F, 0.01176F, 0.62353F},
    {0.45490F, 0.00392F, 0.65882F},
    {0.61176F, 0.09020F, 0.61961F},
    {0.74118F, 0.21569F, 0.52549F},
    {0.84706F, 0.34118F, 0.41961F},
    {0.92941F, 0.47451F, 0.32549F},
    {0.98039F, 0.61961F, 0.23137F},
    {0.99216F, 0.79216F, 0.14902F},
    {0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
