#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PLASMA_18 = std::vector<vivid::srgb_t>{
    {0.05098F, 0.03137F, 0.52941F},
    {0.18431F, 0.01961F, 0.58824F},
    {0.28627F, 0.01176F, 0.62745F},
    {0.38039F, 0.00000F, 0.65490F},
    {0.47059F, 0.00392F, 0.65882F},
    {0.55686F, 0.04706F, 0.64314F},
    {0.63529F, 0.11373F, 0.60392F},
    {0.70588F, 0.18039F, 0.55294F},
    {0.76863F, 0.24314F, 0.49804F},
    {0.82353F, 0.30980F, 0.44314F},
    {0.87059F, 0.38039F, 0.39216F},
    {0.91373F, 0.44706F, 0.34118F},
    {0.95294F, 0.52157F, 0.29412F},
    {0.97647F, 0.60392F, 0.24314F},
    {0.99216F, 0.68627F, 0.19216F},
    {0.99216F, 0.77647F, 0.15294F},
    {0.97255F, 0.87451F, 0.14510F},
    {0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
