#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PLASMA_17 = std::vector<vivid::srgb_t>{
    {0.05098F, 0.03137F, 0.52941F},
    {0.19216F, 0.01961F, 0.59216F},
    {0.29804F, 0.00784F, 0.63137F},
    {0.40000F, 0.00000F, 0.65490F},
    {0.49412F, 0.01176F, 0.65882F},
    {0.58431F, 0.06667F, 0.63137F},
    {0.66667F, 0.13725F, 0.58431F},
    {0.73725F, 0.20784F, 0.52941F},
    {0.80000F, 0.27843F, 0.47059F},
    {0.85098F, 0.34510F, 0.41569F},
    {0.89804F, 0.41961F, 0.36471F},
    {0.94118F, 0.49804F, 0.30980F},
    {0.97255F, 0.58039F, 0.25490F},
    {0.99216F, 0.67059F, 0.20000F},
    {0.99216F, 0.76471F, 0.15686F},
    {0.97647F, 0.86667F, 0.14510F},
    {0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
