#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PLASMA_12 = std::vector<vivid::srgb_t>{
    {0.05098F, 0.03137F, 0.52941F},
    {0.24314F, 0.01569F, 0.61176F},
    {0.38824F, 0.00000F, 0.65490F},
    {0.52941F, 0.02745F, 0.65098F},
    {0.65098F, 0.12549F, 0.59608F},
    {0.75294F, 0.22745F, 0.51373F},
    {0.83529F, 0.32941F, 0.43137F},
    {0.90588F, 0.43529F, 0.35294F},
    {0.96078F, 0.54902F, 0.27451F},
    {0.99216F, 0.68235F, 0.19608F},
    {0.98824F, 0.82353F, 0.14510F},
    {0.94118F, 0.97647F, 0.12941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
