#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PRGN_9 = std::vector<vivid::srgb_t>{
    {0.46275F, 0.16471F, 0.51373F},
    {0.60000F, 0.43922F, 0.67059F},
    {0.76078F, 0.64706F, 0.81176F},
    {0.90588F, 0.83137F, 0.90980F},
    {0.96863F, 0.96863F, 0.96863F},
    {0.85098F, 0.94118F, 0.82745F},
    {0.65098F, 0.85882F, 0.62745F},
    {0.35294F, 0.68235F, 0.38039F},
    {0.10588F, 0.47059F, 0.21569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
