#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PRGN_3 = std::vector<vivid::srgb_t>{
    {0.68627F, 0.55294F, 0.76471F},
    {0.96863F, 0.96863F, 0.96863F},
    {0.49804F, 0.74902F, 0.48235F},
};

} // namespace GOOM::COLOR::COLOR_DATA
