#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PRISM_2 = std::vector<vivid::srgb_t>{
    {0.37255F, 0.27451F, 0.56471F},
    {0.11373F, 0.41176F, 0.58824F},
};

} // namespace GOOM::COLOR::COLOR_DATA
