#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PRISM_8 = std::vector<vivid::srgb_t>{
    {0.37255F, 0.27451F, 0.56471F},
    {0.11373F, 0.41176F, 0.58824F},
    {0.21961F, 0.65098F, 0.64706F},
    {0.05882F, 0.52157F, 0.32941F},
    {0.45098F, 0.68627F, 0.28235F},
    {0.92941F, 0.67843F, 0.03137F},
    {0.88235F, 0.48627F, 0.01961F},
    {0.80000F, 0.31373F, 0.24314F},
};

} // namespace GOOM::COLOR::COLOR_DATA
