#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PUOR_6 = std::vector<vivid::srgb_t>{
    {0.70196F, 0.34510F, 0.02353F},
    {0.94510F, 0.63922F, 0.25098F},
    {0.99608F, 0.87843F, 0.71373F},
    {0.84706F, 0.85490F, 0.92157F},
    {0.60000F, 0.55686F, 0.76471F},
    {0.32941F, 0.15294F, 0.53333F},
};

} // namespace GOOM::COLOR::COLOR_DATA
