#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PURP_7 = std::vector<vivid::srgb_t>{
    {0.95294F, 0.87843F, 0.96863F},
    {0.89412F, 0.78039F, 0.94510F},
    {0.81961F, 0.68627F, 0.90980F},
    {0.72549F, 0.59608F, 0.86667F},
    {0.62353F, 0.50980F, 0.80784F},
    {0.50980F, 0.42745F, 0.72941F},
    {0.38824F, 0.34510F, 0.62353F},
};

} // namespace GOOM::COLOR::COLOR_DATA
