#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PURPLEGRAY_6 = std::vector<vivid::srgb_t>{
    {0.48235F, 0.40000F, 0.82353F},
    {0.86275F, 0.37255F, 0.74118F},
    {0.58039F, 0.56863F, 0.48235F},
    {0.60000F, 0.33725F, 0.53333F},
    {0.81569F, 0.59608F, 0.93333F},
    {0.84314F, 0.83529F, 0.77255F},
};

} // namespace GOOM::COLOR::COLOR_DATA
