#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PURPLES_5 = std::vector<vivid::srgb_t>{
    {0.94902F, 0.94118F, 0.96863F},
    {0.79608F, 0.78824F, 0.88627F},
    {0.61961F, 0.60392F, 0.78431F},
    {0.45882F, 0.41961F, 0.69412F},
    {0.32941F, 0.15294F, 0.56078F},
};

} // namespace GOOM::COLOR::COLOR_DATA
