#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PURPOR_7 = std::vector<vivid::srgb_t>{
    {0.97647F, 0.86667F, 0.85490F},
    {0.94902F, 0.72549F, 0.76863F},
    {0.89804F, 0.59216F, 0.72549F},
    {0.80784F, 0.47059F, 0.70196F},
    {0.67843F, 0.37255F, 0.67843F},
    {0.51373F, 0.29412F, 0.62745F},
    {0.34118F, 0.23137F, 0.53333F},
};

} // namespace GOOM::COLOR::COLOR_DATA
