#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PURP_2 = std::vector<vivid::srgb_t>{
    {0.95294F, 0.87843F, 0.96863F},
    {0.38824F, 0.34510F, 0.62353F},
};

} // namespace GOOM::COLOR::COLOR_DATA
