#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto PURPLES_3 = std::vector<vivid::srgb_t>{
    {0.93725F, 0.92941F, 0.96078F},
    {0.73725F, 0.74118F, 0.86275F},
    {0.45882F, 0.41961F, 0.69412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
