#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDBU_5 = std::vector<vivid::srgb_t>{
    {0.79216F, 0.00000F, 0.12549F},
    {0.95686F, 0.64706F, 0.50980F},
    {0.96863F, 0.96863F, 0.96863F},
    {0.57255F, 0.77255F, 0.87059F},
    {0.01961F, 0.44314F, 0.69020F},
};

} // namespace GOOM::COLOR::COLOR_DATA
