#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDBU_3 = std::vector<vivid::srgb_t>{
    {0.93725F, 0.54118F, 0.38431F},
    {0.96863F, 0.96863F, 0.96863F},
    {0.40392F, 0.66275F, 0.81176F},
};

} // namespace GOOM::COLOR::COLOR_DATA
