#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDGY_5 = std::vector<vivid::srgb_t>{
    {0.79216F, 0.00000F, 0.12549F},
    {0.95686F, 0.64706F, 0.50980F},
    {1.00000F, 1.00000F, 1.00000F},
    {0.72941F, 0.72941F, 0.72941F},
    {0.25098F, 0.25098F, 0.25098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
