#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDGY_8 = std::vector<vivid::srgb_t>{
    {0.69804F, 0.09412F, 0.16863F},
    {0.83922F, 0.37647F, 0.30196F},
    {0.95686F, 0.64706F, 0.50980F},
    {0.99216F, 0.85882F, 0.78039F},
    {0.87843F, 0.87843F, 0.87843F},
    {0.72941F, 0.72941F, 0.72941F},
    {0.52941F, 0.52941F, 0.52941F},
    {0.30196F, 0.30196F, 0.30196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
