#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDPU_3 = std::vector<vivid::srgb_t>{
    {0.99216F, 0.87843F, 0.86667F},
    {0.98039F, 0.62353F, 0.70980F},
    {0.77255F, 0.10588F, 0.54118F},
};

} // namespace GOOM::COLOR::COLOR_DATA
