#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDPU_5 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.92157F, 0.88627F},
    {0.98431F, 0.70588F, 0.72549F},
    {0.96863F, 0.40784F, 0.63137F},
    {0.77255F, 0.10588F, 0.54118F},
    {0.47843F, 0.00392F, 0.46667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
