#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDYLBU_11 = std::vector<vivid::srgb_t>{
    {0.64706F, 0.00000F, 0.14902F},
    {0.84314F, 0.18824F, 0.15294F},
    {0.95686F, 0.42745F, 0.26275F},
    {0.99216F, 0.68235F, 0.38039F},
    {0.99608F, 0.87843F, 0.56471F},
    {1.00000F, 1.00000F, 0.74902F},
    {0.87843F, 0.95294F, 0.97255F},
    {0.67059F, 0.85098F, 0.91373F},
    {0.45490F, 0.67843F, 0.81961F},
    {0.27059F, 0.45882F, 0.70588F},
    {0.19216F, 0.21176F, 0.58431F},
};

} // namespace GOOM::COLOR::COLOR_DATA
