#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDYLGN_7 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.18824F, 0.15294F},
    {0.98824F, 0.55294F, 0.34902F},
    {0.99608F, 0.87843F, 0.54510F},
    {1.00000F, 1.00000F, 0.74902F},
    {0.85098F, 0.93725F, 0.54510F},
    {0.56863F, 0.81176F, 0.37647F},
    {0.10196F, 0.59608F, 0.31373F},
};

} // namespace GOOM::COLOR::COLOR_DATA
