#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDYLBU_6 = std::vector<vivid::srgb_t>{
    {0.84314F, 0.18824F, 0.15294F},
    {0.98824F, 0.55294F, 0.34902F},
    {0.99608F, 0.87843F, 0.56471F},
    {0.87843F, 0.95294F, 0.97255F},
    {0.56863F, 0.74902F, 0.85882F},
    {0.27059F, 0.45882F, 0.70588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
