#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RDYLGN_11 = std::vector<vivid::srgb_t>{
    {0.64706F, 0.00000F, 0.14902F},
    {0.84314F, 0.18824F, 0.15294F},
    {0.95686F, 0.42745F, 0.26275F},
    {0.99216F, 0.68235F, 0.38039F},
    {0.99608F, 0.87843F, 0.54510F},
    {1.00000F, 1.00000F, 0.74902F},
    {0.85098F, 0.93725F, 0.54510F},
    {0.65098F, 0.85098F, 0.41569F},
    {0.40000F, 0.74118F, 0.38824F},
    {0.10196F, 0.59608F, 0.31373F},
    {0.00000F, 0.40784F, 0.21569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
