#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto RED_16 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.07451F, 0.04706F, 0.13725F},
    {0.17255F, 0.08627F, 0.25490F},
    {0.28627F, 0.12549F, 0.35294F},
    {0.40784F, 0.16078F, 0.41961F},
    {0.52549F, 0.20784F, 0.46275F},
    {0.63529F, 0.26275F, 0.48627F},
    {0.72549F, 0.32549F, 0.49412F},
    {0.80000F, 0.40000F, 0.50196F},
    {0.84706F, 0.48627F, 0.50980F},
    {0.88235F, 0.58039F, 0.53333F},
    {0.89804F, 0.67451F, 0.57647F},
    {0.90980F, 0.76863F, 0.64314F},
    {0.92549F, 0.85882F, 0.74118F},
    {0.94902F, 0.93333F, 0.85882F},
    {1.00000F, 1.00000F, 1.00000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
