#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto REDOR_4 = std::vector<vivid::srgb_t>{
    {0.96471F, 0.82353F, 0.66275F},
    {0.94510F, 0.61176F, 0.48627F},
    {0.86667F, 0.40784F, 0.42353F},
    {0.69412F, 0.24706F, 0.39216F},
};

} // namespace GOOM::COLOR::COLOR_DATA
