#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto REDS_5 = std::vector<vivid::srgb_t>{
    {0.99608F, 0.89804F, 0.85098F},
    {0.98824F, 0.68235F, 0.56863F},
    {0.98431F, 0.41569F, 0.29020F},
    {0.87059F, 0.17647F, 0.14902F},
    {0.64706F, 0.05882F, 0.08235F},
};

} // namespace GOOM::COLOR::COLOR_DATA
