#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto REDS_9 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96078F, 0.94118F},
    {0.99608F, 0.87843F, 0.82353F},
    {0.98824F, 0.73333F, 0.63137F},
    {0.98824F, 0.57255F, 0.44706F},
    {0.98431F, 0.41569F, 0.29020F},
    {0.93725F, 0.23137F, 0.17255F},
    {0.79608F, 0.09412F, 0.11373F},
    {0.64706F, 0.05882F, 0.08235F},
    {0.40392F, 0.00000F, 0.05098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
