#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ROMA_8 = std::vector<vivid::srgb_t>{
    {0.49804F, 0.09804F, 0.00000F},
    {0.64706F, 0.41176F, 0.12157F},
    {0.79608F, 0.71373F, 0.30196F},
    {0.88235F, 0.91373F, 0.66667F},
    {0.61961F, 0.88235F, 0.84314F},
    {0.31373F, 0.65882F, 0.79608F},
    {0.20392F, 0.41569F, 0.69412F},
    {0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
