#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ROMA_13 = std::vector<vivid::srgb_t>{
    {0.49804F, 0.09804F, 0.00000F},
    {0.58824F, 0.29412F, 0.07059F},
    {0.67059F, 0.45490F, 0.14118F},
    {0.75686F, 0.63529F, 0.23529F},
    {0.85098F, 0.81176F, 0.42745F},
    {0.88627F, 0.90588F, 0.63922F},
    {0.79216F, 0.92157F, 0.78824F},
    {0.58431F, 0.86667F, 0.84314F},
    {0.38039F, 0.74118F, 0.82745F},
    {0.28235F, 0.59608F, 0.77255F},
    {0.22353F, 0.45882F, 0.71373F},
    {0.16863F, 0.32549F, 0.65490F},
    {0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
