#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto ROMA_15 = std::vector<vivid::srgb_t>{
    {0.49804F, 0.09804F, 0.00000F},
    {0.57647F, 0.26667F, 0.06275F},
    {0.64706F, 0.41176F, 0.12157F},
    {0.71765F, 0.56078F, 0.18824F},
    {0.79608F, 0.71373F, 0.30196F},
    {0.87059F, 0.85098F, 0.49412F},
    {0.88235F, 0.91373F, 0.66667F},
    {0.79216F, 0.92157F, 0.78824F},
    {0.61961F, 0.88235F, 0.84314F},
    {0.43137F, 0.78039F, 0.83529F},
    {0.31373F, 0.65882F, 0.79608F},
    {0.25490F, 0.53725F, 0.74510F},
    {0.20392F, 0.41569F, 0.69412F},
    {0.16078F, 0.30588F, 0.64706F},
    {0.10196F, 0.20000F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
