#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SET1_8 = std::vector<vivid::srgb_t>{
    {0.89412F, 0.10196F, 0.10980F},
    {0.21569F, 0.49412F, 0.72157F},
    {0.30196F, 0.68627F, 0.29020F},
    {0.59608F, 0.30588F, 0.63922F},
    {1.00000F, 0.49804F, 0.00000F},
    {1.00000F, 1.00000F, 0.20000F},
    {0.65098F, 0.33725F, 0.15686F},
    {0.96863F, 0.50588F, 0.74902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
