#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SET2_7 = std::vector<vivid::srgb_t>{
    {0.40000F, 0.76078F, 0.64706F},
    {0.98824F, 0.55294F, 0.38431F},
    {0.55294F, 0.62745F, 0.79608F},
    {0.90588F, 0.54118F, 0.76471F},
    {0.65098F, 0.84706F, 0.32941F},
    {1.00000F, 0.85098F, 0.18431F},
    {0.89804F, 0.76863F, 0.58039F},
};

} // namespace GOOM::COLOR::COLOR_DATA
