#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SET3_4 = std::vector<vivid::srgb_t>{
    {0.55294F, 0.82745F, 0.78039F},
    {1.00000F, 1.00000F, 0.70196F},
    {0.74510F, 0.72941F, 0.85490F},
    {0.98431F, 0.50196F, 0.44706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
