#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SET3 = std::vector<vivid::srgb_t>{
    {0.55294F, 0.82745F, 0.78039F},
    {1.00000F, 1.00000F, 0.70196F},
    {0.74510F, 0.72941F, 0.85490F},
    {0.98431F, 0.50196F, 0.44706F},
    {0.50196F, 0.69412F, 0.82745F},
    {0.99216F, 0.70588F, 0.38431F},
    {0.70196F, 0.87059F, 0.41176F},
    {0.98824F, 0.80392F, 0.89804F},
    {0.85098F, 0.85098F, 0.85098F},
    {0.73725F, 0.50196F, 0.74118F},
    {0.80000F, 0.92157F, 0.77255F},
    {1.00000F, 0.92941F, 0.43529F},
};

} // namespace GOOM::COLOR::COLOR_DATA
