#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_11 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.32941F, 0.11765F, 0.13333F},
    {0.45098F, 0.15294F, 0.14118F},
    {0.56078F, 0.20392F, 0.12157F},
    {0.64706F, 0.29020F, 0.09020F},
    {0.71373F, 0.39216F, 0.07451F},
    {0.76863F, 0.49804F, 0.08235F},
    {0.81176F, 0.60784F, 0.11373F},
    {0.84706F, 0.72941F, 0.16471F},
    {0.87059F, 0.85882F, 0.22745F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
