#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_16 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.28235F, 0.10588F, 0.12157F},
    {0.36863F, 0.12941F, 0.14118F},
    {0.45098F, 0.15294F, 0.14118F},
    {0.52941F, 0.18431F, 0.12941F},
    {0.59216F, 0.23137F, 0.10980F},
    {0.64706F, 0.29020F, 0.09020F},
    {0.69412F, 0.35686F, 0.07843F},
    {0.73333F, 0.42745F, 0.07451F},
    {0.76863F, 0.49804F, 0.08235F},
    {0.79608F, 0.57255F, 0.10196F},
    {0.82353F, 0.65098F, 0.12941F},
    {0.84706F, 0.72941F, 0.16471F},
    {0.86275F, 0.81569F, 0.20392F},
    {0.87451F, 0.90196F, 0.24706F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
