#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_10 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.33725F, 0.12157F, 0.13725F},
    {0.47843F, 0.16078F, 0.14118F},
    {0.59216F, 0.23137F, 0.10980F},
    {0.67843F, 0.33333F, 0.08235F},
    {0.74510F, 0.45098F, 0.07451F},
    {0.79608F, 0.57255F, 0.10196F},
    {0.83922F, 0.70196F, 0.15294F},
    {0.86667F, 0.84314F, 0.21961F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
