#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_12 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.31373F, 0.11373F, 0.12941F},
    {0.42745F, 0.14510F, 0.14510F},
    {0.53725F, 0.18824F, 0.12941F},
    {0.61961F, 0.25882F, 0.10196F},
    {0.68627F, 0.34510F, 0.07843F},
    {0.73725F, 0.43922F, 0.07451F},
    {0.78431F, 0.53725F, 0.09020F},
    {0.81961F, 0.64314F, 0.12549F},
    {0.85098F, 0.75686F, 0.17647F},
    {0.87059F, 0.87059F, 0.23137F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
