#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_17 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.27843F, 0.10196F, 0.12157F},
    {0.35686F, 0.12549F, 0.13725F},
    {0.43529F, 0.14510F, 0.14510F},
    {0.50980F, 0.17647F, 0.13333F},
    {0.57647F, 0.21569F, 0.11373F},
    {0.62745F, 0.27059F, 0.09804F},
    {0.67451F, 0.32941F, 0.08235F},
    {0.71373F, 0.39216F, 0.07451F},
    {0.74902F, 0.45490F, 0.07451F},
    {0.78039F, 0.52549F, 0.08627F},
    {0.80784F, 0.59608F, 0.10980F},
    {0.83137F, 0.67059F, 0.13725F},
    {0.85098F, 0.74510F, 0.17255F},
    {0.86667F, 0.82353F, 0.21176F},
    {0.87451F, 0.90588F, 0.25098F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
