#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_9 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.35686F, 0.12549F, 0.13725F},
    {0.50980F, 0.17647F, 0.13333F},
    {0.62745F, 0.27059F, 0.09804F},
    {0.71373F, 0.39216F, 0.07451F},
    {0.78039F, 0.52549F, 0.08627F},
    {0.83137F, 0.67059F, 0.13725F},
    {0.86667F, 0.82353F, 0.21176F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
