#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_20 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.26275F, 0.09804F, 0.11765F},
    {0.33333F, 0.11765F, 0.13333F},
    {0.39608F, 0.13725F, 0.14118F},
    {0.46667F, 0.15686F, 0.14118F},
    {0.52157F, 0.18039F, 0.12941F},
    {0.57647F, 0.21961F, 0.11373F},
    {0.62353F, 0.26275F, 0.09804F},
    {0.65882F, 0.30980F, 0.08627F},
    {0.69804F, 0.36471F, 0.07843F},
    {0.72941F, 0.41961F, 0.07451F},
    {0.75686F, 0.47843F, 0.07843F},
    {0.78039F, 0.53333F, 0.09020F},
    {0.80392F, 0.59216F, 0.10588F},
    {0.82745F, 0.65490F, 0.12941F},
    {0.84314F, 0.71765F, 0.15686F},
    {0.85882F, 0.78431F, 0.19216F},
    {0.87059F, 0.85098F, 0.22353F},
    {0.87843F, 0.92157F, 0.25882F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
