#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SOLAR_15 = std::vector<vivid::srgb_t>{
    {0.20000F, 0.07843F, 0.09412F},
    {0.29020F, 0.10588F, 0.12549F},
    {0.37647F, 0.12941F, 0.14118F},
    {0.47059F, 0.15686F, 0.14118F},
    {0.54902F, 0.19608F, 0.12549F},
    {0.61176F, 0.25098F, 0.10196F},
    {0.66667F, 0.31765F, 0.08627F},
    {0.71373F, 0.39216F, 0.07451F},
    {0.75294F, 0.46667F, 0.07843F},
    {0.78824F, 0.54510F, 0.09412F},
    {0.81569F, 0.62745F, 0.12157F},
    {0.84314F, 0.70980F, 0.15686F},
    {0.86275F, 0.80392F, 0.20000F},
    {0.87451F, 0.89804F, 0.24706F},
    {0.88235F, 0.99216F, 0.29412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
