#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SPEED_19 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.99216F, 0.80392F},
    {0.96471F, 0.92549F, 0.68627F},
    {0.92549F, 0.86275F, 0.56863F},
    {0.88235F, 0.80392F, 0.45098F},
    {0.82353F, 0.75294F, 0.32549F},
    {0.75294F, 0.70980F, 0.21569F},
    {0.66667F, 0.67451F, 0.12549F},
    {0.57647F, 0.63922F, 0.05490F},
    {0.47843F, 0.60784F, 0.02353F},
    {0.37255F, 0.57255F, 0.04706F},
    {0.27451F, 0.53333F, 0.09020F},
    {0.17647F, 0.49412F, 0.12941F},
    {0.09412F, 0.45098F, 0.15686F},
    {0.04706F, 0.40000F, 0.17255F},
    {0.05098F, 0.34902F, 0.17647F},
    {0.07843F, 0.29804F, 0.16471F},
    {0.09412F, 0.24314F, 0.14510F},
    {0.09804F, 0.18824F, 0.11373F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
