#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SPEED_20 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.99216F, 0.80392F},
    {0.96471F, 0.92941F, 0.69412F},
    {0.92941F, 0.86667F, 0.57647F},
    {0.89020F, 0.81176F, 0.46667F},
    {0.83529F, 0.76078F, 0.34902F},
    {0.77255F, 0.72157F, 0.24706F},
    {0.69412F, 0.68235F, 0.15294F},
    {0.60784F, 0.65098F, 0.07843F},
    {0.52157F, 0.62353F, 0.02745F},
    {0.42353F, 0.58824F, 0.02745F},
    {0.32941F, 0.55686F, 0.06667F},
    {0.23137F, 0.51765F, 0.10980F},
    {0.14510F, 0.47843F, 0.14118F},
    {0.07451F, 0.43529F, 0.16078F},
    {0.04314F, 0.38824F, 0.17255F},
    {0.05882F, 0.33725F, 0.17255F},
    {0.08235F, 0.28627F, 0.16471F},
    {0.09804F, 0.23922F, 0.14118F},
    {0.09804F, 0.18431F, 0.10980F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
