#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SPEED_14 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.99216F, 0.80392F},
    {0.94510F, 0.89804F, 0.63529F},
    {0.89020F, 0.81569F, 0.47451F},
    {0.81569F, 0.74510F, 0.30980F},
    {0.70980F, 0.69020F, 0.16863F},
    {0.58431F, 0.64314F, 0.05882F},
    {0.44314F, 0.59608F, 0.02353F},
    {0.30980F, 0.54902F, 0.07451F},
    {0.17255F, 0.49020F, 0.12941F},
    {0.06275F, 0.42353F, 0.16471F},
    {0.04706F, 0.35686F, 0.17647F},
    {0.08235F, 0.28235F, 0.16078F},
    {0.09804F, 0.21176F, 0.12941F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
