#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SPEED_8 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.99216F, 0.80392F},
    {0.90196F, 0.83137F, 0.50196F},
    {0.74118F, 0.70588F, 0.20392F},
    {0.50588F, 0.61569F, 0.02353F},
    {0.24706F, 0.52157F, 0.10196F},
    {0.05098F, 0.40784F, 0.16863F},
    {0.08627F, 0.27059F, 0.15686F},
    {0.09020F, 0.13725F, 0.07451F},
};

} // namespace GOOM::COLOR::COLOR_DATA
