#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto SUNSET_2 = std::vector<vivid::srgb_t>{
    {0.95294F, 0.90588F, 0.60784F},
    {0.36078F, 0.32549F, 0.64706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
