#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TAB20B = std::vector<vivid::srgb_t>{
    {0.22353F, 0.23137F, 0.47451F},
    {0.32157F, 0.32941F, 0.63922F},
    {0.41961F, 0.43137F, 0.81176F},
    {0.61176F, 0.61961F, 0.87059F},
    {0.38824F, 0.47451F, 0.22353F},
    {0.54902F, 0.63529F, 0.32157F},
    {0.70980F, 0.81176F, 0.41961F},
    {0.80784F, 0.85882F, 0.61176F},
    {0.54902F, 0.42745F, 0.19216F},
    {0.74118F, 0.61961F, 0.22353F},
    {0.90588F, 0.72941F, 0.32157F},
    {0.90588F, 0.79608F, 0.58039F},
    {0.51765F, 0.23529F, 0.22353F},
    {0.67843F, 0.28627F, 0.29020F},
    {0.83922F, 0.38039F, 0.41961F},
    {0.90588F, 0.58824F, 0.61176F},
    {0.48235F, 0.25490F, 0.45098F},
    {0.64706F, 0.31765F, 0.58039F},
    {0.80784F, 0.42745F, 0.74118F},
    {0.87059F, 0.61961F, 0.83922F},
};

} // namespace GOOM::COLOR::COLOR_DATA
