#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TAB20C = std::vector<vivid::srgb_t>{
    {0.19216F, 0.50980F, 0.74118F},
    {0.41961F, 0.68235F, 0.83922F},
    {0.61961F, 0.79216F, 0.88235F},
    {0.77647F, 0.85882F, 0.93725F},
    {0.90196F, 0.33333F, 0.05098F},
    {0.99216F, 0.55294F, 0.23529F},
    {0.99216F, 0.68235F, 0.41961F},
    {0.99216F, 0.81569F, 0.63529F},
    {0.19216F, 0.63922F, 0.32941F},
    {0.45490F, 0.76863F, 0.46275F},
    {0.63137F, 0.85098F, 0.60784F},
    {0.78039F, 0.91373F, 0.75294F},
    {0.45882F, 0.41961F, 0.69412F},
    {0.61961F, 0.60392F, 0.78431F},
    {0.73725F, 0.74118F, 0.86275F},
    {0.85490F, 0.85490F, 0.92157F},
    {0.38824F, 0.38824F, 0.38824F},
    {0.58824F, 0.58824F, 0.58824F},
    {0.74118F, 0.74118F, 0.74118F},
    {0.85098F, 0.85098F, 0.85098F},
};

} // namespace GOOM::COLOR::COLOR_DATA
