#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TAB20 = std::vector<vivid::srgb_t>{
    {0.12157F, 0.46667F, 0.70588F},
    {0.68235F, 0.78039F, 0.90980F},
    {1.00000F, 0.49804F, 0.05490F},
    {1.00000F, 0.73333F, 0.47059F},
    {0.17255F, 0.62745F, 0.17255F},
    {0.59608F, 0.87451F, 0.54118F},
    {0.83922F, 0.15294F, 0.15686F},
    {1.00000F, 0.59608F, 0.58824F},
    {0.58039F, 0.40392F, 0.74118F},
    {0.77255F, 0.69020F, 0.83529F},
    {0.54902F, 0.33725F, 0.29412F},
    {0.76863F, 0.61176F, 0.58039F},
    {0.89020F, 0.46667F, 0.76078F},
    {0.96863F, 0.71373F, 0.82353F},
    {0.49804F, 0.49804F, 0.49804F},
    {0.78039F, 0.78039F, 0.78039F},
    {0.73725F, 0.74118F, 0.13333F},
    {0.85882F, 0.85882F, 0.55294F},
    {0.09020F, 0.74510F, 0.81176F},
    {0.61961F, 0.85490F, 0.89804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
