#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TABLEAULIGHT_10 = std::vector<vivid::srgb_t>{
    {0.68235F, 0.78039F, 0.90980F},
    {1.00000F, 0.73333F, 0.47059F},
    {0.59608F, 0.87451F, 0.54118F},
    {1.00000F, 0.59608F, 0.58824F},
    {0.77255F, 0.69020F, 0.83529F},
    {0.76863F, 0.61176F, 0.58039F},
    {0.96863F, 0.71373F, 0.82353F},
    {0.78039F, 0.78039F, 0.78039F},
    {0.85882F, 0.85882F, 0.55294F},
    {0.61961F, 0.85490F, 0.89804F},
};

} // namespace GOOM::COLOR::COLOR_DATA
