#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEAL_6 = std::vector<vivid::srgb_t>{
    {0.81961F, 0.93333F, 0.91765F},
    {0.65882F, 0.85882F, 0.85098F},
    {0.52157F, 0.76863F, 0.78824F},
    {0.30980F, 0.56471F, 0.65098F},
    {0.23137F, 0.45098F, 0.56078F},
    {0.16471F, 0.33725F, 0.45490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
