#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEALROSE_5 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.57647F, 0.57255F},
    {0.69412F, 0.78039F, 0.70196F},
    {0.94510F, 0.91765F, 0.78431F},
    {0.89804F, 0.72549F, 0.67843F},
    {0.81569F, 0.34510F, 0.49412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
