#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEALROSE_2 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.57647F, 0.57255F},
    {0.81569F, 0.34510F, 0.49412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
