#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEAL_2 = std::vector<vivid::srgb_t>{
    {0.81961F, 0.93333F, 0.91765F},
    {0.16471F, 0.33725F, 0.45490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
