#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEALGRN_2 = std::vector<vivid::srgb_t>{
    {0.69020F, 0.94902F, 0.73725F},
    {0.14510F, 0.49020F, 0.59608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
