#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEMPO_14 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96471F, 0.95686F},
    {0.89020F, 0.89020F, 0.84314F},
    {0.78431F, 0.83137F, 0.74510F},
    {0.66275F, 0.77255F, 0.65098F},
    {0.54118F, 0.71765F, 0.58431F},
    {0.39608F, 0.66667F, 0.53333F},
    {0.23922F, 0.61176F, 0.50588F},
    {0.10980F, 0.54902F, 0.49412F},
    {0.06667F, 0.47451F, 0.47059F},
    {0.09020F, 0.40000F, 0.43529F},
    {0.10980F, 0.33333F, 0.39608F},
    {0.10980F, 0.25882F, 0.35294F},
    {0.09804F, 0.19216F, 0.30980F},
    {0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
