#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEMPO_8 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96471F, 0.95686F},
    {0.80000F, 0.83922F, 0.75686F},
    {0.57255F, 0.73333F, 0.60000F},
    {0.31373F, 0.63529F, 0.51765F},
    {0.07451F, 0.51765F, 0.48235F},
    {0.09804F, 0.38431F, 0.42745F},
    {0.10980F, 0.25098F, 0.34510F},
    {0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
