#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEMPO_12 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96471F, 0.95686F},
    {0.87451F, 0.88235F, 0.82745F},
    {0.74118F, 0.80784F, 0.70980F},
    {0.59216F, 0.74118F, 0.61176F},
    {0.43529F, 0.67843F, 0.54510F},
    {0.25490F, 0.61569F, 0.50980F},
    {0.10196F, 0.54118F, 0.49020F},
    {0.07059F, 0.45882F, 0.46275F},
    {0.10196F, 0.37255F, 0.41961F},
    {0.10980F, 0.28627F, 0.36863F},
    {0.10196F, 0.20392F, 0.31373F},
    {0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
