#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEMPO_20 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96471F, 0.95686F},
    {0.92941F, 0.91765F, 0.88235F},
    {0.85098F, 0.86667F, 0.80392F},
    {0.77647F, 0.82745F, 0.73725F},
    {0.69412F, 0.78431F, 0.67451F},
    {0.61176F, 0.74902F, 0.62353F},
    {0.52157F, 0.70980F, 0.57647F},
    {0.42745F, 0.67843F, 0.54118F},
    {0.32941F, 0.64314F, 0.51765F},
    {0.21961F, 0.60000F, 0.50588F},
    {0.12941F, 0.55686F, 0.49412F},
    {0.07059F, 0.50980F, 0.48235F},
    {0.07059F, 0.46275F, 0.46275F},
    {0.08627F, 0.41176F, 0.44314F},
    {0.10196F, 0.36078F, 0.41569F},
    {0.10980F, 0.31373F, 0.38431F},
    {0.10980F, 0.26275F, 0.35294F},
    {0.10196F, 0.21569F, 0.32549F},
    {0.09412F, 0.16471F, 0.29412F},
    {0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
