#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEMPO_5 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96471F, 0.95686F},
    {0.63137F, 0.75686F, 0.63137F},
    {0.16471F, 0.57647F, 0.49804F},
    {0.10588F, 0.34902F, 0.40784F},
    {0.08235F, 0.11373F, 0.26667F},
};

} // namespace GOOM::COLOR::COLOR_DATA
