#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TEMPS_4 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.57647F, 0.57255F},
    {0.61176F, 0.79608F, 0.52549F},
    {0.93333F, 0.70588F, 0.47451F},
    {0.81176F, 0.34902F, 0.49412F},
};

} // namespace GOOM::COLOR::COLOR_DATA
