#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto THERMAL_20 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.02745F, 0.17255F, 0.30196F},
    {0.07059F, 0.19608F, 0.43529F},
    {0.15294F, 0.20392F, 0.56863F},
    {0.27451F, 0.20784F, 0.62745F},
    {0.35686F, 0.23922F, 0.60784F},
    {0.43137F, 0.27843F, 0.58039F},
    {0.50196F, 0.30588F, 0.56078F},
    {0.57255F, 0.33333F, 0.54510F},
    {0.65098F, 0.36078F, 0.52549F},
    {0.72941F, 0.38431F, 0.49412F},
    {0.80784F, 0.41176F, 0.44314F},
    {0.87843F, 0.44314F, 0.38824F},
    {0.93333F, 0.49020F, 0.32549F},
    {0.97255F, 0.55686F, 0.26667F},
    {0.98431F, 0.63137F, 0.23922F},
    {0.98431F, 0.71765F, 0.23922F},
    {0.97255F, 0.80392F, 0.26667F},
    {0.94510F, 0.89412F, 0.30980F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
