#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto THERMAL_8 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.12157F, 0.20392F, 0.52941F},
    {0.38824F, 0.25490F, 0.59608F},
    {0.58431F, 0.33725F, 0.54118F},
    {0.80000F, 0.40784F, 0.45098F},
    {0.96078F, 0.52549F, 0.29020F},
    {0.98039F, 0.74510F, 0.24706F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
