#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto THERMAL_18 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.03137F, 0.17647F, 0.32157F},
    {0.08627F, 0.20000F, 0.46667F},
    {0.20000F, 0.20000F, 0.60784F},
    {0.31373F, 0.22353F, 0.61961F},
    {0.40000F, 0.26275F, 0.59216F},
    {0.47843F, 0.29804F, 0.56863F},
    {0.56078F, 0.32941F, 0.54902F},
    {0.64706F, 0.36078F, 0.52549F},
    {0.73333F, 0.38431F, 0.49020F},
    {0.81961F, 0.41569F, 0.43529F},
    {0.89804F, 0.45490F, 0.36863F},
    {0.95294F, 0.51373F, 0.29804F},
    {0.98039F, 0.59608F, 0.24706F},
    {0.98824F, 0.68627F, 0.23529F},
    {0.97647F, 0.78431F, 0.25882F},
    {0.94902F, 0.88235F, 0.30196F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
