#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto THERMAL_15 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.03529F, 0.18431F, 0.34902F},
    {0.12157F, 0.20392F, 0.52941F},
    {0.27843F, 0.21176F, 0.62745F},
    {0.38824F, 0.25490F, 0.59608F},
    {0.48627F, 0.30196F, 0.56471F},
    {0.58431F, 0.33725F, 0.54118F},
    {0.69412F, 0.37255F, 0.50980F},
    {0.80000F, 0.40784F, 0.45098F},
    {0.89412F, 0.45098F, 0.37255F},
    {0.96078F, 0.52549F, 0.29020F},
    {0.98431F, 0.62353F, 0.23922F},
    {0.98039F, 0.74510F, 0.24706F},
    {0.95686F, 0.86275F, 0.29412F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
