#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto THERMAL_16 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.03529F, 0.18039F, 0.33725F},
    {0.10980F, 0.20392F, 0.50980F},
    {0.25098F, 0.20392F, 0.62353F},
    {0.36078F, 0.24314F, 0.60392F},
    {0.45490F, 0.28627F, 0.57255F},
    {0.54510F, 0.32549F, 0.55294F},
    {0.63922F, 0.35686F, 0.52549F},
    {0.74118F, 0.38824F, 0.48627F},
    {0.83922F, 0.42353F, 0.42353F},
    {0.92157F, 0.47451F, 0.34510F},
    {0.96863F, 0.54902F, 0.27059F},
    {0.98824F, 0.65098F, 0.23529F},
    {0.98039F, 0.75686F, 0.25098F},
    {0.95294F, 0.86667F, 0.29412F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
