#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto THERMAL_14 = std::vector<vivid::srgb_t>{
    {0.01569F, 0.13725F, 0.20000F},
    {0.04314F, 0.18824F, 0.36471F},
    {0.14510F, 0.20392F, 0.56078F},
    {0.30588F, 0.21961F, 0.61961F},
    {0.41569F, 0.27059F, 0.58431F},
    {0.52157F, 0.31765F, 0.55686F},
    {0.63529F, 0.35686F, 0.52941F},
    {0.74510F, 0.38824F, 0.48235F},
    {0.85882F, 0.43137F, 0.40784F},
    {0.94510F, 0.50196F, 0.30980F},
    {0.98431F, 0.60000F, 0.24706F},
    {0.98431F, 0.72549F, 0.24314F},
    {0.96078F, 0.84706F, 0.28627F},
    {0.90980F, 0.98039F, 0.35686F},
};

} // namespace GOOM::COLOR::COLOR_DATA
