#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOFINO_13 = std::vector<vivid::srgb_t>{
    {0.87059F, 0.85098F, 1.00000F},
    {0.65098F, 0.69412F, 0.90196F},
    {0.43137F, 0.53725F, 0.79608F},
    {0.24314F, 0.36863F, 0.60392F},
    {0.15294F, 0.23529F, 0.39608F},
    {0.08627F, 0.12549F, 0.20392F},
    {0.05098F, 0.08627F, 0.07451F},
    {0.08235F, 0.17255F, 0.09412F},
    {0.14118F, 0.30196F, 0.15686F},
    {0.21569F, 0.45098F, 0.23529F},
    {0.36078F, 0.61961F, 0.34118F},
    {0.61569F, 0.77255F, 0.48235F},
    {0.85882F, 0.90196F, 0.60784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
