#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOFINO_7 = std::vector<vivid::srgb_t>{
    {0.87059F, 0.85098F, 1.00000F},
    {0.43137F, 0.53725F, 0.79608F},
    {0.15294F, 0.23529F, 0.39608F},
    {0.05098F, 0.08627F, 0.07451F},
    {0.14118F, 0.30196F, 0.15686F},
    {0.36078F, 0.61961F, 0.34118F},
    {0.85882F, 0.90196F, 0.60784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
