#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOFINO_18 = std::vector<vivid::srgb_t>{
    {0.87059F, 0.85098F, 1.00000F},
    {0.71373F, 0.73725F, 0.92941F},
    {0.55686F, 0.62745F, 0.86275F},
    {0.40000F, 0.51373F, 0.77647F},
    {0.27059F, 0.39608F, 0.64706F},
    {0.19216F, 0.29804F, 0.49412F},
    {0.13333F, 0.20784F, 0.34902F},
    {0.08627F, 0.12941F, 0.21176F},
    {0.05882F, 0.08235F, 0.10588F},
    {0.05882F, 0.10588F, 0.07059F},
    {0.08627F, 0.17647F, 0.09412F},
    {0.12549F, 0.27059F, 0.14118F},
    {0.17255F, 0.37255F, 0.19216F},
    {0.23137F, 0.48235F, 0.25098F},
    {0.34118F, 0.60392F, 0.32941F},
    {0.50980F, 0.71373F, 0.42353F},
    {0.68627F, 0.80784F, 0.51765F},
    {0.85882F, 0.90196F, 0.60784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
