#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOFINO_12 = std::vector<vivid::srgb_t>{
    {0.87059F, 0.85098F, 1.00000F},
    {0.62745F, 0.67843F, 0.89412F},
    {0.39216F, 0.50588F, 0.77255F},
    {0.21569F, 0.32941F, 0.54510F},
    {0.12549F, 0.19216F, 0.31765F},
    {0.06667F, 0.09020F, 0.12941F},
    {0.06667F, 0.12157F, 0.07059F},
    {0.11765F, 0.25098F, 0.12941F},
    {0.19216F, 0.40784F, 0.21176F},
    {0.33333F, 0.59216F, 0.32549F},
    {0.59216F, 0.76078F, 0.47059F},
    {0.85882F, 0.90196F, 0.60784F},
};

} // namespace GOOM::COLOR::COLOR_DATA
