#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOKYO_20 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.05490F, 0.20392F},
    {0.18039F, 0.08235F, 0.24706F},
    {0.26275F, 0.12157F, 0.29412F},
    {0.34118F, 0.16863F, 0.34510F},
    {0.41961F, 0.22745F, 0.39216F},
    {0.47451F, 0.29020F, 0.43137F},
    {0.51373F, 0.35294F, 0.46275F},
    {0.53333F, 0.40392F, 0.48627F},
    {0.54902F, 0.45490F, 0.50196F},
    {0.55686F, 0.50588F, 0.51765F},
    {0.56863F, 0.55294F, 0.52941F},
    {0.57647F, 0.60000F, 0.54510F},
    {0.58431F, 0.64706F, 0.55686F},
    {0.59608F, 0.69804F, 0.57255F},
    {0.62353F, 0.75686F, 0.59216F},
    {0.66667F, 0.82353F, 0.62745F},
    {0.75294F, 0.89804F, 0.68235F},
    {0.84314F, 0.95294F, 0.74118F},
    {0.92941F, 0.98431F, 0.80000F},
    {0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
