#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOKYO_17 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.05490F, 0.20392F},
    {0.20000F, 0.09020F, 0.25490F},
    {0.29412F, 0.13725F, 0.31373F},
    {0.38824F, 0.20000F, 0.37255F},
    {0.46275F, 0.27451F, 0.42353F},
    {0.50980F, 0.34902F, 0.46275F},
    {0.53725F, 0.41176F, 0.49020F},
    {0.55294F, 0.47059F, 0.50980F},
    {0.56471F, 0.52941F, 0.52549F},
    {0.57255F, 0.58431F, 0.54118F},
    {0.58431F, 0.64314F, 0.55686F},
    {0.60000F, 0.70196F, 0.57255F},
    {0.63137F, 0.77255F, 0.60000F},
    {0.69804F, 0.85490F, 0.64706F},
    {0.80784F, 0.93333F, 0.71765F},
    {0.91373F, 0.98039F, 0.78824F},
    {0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
