#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOKYO_14 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.05490F, 0.20392F},
    {0.22353F, 0.10196F, 0.27059F},
    {0.33725F, 0.16471F, 0.34118F},
    {0.44314F, 0.25098F, 0.40784F},
    {0.50588F, 0.34118F, 0.45882F},
    {0.53725F, 0.41961F, 0.49020F},
    {0.55686F, 0.49412F, 0.51373F},
    {0.56863F, 0.56078F, 0.53333F},
    {0.58039F, 0.63529F, 0.55294F},
    {0.60000F, 0.70980F, 0.57647F},
    {0.64706F, 0.79608F, 0.61176F},
    {0.75686F, 0.90196F, 0.68627F},
    {0.89020F, 0.97255F, 0.77255F},
    {0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
