#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOKYO_8 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.05490F, 0.20392F},
    {0.31765F, 0.15294F, 0.32941F},
    {0.49412F, 0.31765F, 0.44706F},
    {0.54902F, 0.46275F, 0.50588F},
    {0.57255F, 0.59608F, 0.54118F},
    {0.60784F, 0.73333F, 0.58431F},
    {0.78039F, 0.91765F, 0.69804F},
    {0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
