#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TOKYO_11 = std::vector<vivid::srgb_t>{
    {0.10196F, 0.05490F, 0.20392F},
    {0.25882F, 0.11765F, 0.29020F},
    {0.40392F, 0.21569F, 0.38431F},
    {0.50196F, 0.32941F, 0.45490F},
    {0.54510F, 0.43529F, 0.49804F},
    {0.56471F, 0.52941F, 0.52549F},
    {0.58039F, 0.61961F, 0.54902F},
    {0.60392F, 0.71373F, 0.57647F},
    {0.68235F, 0.83922F, 0.63529F},
    {0.85490F, 0.95686F, 0.74902F},
    {0.99608F, 0.99608F, 0.84706F},
};

} // namespace GOOM::COLOR::COLOR_DATA
