#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TRAFFICLIGHT_9 = std::vector<vivid::srgb_t>{
    {0.69412F, 0.01176F, 0.09412F},
    {0.85882F, 0.63137F, 0.22745F},
    {0.18824F, 0.57647F, 0.26275F},
    {0.84706F, 0.14510F, 0.14902F},
    {1.00000F, 0.75686F, 0.33725F},
    {0.41176F, 0.71765F, 0.39216F},
    {0.94902F, 0.42353F, 0.39216F},
    {1.00000F, 0.86667F, 0.44314F},
    {0.62353F, 0.80392F, 0.60000F},
};

} // namespace GOOM::COLOR::COLOR_DATA
