#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TROPIC_6 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.60784F, 0.61961F},
    {0.25882F, 0.71765F, 0.72549F},
    {0.65490F, 0.82745F, 0.83137F},
    {0.89412F, 0.75686F, 0.85098F},
    {0.83922F, 0.56863F, 0.75686F},
    {0.78039F, 0.36471F, 0.67059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
