#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURBID_7 = std::vector<vivid::srgb_t>{
    {0.91373F, 0.96471F, 0.67059F},
    {0.82745F, 0.77647F, 0.44314F},
    {0.74902F, 0.59216F, 0.27843F},
    {0.63137F, 0.43922F, 0.23137F},
    {0.47451F, 0.32549F, 0.21961F},
    {0.30588F, 0.22353F, 0.18039F},
    {0.13333F, 0.12157F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
