#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURBID_6 = std::vector<vivid::srgb_t>{
    {0.91373F, 0.96471F, 0.67059F},
    {0.81176F, 0.73725F, 0.40000F},
    {0.70980F, 0.52941F, 0.25098F},
    {0.54118F, 0.36863F, 0.22745F},
    {0.33725F, 0.24314F, 0.18824F},
    {0.13333F, 0.12157F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
