#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURBID_10 = std::vector<vivid::srgb_t>{
    {0.91373F, 0.96471F, 0.67059F},
    {0.85490F, 0.83529F, 0.51373F},
    {0.80392F, 0.70980F, 0.37255F},
    {0.74902F, 0.59216F, 0.27843F},
    {0.67843F, 0.49020F, 0.23922F},
    {0.58431F, 0.39608F, 0.22745F},
    {0.47451F, 0.32549F, 0.21961F},
    {0.36078F, 0.25882F, 0.19608F},
    {0.24314F, 0.18824F, 0.15686F},
    {0.13333F, 0.12157F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
