#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURBID_3 = std::vector<vivid::srgb_t>{
    {0.91373F, 0.96471F, 0.67059F},
    {0.63137F, 0.43922F, 0.23137F},
    {0.13333F, 0.12157F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
