#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURBID_18 = std::vector<vivid::srgb_t>{
    {0.91373F, 0.96471F, 0.67059F},
    {0.87843F, 0.89412F, 0.58431F},
    {0.85098F, 0.82745F, 0.50196F},
    {0.82353F, 0.76078F, 0.42745F},
    {0.79608F, 0.69804F, 0.36078F},
    {0.76863F, 0.63529F, 0.30588F},
    {0.73725F, 0.57255F, 0.26667F},
    {0.70196F, 0.51765F, 0.24706F},
    {0.65882F, 0.46667F, 0.23529F},
    {0.60784F, 0.41961F, 0.23137F},
    {0.55294F, 0.37647F, 0.22745F},
    {0.49412F, 0.33725F, 0.22353F},
    {0.43529F, 0.29804F, 0.21176F},
    {0.37255F, 0.26275F, 0.20000F},
    {0.31373F, 0.23137F, 0.18039F},
    {0.25098F, 0.19608F, 0.16078F},
    {0.19216F, 0.15686F, 0.13333F},
    {0.13333F, 0.12157F, 0.10588F},
};

} // namespace GOOM::COLOR::COLOR_DATA
