#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURKU_11 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.13333F, 0.13333F, 0.12157F},
    {0.23529F, 0.23529F, 0.19608F},
    {0.33725F, 0.33725F, 0.25098F},
    {0.44314F, 0.43922F, 0.29804F},
    {0.57647F, 0.54902F, 0.35686F},
    {0.72549F, 0.62745F, 0.43137F},
    {0.84706F, 0.65490F, 0.50980F},
    {0.93725F, 0.69412F, 0.63137F},
    {0.99216F, 0.79608F, 0.78039F},
    {1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
