#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURKU_20 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.08235F, 0.08235F, 0.07451F},
    {0.13725F, 0.13725F, 0.12157F},
    {0.18824F, 0.18824F, 0.16471F},
    {0.24706F, 0.24706F, 0.20392F},
    {0.30196F, 0.29804F, 0.23137F},
    {0.35686F, 0.35686F, 0.25882F},
    {0.40784F, 0.40784F, 0.28235F},
    {0.46667F, 0.45882F, 0.30980F},
    {0.53725F, 0.51765F, 0.33725F},
    {0.61176F, 0.57255F, 0.37255F},
    {0.69804F, 0.61569F, 0.41569F},
    {0.76863F, 0.64314F, 0.45490F},
    {0.82745F, 0.65098F, 0.49804F},
    {0.88235F, 0.66275F, 0.54902F},
    {0.92941F, 0.68627F, 0.61176F},
    {0.96863F, 0.73333F, 0.69412F},
    {0.98824F, 0.78431F, 0.76863F},
    {1.00000F, 0.84706F, 0.83922F},
    {1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
