#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURKU_17 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.09412F, 0.09412F, 0.08627F},
    {0.15686F, 0.15686F, 0.13725F},
    {0.22353F, 0.22353F, 0.18824F},
    {0.28627F, 0.28627F, 0.22745F},
    {0.35294F, 0.35294F, 0.25882F},
    {0.41961F, 0.41569F, 0.28627F},
    {0.49020F, 0.48235F, 0.31765F},
    {0.57647F, 0.54902F, 0.35686F},
    {0.66667F, 0.60392F, 0.40000F},
    {0.76078F, 0.63922F, 0.45098F},
    {0.83137F, 0.65490F, 0.50196F},
    {0.89412F, 0.66667F, 0.56078F},
    {0.94902F, 0.70196F, 0.64706F},
    {0.98431F, 0.76471F, 0.74118F},
    {0.99608F, 0.83137F, 0.82745F},
    {1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
