#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURKU_15 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.10196F, 0.10196F, 0.09412F},
    {0.17255F, 0.17255F, 0.15294F},
    {0.25098F, 0.25098F, 0.20392F},
    {0.32549F, 0.32157F, 0.24314F},
    {0.39608F, 0.39608F, 0.27843F},
    {0.47451F, 0.46667F, 0.31373F},
    {0.57647F, 0.54902F, 0.35686F},
    {0.68627F, 0.61176F, 0.40784F},
    {0.78431F, 0.64314F, 0.46667F},
    {0.85882F, 0.65882F, 0.52549F},
    {0.92549F, 0.68235F, 0.60784F},
    {0.97647F, 0.74902F, 0.71765F},
    {0.99608F, 0.82353F, 0.81569F},
    {1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
