#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto TURKU_4 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.00000F, 0.00000F},
    {0.37255F, 0.37255F, 0.26667F},
    {0.81176F, 0.65098F, 0.48627F},
    {1.00000F, 0.90196F, 0.90196F},
};

} // namespace GOOM::COLOR::COLOR_DATA
