#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIK_14 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.07059F, 0.38039F},
    {0.00784F, 0.19216F, 0.45882F},
    {0.01569F, 0.30980F, 0.53333F},
    {0.13725F, 0.45098F, 0.62745F},
    {0.35294F, 0.60392F, 0.72941F},
    {0.60392F, 0.76078F, 0.83529F},
    {0.84706F, 0.89412F, 0.91373F},
    {0.92941F, 0.84314F, 0.79608F},
    {0.87059F, 0.69020F, 0.58431F},
    {0.80784F, 0.54510F, 0.39216F},
    {0.74902F, 0.41176F, 0.21961F},
    {0.63922F, 0.24314F, 0.05098F},
    {0.48627F, 0.10588F, 0.02353F},
    {0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
