#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIK_3 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.07059F, 0.38039F},
    {0.92549F, 0.89804F, 0.87843F},
    {0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
