#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIK_13 = std::vector<vivid::srgb_t>{
    {0.00000F, 0.07059F, 0.38039F},
    {0.00784F, 0.20000F, 0.46275F},
    {0.02353F, 0.32941F, 0.54510F},
    {0.18824F, 0.49020F, 0.65098F},
    {0.44314F, 0.65882F, 0.76863F},
    {0.70196F, 0.81961F, 0.87451F},
    {0.92549F, 0.89804F, 0.87843F},
    {0.89412F, 0.74902F, 0.66667F},
    {0.82745F, 0.59216F, 0.45490F},
    {0.76471F, 0.44706F, 0.26275F},
    {0.67059F, 0.28235F, 0.07843F},
    {0.49412F, 0.11373F, 0.02353F},
    {0.34902F, 0.00000F, 0.03137F},
};

} // namespace GOOM::COLOR::COLOR_DATA
