#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIRIDIS_11 = std::vector<vivid::srgb_t>{
    {0.26667F, 0.00392F, 0.32941F},
    {0.28235F, 0.14510F, 0.46275F},
    {0.25490F, 0.26667F, 0.52941F},
    {0.20784F, 0.37255F, 0.55294F},
    {0.16471F, 0.47059F, 0.55686F},
    {0.12941F, 0.56863F, 0.54902F},
    {0.13333F, 0.65882F, 0.51765F},
    {0.25882F, 0.74510F, 0.44314F},
    {0.47843F, 0.81961F, 0.31765F},
    {0.74118F, 0.87451F, 0.14902F},
    {0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
