#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIRIDIS_10 = std::vector<vivid::srgb_t>{
    {0.26667F, 0.00392F, 0.32941F},
    {0.28235F, 0.15686F, 0.47059F},
    {0.24314F, 0.29020F, 0.53725F},
    {0.19216F, 0.40784F, 0.55686F},
    {0.14902F, 0.50980F, 0.55686F},
    {0.12157F, 0.61961F, 0.53725F},
    {0.20784F, 0.71765F, 0.47451F},
    {0.42353F, 0.80392F, 0.35294F},
    {0.70980F, 0.87059F, 0.16863F},
    {0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
