#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIRIDIS_3 = std::vector<vivid::srgb_t>{
    {0.26667F, 0.00392F, 0.32941F},
    {0.12941F, 0.56863F, 0.54902F},
    {0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
