#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIRIDIS_18 = std::vector<vivid::srgb_t>{
    {0.26667F, 0.00392F, 0.32941F},
    {0.28235F, 0.09020F, 0.41176F},
    {0.27843F, 0.16471F, 0.47843F},
    {0.26275F, 0.23922F, 0.51765F},
    {0.23922F, 0.30588F, 0.54118F},
    {0.20784F, 0.36863F, 0.55294F},
    {0.18039F, 0.42745F, 0.55686F},
    {0.16078F, 0.48235F, 0.55686F},
    {0.13725F, 0.53725F, 0.55686F},
    {0.12157F, 0.59216F, 0.54510F},
    {0.12941F, 0.64706F, 0.52157F},
    {0.18039F, 0.70196F, 0.48627F},
    {0.27451F, 0.75294F, 0.43529F},
    {0.39608F, 0.79608F, 0.36863F},
    {0.53725F, 0.83529F, 0.28235F},
    {0.69020F, 0.86667F, 0.18431F},
    {0.84706F, 0.88627F, 0.09804F},
    {0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
