#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIRIDIS_9 = std::vector<vivid::srgb_t>{
    {0.26667F, 0.00392F, 0.32941F},
    {0.27843F, 0.17647F, 0.48235F},
    {0.23137F, 0.32157F, 0.54510F},
    {0.17255F, 0.44706F, 0.55686F},
    {0.12941F, 0.56863F, 0.54902F},
    {0.15294F, 0.67843F, 0.50588F},
    {0.36078F, 0.78431F, 0.38824F},
    {0.66667F, 0.86275F, 0.19608F},
    {0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
