#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIRIDIS_16 = std::vector<vivid::srgb_t>{
    {0.26667F, 0.00392F, 0.32941F},
    {0.28235F, 0.10196F, 0.42353F},
    {0.27843F, 0.18431F, 0.49020F},
    {0.25490F, 0.26667F, 0.52941F},
    {0.22353F, 0.33725F, 0.54902F},
    {0.19216F, 0.40784F, 0.55686F},
    {0.16471F, 0.47059F, 0.55686F},
    {0.13725F, 0.53333F, 0.55686F},
    {0.12157F, 0.59608F, 0.54510F},
    {0.13333F, 0.65882F, 0.51765F},
    {0.20784F, 0.71765F, 0.47451F},
    {0.32941F, 0.77255F, 0.40784F},
    {0.47843F, 0.81961F, 0.31765F},
    {0.64706F, 0.85882F, 0.21176F},
    {0.82353F, 0.88627F, 0.10588F},
    {0.99216F, 0.90588F, 0.14510F},
};

} // namespace GOOM::COLOR::COLOR_DATA
