#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIVID_10 = std::vector<vivid::srgb_t>{
    {0.89804F, 0.52549F, 0.02353F},
    {0.36471F, 0.41176F, 0.69412F},
    {0.32157F, 0.73725F, 0.63922F},
    {0.60000F, 0.78824F, 0.27059F},
    {0.80000F, 0.38039F, 0.69020F},
    {0.14118F, 0.47451F, 0.42353F},
    {0.85490F, 0.64706F, 0.10588F},
    {0.18431F, 0.54118F, 0.76863F},
    {0.46275F, 0.30588F, 0.62353F},
    {0.92941F, 0.39216F, 0.35294F},
};

} // namespace GOOM::COLOR::COLOR_DATA
