#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto VIVID_4 = std::vector<vivid::srgb_t>{
    {0.89804F, 0.52549F, 0.02353F},
    {0.36471F, 0.41176F, 0.69412F},
    {0.32157F, 0.73725F, 0.63922F},
    {0.60000F, 0.78824F, 0.27059F},
};

} // namespace GOOM::COLOR::COLOR_DATA
