#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto YLGN_5 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.76078F, 0.90196F, 0.60000F},
    {0.47059F, 0.77647F, 0.47451F},
    {0.19216F, 0.63922F, 0.32941F},
    {0.00000F, 0.40784F, 0.21569F},
};

} // namespace GOOM::COLOR::COLOR_DATA
