#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto YLGN_7 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.80000F},
    {0.85098F, 0.94118F, 0.63922F},
    {0.67843F, 0.86667F, 0.55686F},
    {0.47059F, 0.77647F, 0.47451F},
    {0.25490F, 0.67059F, 0.36471F},
    {0.13725F, 0.51765F, 0.26275F},
    {0.00000F, 0.35294F, 0.19608F},
};

} // namespace GOOM::COLOR::COLOR_DATA
