#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto YLGN_3 = std::vector<vivid::srgb_t>{
    {0.96863F, 0.98824F, 0.72549F},
    {0.67843F, 0.86667F, 0.55686F},
    {0.19216F, 0.63922F, 0.32941F},
};

} // namespace GOOM::COLOR::COLOR_DATA
