#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto YLORRD_4 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.69804F},
    {0.99608F, 0.80000F, 0.36078F},
    {0.99216F, 0.55294F, 0.23529F},
    {0.89020F, 0.10196F, 0.10980F},
};

} // namespace GOOM::COLOR::COLOR_DATA
