#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto YLORRD_7 = std::vector<vivid::srgb_t>{
    {1.00000F, 1.00000F, 0.69804F},
    {0.99608F, 0.85098F, 0.46275F},
    {0.99608F, 0.69804F, 0.29804F},
    {0.99216F, 0.55294F, 0.23529F},
    {0.98824F, 0.30588F, 0.16471F},
    {0.89020F, 0.10196F, 0.10980F},
    {0.69412F, 0.00000F, 0.14902F},
};

} // namespace GOOM::COLOR::COLOR_DATA
