#pragma once

// IMPORTANT - THIS CODE IS GENERATED BY:
//
//  'depends/goom-libs/src/goom/src/color/color_data/create_colormaps.py'
//
// DO NOT EDIT!!

#include "vivid/types.h"

#include <vector>

namespace GOOM::COLOR::COLOR_DATA
{

inline const auto YLORBR_3 = std::vector<vivid::srgb_t>{
    {1.00000F, 0.96863F, 0.73725F},
    {0.99608F, 0.76863F, 0.30980F},
    {0.85098F, 0.37255F, 0.05490F},
};

} // namespace GOOM::COLOR::COLOR_DATA
